### ISSUE TITLE
Modal width change issue

### ISSUE THREAD

**Issue by mnabialek** [tailwindlabs/tailwindui-issues#1095]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name:  Centered with single action

**Describe the bug**
When resizing window with different modal width, modal disappears.

**To Reproduce**

1. Go to https://tailwindui.com/components/application-ui/overlays/modals  
2. Copy HTML version of **Centered with single action** component 
3. Go to  https://play.tailwindcss.com HTML tab and paste code. 
4. Try to resize modal, you will see everything is fine (modal is always visible no matter of width of right panel with preview). 
5. Now let's assume we want to change modal width - change 

```
sm:max-w-sm sm:w-full
```

into for example:

```
w-full
```

or 

```
sm:max-w-4xl sm:w-full
```
6. Try to resize component and you will see it disappears for some widths but it appears again for sm breakpoint.

**Additional context**
Maybe there is something obvious here to fix but from what I see problem is with this:

```
<!-- This element is to trick the browser into centering the modal contents. -->
<span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">​</span>
```

**Comment by reinink** [comment]
Hey!

So this is related to the interesting hack we use to make sure the modals are properly centered:

```html
<!-- This element is to trick the browser into centering the modal contents. -->
<span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
```

Basically we render this `span` element (which has a hidden character in it) as well as the modal panel as an `inline-block` element, and then apply `align-middle` to the modal panel to vertically center it. Pretty confusing stuff 😵‍💫

We might eventually update our modals to stop using this hack (we've been prototyping some alternative approaches), but in the meantime you can get around this issue by removing any whitespace between the span and the modal panel:

```html
<span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span><div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6"><!-- ... --></div>
```

This works automatically in React which doesn't render any space between these elements.

Here is a working demo of this using `sm:max-w-4xl` instead of `sm:max-w-sm`:

https://play.tailwindcss.com/AkezT79L4o

Hope that helps! 💪

**Comment by mnabialek** [comment]
Thanks @reinink Removing whitespace between span and modal panel did the trick!
