### ISSUE TITLE
Simple alert modal displays incorrectly when removing transform in v3.0

### ISSUE THREAD

**Issue by andgith** [tailwindlabs/tailwindui-issues#1096]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Simple alert

**Describe the bug**
When removing the transform class mentioned at: https://tailwindcss.com/docs/upgrade-guide#automatic-transforms-and-filters the overlay displays over the modal.

**To Reproduce**
Remove the 'transform' class from TransitionChild

**Expected behavior**
I may just be misunderstanding when the 'transform' class can be removed...

**Screenshots**
![image](https://user-images.githubusercontent.com/20873476/147122862-6f821630-8a6c-4719-8ce2-30eb541f77f4.png)

**Browser/Device (if applicable)**
 - Version 3.0.7

**Comment by RomkeVdMeulen** [comment]
I've looked into this. Turns out `.transform` still exists in v3, probably for backward compatibility. It's implemention is `transform: var(--tw-transform);`. It isn't actually needed for transforms anymore: `.translate-y-4` for example also includes this style instruction.

However, a possibly unintended side-effect of adding an empty transform is that it still [starts a new stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/transform). It was because of this that the modal was on top of the overlay before.

A simple workaround would be to still put an empty transform on the modal body, even without the `.transform` class. I've added `.translate-x-0` in my case, and that fixed it.

**Comment by adamwathan** [comment]
Hey! Yeah good catch, adding `transform` creates a new stacking context which we were relying on for the `z-index` issue here. Few options:

1. Just keep the `transform` class, it's still there and will add a new stacking context.
2. Add the `relative` class to force a new stacking context.
3. Add the `isolate` class to force a new stacking context.

We'll probably update these ourselves to just add `relative` instead of `transform` so that nothing breaks if v3 users remove that class 👍

Have added a note to take care of it so going to close this since the code does work if you don't change it, but if anyone else runs into this hopefully the info here is helpful!

**Comment by reinink** [comment]
Just a heads up that I've added `relative` to all the dialog components in Tailwind UI to force a new stacking context instead of relying on `transform` for this, but kept both classes so that it works on both Tailwind CSS v2 and v3. However, if you're using v3, you can safely now remove `transform` (assuming, of course, you've added the `relative` class).
