### ISSUE TITLE
Footers page and maybe others have out of date React styles

### ISSUE THREAD

**Issue by saheljalal** [tailwindlabs/tailwindui-issues#1100]
**What component (if applicable)**
- URL for category:  Footers
- Component name:  4-column with newsletter and localization

**Describe the bug**
The code in the React tab is incorrect. I copied and pasted it into my project and the form fields (input and button) were not correct. After looking at the source code of the page it appears that it uses different Tailwind classes. Please keep these components up to date as we paid for quality and expect better attention to details like that. Thanks.

**To Reproduce**
1. Go to 'https://tailwindui.com/components/marketing/sections/footers'
2. Click on 'React' tab under 4-column with newsletter and localization
3. Compare styles with actual in inspector

**Expected behavior**
The correct styles in all the code snippets

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I think you might have forgotten to install the forms plugin. There is some information about it at the top of the snippets:
``````
/*
  This example requires Tailwind CSS v2.0+ 
  
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
*/
``````

It's hard to debug what your actual issue is without looking at code, but I guess that since you mentioned form fields that you forgot to install and add the `@tailwindcss/forms` plugin.

I copied it locally including the forms plugin and the React code renders fine. If this issue is still applicable to you, please open a new issue with a minimal reproduction repo so that we can debug this better.
