### ISSUE TITLE
Background image not full screen with 404 Pages / With background image

### ISSUE THREAD

**Issue by OrionSeven** [tailwindlabs/tailwindui-issues#1102]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/feedback/404-pages
- Component name: With background image

**Describe the bug**
Using the default component the unsplash image doesn't cover the full page. I made sure h-full was used in the body and html tags. But the image only covers the main div section and leaves a white section below that. Switching to min-h-screen instead of min-h-full corrects this.

**To Reproduce**
Create a new component and copy and paste the 404 "with full background" code (using react). 

**Expected behavior**
Image background covers the full screen

**Screenshots**
Using the default code: min-h-full
<img width="1680" alt="bug_min-h-full" src="https://user-images.githubusercontent.com/188715/147703603-3072dfd7-ad9c-49db-977e-18a457fddd45.png">

Changing min-h-full to min-h-screen
<img width="1679" alt="bug-_min-h-screen" src="https://user-images.githubusercontent.com/188715/147703595-829ba8c0-2ec1-419d-b9de-12c6c8e723a9.png">

**Browser/Device (if applicable)**
 - OS: macOS 12.0.1
 - Browser Chrome (96.0.4664) and Safari (15.1)
 - Version Tailwind 3.0.1

**Comment by bjorntj** [comment]
Nice if this would be fixed, this a product that actually costs money....

**Comment by bradlc** [comment]
Hey! My guess is you have an extra `div` between the body and the component, and that `div` doesn't have `h-full` on it. If you are using Next.js for example, they add a `div` there that you can't really control, so you'll need to add `height: full` to that `div` with some custom CSS.

In a Next.js project you could write some custom CSS like this, for example:

```css
@layer base {
  html {
    height: 100%;
  }
  body {
    height: 100%;
  }
  #__next {
    height: 100%;
  }
}
```

I bet even if you're not using Next that this is the root of the problem. You'll want to just inspect the HTML in dev tools and see if there are any extra elements being added by your framework of choice, and make sure you write some CSS to target those elements and properly drill the `height: 100%` stuff all the way down from the `html` element to the actual component.

Annoying I know 😕 Unfortunately `height: 100vh` behaves really badly on mobile Safari, so this height drilling approach is the only way to build full height layouts in a cross-browser way.

Going to close because I'm almost positive this is the solution for you but if this doesn't help, please open a new issue with a full reproduction (don't worry about non-Tailwind UI customers being able to see the code, all good) and will definitely help you get to the bottom of it.
