### ISSUE TITLE
Color Picker (RadioGroup) not showing all colors when using arbitrary values.

### ISSUE THREAD

**Issue by magiobus** [tailwindlabs/tailwindui-issues#1131]
**What component (if applicable)** Color Picker
- URL for category:  https://tailwindui.com/components/application-ui/forms/radio-groups
- Component name: Color Picker

**Describe the bug**
I think I found a bug on the color picker of tailiwind ui.
I'm iterating tru my colors array and assigning arbitrary values like className="bg-[#50d71e]" and it only shows few of them. 

assign arbitrary values in the array of colors like "bg-[#50d71e]" instead of bg-pink-500

**Expected behavior**
To show all the background colors

Screenshoot
![colorpicker](https://user-images.githubusercontent.com/981372/149922986-39f8feb5-9567-43c1-9ea6-92da00a7f4a4.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I think I've talked to you on Discord as well. I'm pretty sure the issue is that you are constructing your className dynamically. When you are constructing values dynamically at runtime, then Tailwind won't be able to find the correct classNames because those are only available at runtime. More info: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

Make sure that you are using full class names:
```js
// This is fine, because the full class is visible
["bg-[#f00]", "bg-[#f0f]"].map(color => <div className={color}></div>)

// This is NOT fine, because the full class is not visible
["#f00", "#f0f"].map(color => <div className={`bg-[${color}]`}></div>)
```

If this is not the case, could you attach your code or create a minimal reproduction repo that showcases this issue? Otherwise we are looking for an issue in the dark.

**Comment by reinink** [comment]
@magiobus Hey, I'm going to close this issue since we haven't heard anything back, and I think @RobinMalfait's solution is correct here. Let us know if you're still having any issues though — and if so please provide a minimal reproduction repo 👍
