### ISSUE TITLE
Component looks bad

### ISSUE THREAD

**Issue by cipiloosh** [tailwindlabs/tailwindui-issues#1141]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/multi-column
- Component name: [Full-width with narrow sidebar and secondary column on right](https://tailwindui.com/components/application-ui/application-shells/multi-column#component-b639fa188098a2dbfd9f419c6ef9c6f3)

**Describe the bug**
The component looks to not be full-height on my screen. I mention that I follow all steps, including adding classes on html and body. (See picture bellow)

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] mac os
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 98.0.4758.80

**Additional context**
<img width="1440" alt="Screenshot 2022-02-14 at 09 33 28" src="https://user-images.githubusercontent.com/39827508/153828326-ec25893f-e9a9-4492-b5d1-71771b7e6a07.png">

**Comment by adamwathan** [comment]
Hey! My guess is you have an extra `div` between the body and the component, and that `div` doesn't have `h-full` on it. If you are using Next.js for example, they add a `div` there that you can't really control, so you'll need to add `height: full` to that `div` with some custom CSS.

This is what I end up doing in my own Next projects:

```css
@layer base {
  html {
    height: 100%;
  }
  body {
    height: 100%;
  }
  #__next {
    height: 100%;
  }
}
```

I bet even if you're not using Next that this is the root of the problem. You'll want to just inspect the HTML in dev tools and see if there are any extra elements being added by your framework of choice, and make sure you write some CSS to target those elements and properly drill the `height: 100%` stuff all the way down from the `html` element to the actual component.

Annoying I know 😕 I wish `height: 100vh` worked properly in all browsers but it behaves really badly on mobile Safari, so this stupid height drilling approach is the only way to build full height layouts in a cross-browser way.

Going to close because I'm almost positive this is the solution for you but if this doesn't help, please open a new issue with a full reproduction (don't worry about non-Tailwind UI customers being able to see the code, all good) and will definitely help you get to the bottom of it.
