### ISSUE TITLE
`Application UI > Data Display > Description Lists` Vue Code Doesn't Match Preview

### ISSUE THREAD

**Issue by ptrkstr** [tailwindlabs/tailwindui-issues#1149]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/data-display/description-lists
- Component name: Multiple are impacted, for example: `Left-aligned with inline actions`.

**Describe the bug**
Component Vue code isn't matching Preview. For example in `Left-aligned with inline actions.`, there are 3 `div`s missing (see screenshot).

**To Reproduce**
1. Open above URL category
2. Switch to Vue code
3. Copy code to Vue app
4. View page

**Expected behavior**
Page matches preview.

**Screenshots**

![image](https://user-images.githubusercontent.com/11362913/154653332-c3c54a50-4920-42fa-b095-2d1a4cbac019.png)

**Comment by adamwathan** [comment]
To expand on @RobinMalfait's answer, for many of the components in Tailwind UI we add some extra wrapper styles in the preview pane to do things like add a max width, center it, add some surrounding padding, etc. just to present the component nicely. But the snippet that you copy usually has these sorts of context-specific presentational wrapper styles removed, so that the component will fill the full area of your layout wherever you paste it in.

A better example of this that is probably more intuitive is something like this stacked list:

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/4323180/155574495-81ea673b-4456-437c-b005-829c6f30a5aa.png">

It would be weird if this included styles like `mx-auto` or anything to center it, or the big vertical padding above and below the list. Instead you want the list to just fill up the space that you put it in, and you can add your own containing styles that make sense for where you are using it in your project.

Hope that helps explain the intent here! ❤️

**Comment by ptrkstr** [comment]
That all makes sense, thanks so much for responding everyone. I continue to be a very happy user 😇
