### ISSUE TITLE
Home and end keys don't work in the combobox

### ISSUE THREAD

**Issue by chrisdavies** [tailwindlabs/tailwindui-issues#1158]
Comboboxes

https://tailwindui.com/components/application-ui/forms/comboboxes#component-886412bdec54790d0c35bb5a09086c9a

Type in the combobox and hit home to go to the start or end to go to the end. The caret never moves.

Expected:

The caret moves.

- OS Fedora 35
- Browser Brave

Thanks for Tailwind ... it's been absolutely fantastic.

**Comment by adamwathan** [comment]
Hey @chrisdavies! This is intentional — the home/end keys are used for selecting the first/last items in the dropdown list:

https://user-images.githubusercontent.com/4323180/156179854-80437368-f3aa-4817-9627-fe70786882a1.mov

You can see the documentation for the available shortcuts here:

https://headlessui.dev/react/combobox#keyboard-interaction

This is consistent with other combobox implementations we've studied online, including the native [datalist element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) 👍

Hope that helps!
