### ISSUE TITLE
Vue `Contact Sections` > `Centered` missing `border` on some input.

### ISSUE THREAD

**Issue by ptrkstr** [tailwindlabs/tailwindui-issues#1167]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/contact-sections#component-986addbc8678313fba5b0dd59c778e9b
- Component name: Centered

**Describe the bug**
The `border` attribute is missing on some inputs which makes it not match the preview:
- first name
- last name
- company
- email
- phone number

**To Reproduce**
1. Open above URL
2. Switch to Vue
3. Copy and paste
4. Observe missing border

**Expected behavior**
Borders appear.

**Screenshots**
<img width="678" alt="image" src="https://user-images.githubusercontent.com/11362913/158007369-6be8e1d2-19cc-4625-8b7d-d5bc083085f9.png">

**Additional context**
Solution is to add `border` to the inputs.

**Comment by reinink** [comment]
Hey there! So I think the issue here is that you don't have our forms plugin installed. There is a comment at the top of this component that explains this. You'll need to install the `@tailwindcss/forms` package, and then update your `tailwind.config.js` file like this:

  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```

I just gave this component a try and got the same results until I configured the forms plugin. You can see a working version here: https://play.tailwindcss.com/NHsXC3yM56?file=config

Hope that helps! 🙌

**Comment by reinink** [comment]
@ptrkstr All good, happy to help 🤘
