### ISSUE TITLE
Calendar Date Height Problem and Event Font Problem

### ISSUE THREAD

**Issue by eskiesirius** [tailwindlabs/tailwindui-issues#1174]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/data-display/calendars
- Component name: Month view

**Describe the bug**
When there is no event in the current month, the height of date cell shrinks. Also the font size of event name is different from the code

**Comment by reinink** [comment]
@eskiesirius Hey!

So that makes sense — the height of the calendar is determined by the content that's within it, however you can choose to set a minimum height on it for your particular app. We don't do that in the HTML that we ship for this component, because how you implement this might be different depending on the situation and what you're trying to achieve.

For example, maybe you want to set a minimum height of `768px` in one situation, and in another situation you might want the calendar component to always fill all the vertical space available.

Here's an example of how to do each of these:

**Min height of 768px:**
https://play.tailwindcss.com/wwoZnyJrvg
(requires adding `lg:min-h-[768px]` to the root `<div>`)

**Fill all vertical space available:**
https://play.tailwindcss.com/9irvq6ods3
(requires have `h-full` on the `<html>` and `<body>` elements)

I hope that helps with that issue!

As for the "font size of event name is different from the code" issue, I'm not really sure what this means, and I'm not able to reproduce it. Feel free to leave another comment below explaining this further, and I'd be happy to take another look.

**Comment by eskiesirius** [comment]
Sorry.. please ignore the event font problem.. thank you for this!
