### ISSUE TITLE
The big screen

### ISSUE THREAD

**Issue by IgorDePaula** [tailwindlabs/tailwindui-issues#1204]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens
- Component name: Card layout with sidebar

**Describe the bug**
I was develop a new app when I see that the example layout: my monitor have 24", but the layout example is perfect, but not in my monitor, my screen.
The search bar and above not complete the full space.

**To Reproduce**
1- create the layout in any html and see it in 24" screen

**Expected behavior**
Tha is perfect

**Screenshots**
![Captura de tela de 2022-05-04 20-59-47](https://user-images.githubusercontent.com/2833993/166844692-99ce1f45-4bb7-40e4-9737-b52155893089.png)
![Captura de tela de 2022-05-04 21-04-26](https://user-images.githubusercontent.com/2833993/166844749-710013af-648b-4d9e-aeb0-5c110288b585.png)

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] ubuntu 20.04
 - Browser [e.g. chrome, safari] firefox 
 - Version [e.g. 22] 99

**Additional context**

**Comment by reinink** [comment]
Hey!

So this is actually by design — we wanted the search input and account dropdown in the page header to stay centered with the content below.

You are, of course, welcome to modify this for your own project. That's one of the great things about Tailwind UI — all our components can be customized by simply updating the HTML and Tailwind classes 👍

**Comment by IgorDePaula** [comment]
Ok, Thank you
