### ISSUE TITLE
Empty value is not supported in comboboxes

### ISSUE THREAD

**Issue by adamzajdzik** [tailwindlabs/tailwindui-issues#1217]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/comboboxes
- Component name: simplewith check on left, but probably all the others as well

**Describe the bug**
Empty selectedPerson value is not supported and results in "Uncaught TypeError: Cannot read properties of undefined (reading 'name')" error. This makes using empty initial value, and unselecting a value impossible.

**To Reproduce**
1. Create a component using provided code
2. See error

**Expected behavior**
Empty selectedPerson should be OK and result in an empty combobox.

**Comment by adamzajdzik** [comment]
Also, maybe deleting the contents of the input should deselect any selected value?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

The issue is that the `displayValue` will be called with whatever value you provided. If you start with an `undefined` value then you are trying to do `displayValue={person => undefined.name}`, hence the error you are getting. You can handle that by providing `displayValue={person => person?.name}` hence the `?` to handle the undefined case.

For your second question, this is possible if you use the `nullable` prop, more information can be found here:
- https://headlessui.dev/react/combobox#allowing-empty-values
- https://headlessui.dev/vue/combobox#allowing-empty-values

Hope this helps!

**Comment by adamzajdzik** [comment]
Robin, thank for the tip about `nullable`.

Regarding empty/undefinde person - this is exactly how I fixed it on my side. What I was trying to suggest is the code you provide should already include the `?` in the `displayValue={person => person?.name}` part.
