### ISSUE TITLE
Link active state doesn't work properly for mobile sidebar

### ISSUE THREAD

**Issue by ravibpatel** [tailwindlabs/tailwindui-issues#1218]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: [Brand sidebar with light header](https://tailwindui.com/components/application-ui/application-shells/sidebar#component-17f40014d95a5c5bb5628b9d69558a69) and probably all components with mobile sidebar

**Describe the bug**
Link active state don't change until you close the mobile Sidebar. It works fine for desktop sidebar. I'm using it on SPA developed using Inertia.

**To Reproduce**
1. Pull repo from [here](https://github.com/ravibpatel/tailwind-ui-issue).
1. Run "composer install"
2. Run "php artisan key:generate"
3. Run "php artisan serve"
4. Go to 127.0.0.1:8000 and see the issue in action by using developer tools.

As you can see from the [template](https://github.com/ravibpatel/tailwind-ui-issue/blob/master/resources/js/Layouts/AppLayout.vue), I only did a slight change to it to demonstrate the issue.

**Expected behavior**
Link should properly show active state whenever you click on them.

**Screenshots**
https://www.youtube.com/shorts/yZkQpy3yAzA

**Browser/Device (if applicable)**
 - OS: Windows 11, Android
 - Browser: Firefox, Chrome
 - Version: Latest

**Comment by adamwathan** [comment]
Hey! The problem in your app is that `route().current(item.route)` isn't ever updating to `true` when clicking links in the sidebar. I don't know enough about all of the tools involved here but it seems like in general, Vue isn't re-rendering when clicking the link because it doesn't think any of the dependencies in the component have changed.

Unfortunately this one is out of the scope of what we are able to offer support for — it seems the real underlying thing to figure out out here is "how do I get Vue to treat calls to Ziggy as reactive dependencies so it re-renders if the result of `route().current(...)` changes".

I would try the [Tailwind UI Discord](https://tailwindui.com/discord) or [Inertia Discord](https://discord.com/invite/inertiajs), you might be able to find someone who has a similar setup and can share the correct solution.

Sorry can't be more help here 🙁

**Comment by adamwathan** [comment]
Talked to @reinink, he said this is where you need to look:

https://inertiajs.com/links#active-states

It's sort of annoying to get it playing nicely with Ziggy but this is a working proof-of-concept:

```html
<Link v-for="item in navigation" :key="item.name" :href="route(item.route)" :class="[$page.url === (route(item.route, [], false) || '/') ? 'bg-indigo-800 text-white' : 'text-indigo-100 hover:bg-indigo-600', 'group flex items-center px-2 py-2 text-base font-medium rounded-md']">
    <component :is="item.icon" class="mr-4 flex-shrink-0 h-6 w-6 text-indigo-300" aria-hidden="true" />
    {{ item.name }}
</Link>
```

You probably want to extract that gross logic into some function you can reuse and call like `routeActive(item.route)` 👍

**Comment by ravibpatel** [comment]
@adamwathan @reinink Thanks for the solution. It worked great. I really appreciate providing the fix, even if it wasn't related to Tailwind UI.
