### ISSUE TITLE
TailwindUI Modals not closable in Vue

### ISSUE THREAD

**Issue by LachlanZHogan** [tailwindlabs/tailwindui-issues#1223]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Modal (Vue)

**Describe the bug**
When attempting to close the modal, an error is produced that prevents the dialog closing as well as causing the modal to become unresponsive.

**To Reproduce**
 - Copy Vue code for 'Centered with single action' modal
 - Paste into new component and add component onto any page
 - The component opens on page load, press the button in the modal or click outside the modal

**Expected behavior**
The modal closes without issue

**Actual behaviour**
The modal closes briefly, and then reopens with an error:
```
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <Portal> 
  at <ForcePortalRoot force=true > 
  at <Dialog as="div" class="relative z-10" onClose=fn  ... > 
  at <Anonymous onBeforeEnter=fn<onBeforeEnter> onAfterEnter=fn<onAfterEnter> onBeforeLeave=fn<onBeforeLeave>  ... > 
  at <Anonymous as="template" show=true > 
  at <Modal> 
  at <App key=1 > 
  at <NuxtRoot> runtime-core.esm-bundler.js:38:16
Hydration completed but contains mismatches. runtime-core.esm-bundler.js:4571:20
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Anonymous as="template" show=false > 
  at <Modal> 
  at <App key=1 > 
  at <NuxtRoot> runtime-core.esm-bundler.js:38:16
Uncaught (in promise) TypeError: child is null
    NuxtJS 19
runtime-dom.esm-bundler.js:13:23
```

**Browser/Device (if applicable)**
 - MacOS Bug Sur
 - Firefox and Chrome
 - Nuxt3
```
"dependencies": {
  "@headlessui/vue": "^0.0.0-insiders.f2a813e",
  "@heroicons/vue": "^1.0.6",
  "tailwindcss": "^3.0.24"
}
 ```

**Additional context**
Tried both LTS and Insiders version of HeadlessUI

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The problem is the SSR environment, in the example we default to `const open = ref(true)` but in a real-world application you probably don't want this behaviour.
Currently when you close the Dialog it actually properly closes, the issue is that when it is closed you can still see it because that's the static html that came from the server.

There are a few solutions to this problem that you can apply right now:
- Use `const open = ref(false)` to start with instead
- Use a `client-only` wrapper (https://www.npmjs.com/package/vue-client-only) to ensure it only gets rendered in the browser and not on the server

I'm going to make the second the default where the Dialog only renders on the client and will keep this issue open until a fix is ready. Once we figure out a good story for SSR'd Dialogs we can implement that one but for now we'll keep it client only.

To give you some context, one of the biggest issues with SSR a Dialog is that a Dialog on the client is rendered in a portal using teleport, we teleport it to the `document.body` even if you used the `<Dialog />` somewhere inside your normal app tree.

If you SSR the Dialog, then there is no `document.body` yet (or at least not from Headless UI's perspective). Rendering it inline in the current spot without a portal can lead to incorrect result, for example the one you are seeing right now, but also styles could be different and you might even have stacking (z-index) kind of problems.

Once my PR is ready with a client-only fix, then bumping to the `insiders` build should fix your problem without you doing anything special. Hope this helps!

**Comment by delirium15** [comment]
Also have the same errors. I'm using Nuxt3 and got these errors when using Tailwind components, that are using portals.
I tried to used 3 components, all of them were used each on own single page, just used whole code examples of first available free components:
1. https://tailwindui.com/components/ecommerce/components/product-quickviews
2. https://tailwindui.com/components/ecommerce/components/shopping-carts
3. https://tailwindui.com/components/application-ui/overlays/modals
Interesting thing, that if coming to page with one of these components from another page, error doesn't occures, but when refreshes any of these pages, all of them reproduce the same error.
