### ISSUE TITLE
CTA - Split Image version

### ISSUE THREAD

**Issue by chrisvidal** [tailwindlabs/tailwindui-issues#1227]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/marketing/sections/cta-sections
- Component name: Split with image

**Describe the bug**
When I copy the HTML code as it is in my project for testing, the image does not appear rounded as it is on the preview.

**To Reproduce**
using `"tailwindcss": "^3.0.23",`

**Expected behavior**
Image to be rounded

**Screenshots**
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/2263496/173983335-8abef17c-5f7d-4828-9362-098234c6ed62.png">

**Browser/Device (if applicable)**
 - OS:  Mac OS
 - Browser: chrome
 - Version latest

**Comment by adamwathan** [comment]
Hey! Yeah so that component actually doesn't have rounded corners, it's just that our iframe for previewing the components in Tailwind UI _does_ have rounded corners, so everything looks round in this context:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/4323180/174114431-b16f59bb-74c5-4c1e-9e41-ba18861ab3e9.png">

You can `rounded-2xl overflow-hidden` (or a different radius value if you prefer) to the wrapper element to add the rounded corners 👍

https://play.tailwindcss.com/cdPlfk0sWN

Hope that helps!
