### ISSUE TITLE
Components page is broken

### ISSUE THREAD

**Issue by vgladimir** [tailwindlabs/tailwindui-issues#1255]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components
- Component name: Components page

**Describe the bug**
![image](https://user-images.githubusercontent.com/19341468/177284767-c157fbfe-a1a5-4f55-8d49-8b49fe9a3bf4.png)

On safari all components images are broken.

**To Reproduce**
1. Open safari
2. Open components page

**Browser/Device (if applicable)**
 - OS: macOS Big Sur
 - Browser Safari
 - Version 14.1.2

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

- Can you refresh and verify that this is still happening?
- Do you have any browser extensions running that could cause this? (E.g.: try to open this page in a New Private Window.
- Does it only happen in Safari or also in other browsers?

**Comment by adamwathan** [comment]
Hey! This is because we are using the `aspect-ratio` CSS property for those images, which didn't have Safari support until Safari 15 which ships with Monterey and was released in October 2021.

In Safari 15+ it does work:

![image](https://user-images.githubusercontent.com/4323180/177335327-f82135d9-f76f-4c29-8494-9421cd3285fc.png)

![image](https://user-images.githubusercontent.com/4323180/177335341-10703adc-b3ce-4a48-ae98-6c6d98f1ab7d.png)

Just going to live with this I think rather than use a fallback approach, but I appreciate the heads up! Going to dig into some analytics too and see how many people this impacts.
