### ISSUE TITLE
Any plans for VueJS implementations of the TailwindUI Templates?

### ISSUE THREAD

**Issue by aaronlippold** [tailwindlabs/tailwindui-issues#1256]
TailwindUI has great support for both React and Vue, just wondering if this will extend to the Templates at some point.

**Comment by reinink** [comment]
Hey!

So no immediate plans to provide the site templates in other formats (ie. HTML, Vue, Svelte, etc), but it's something we've chatted about and may do eventually.

We went with React because that's the framework most of our customers use, so it felt like a good place to start.

Hope that makes sense 👍

**Comment by aaronlippold** [comment]
Yes it does, if you guys had to pick a 'next framework' - given that your compoents are HTML, React and VueJS - I would say your templates should follow the same pattern.

**Comment by majortom64** [comment]
@reinink should we expect you to drop support for Vue in the regular component section or is that still safe?

**Comment by reinink** [comment]
@majortom64 Hey we don't have any plans to drop support for Vue in our components.
