### ISSUE TITLE
More breadcrumbs than the example doesn't look good on mobile

### ISSUE THREAD

**Issue by nahall** [tailwindlabs/tailwindui-issues#1269]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/breadcrumbs
- Component name: Tested full-width bar and Simple with chevrons

**Describe the bug**
If you create a breadcrumb list with 5 or 6 breadcrumbs and view it on mobile, it looks bad. Text ends up being almost vertical and it may cause horizontal scrolling.

**To Reproduce**
1. Copy the breadcrumb HTML code
2. Duplicate the li sections several times and add more text to each breadcrumb
3. View on a small screen or mobile
4. The breadcrumbs will look bad.

**Expected behavior**
It should format itself better, probably into multiple rows which would be much more readable.

**Screenshots**
https://play.tailwindcss.com/svvB68ZM2b?size=540x720
another one:
https://play.tailwindcss.com/tgbZgYBQ4X?size=540x720

**Browser/Device (if applicable)**
 - Android
 - Chrome

**Additional context**
Example:
https://play.tailwindcss.com/svvB68ZM2b?size=540x720
another one:
https://play.tailwindcss.com/tgbZgYBQ4X?size=540x720

**Comment by reinink** [comment]
Hey @nahall, thanks for reaching out about this.

So the way these breadcrumb components work is actually by design. The design is intended to accommodate two, maybe three items max.

If I were to implement this in an app of my own, I'd probably either drop the extra items to the left on mobile (something [like this](https://play.tailwindcss.com/9ef54FEU3W?size=704x720)), or even switch to something entirely different on mobile, like a back button (you can see an example of that in our [stacked card layout](https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-80034b9052ca551c25f7d731b7b3c6dd) component).

I hope that helps 👍
