### ISSUE TITLE
Padding not applied in Safari 14

### ISSUE THREAD

**Issue by danielfriis** [tailwindlabs/tailwindui-issues#1283]
**What component (if applicable)**
- URL for category: https://salient.tailwindui.com/
- Component name: Salient Template

**Describe the bug**
Seems that padding is not applied in multiple instances for Safari 14. Example is Salient where I discovered the bug.

**To Reproduce**
1. Go to ['Salient Live Preview'](https://salient.tailwindui.com/)
2. See error

**Screenshots**
<img width="1440" alt="Skærmbillede 2022-07-30 kl  19 58 10" src="https://user-images.githubusercontent.com/2437484/181935835-6d243afa-a960-48a2-a6a3-6ccdf553f2cb.png">

**Browser/Device (if applicable)**
 - OS: macOS Big Sur, 11.2.3
 - Browser: Safari
 - Version: 14

**Comment by adamwathan** [comment]
Hey! This is because we are using the `gap` property with flexbox which didn't get support in Safari until Safari 14.1:

https://caniuse.com/flexbox-gap

If you want to use this template in a project that needs to support older browsers you'll want to tweak the code to only use features that the browsers you are targeting support 👍

In this case you'd probably want to play with the `space-x-*` utilities, but it can get tricky when you need things to support wrapping, which is why we reach for `gap` which just works so nicely with no complex workarounds.

Hope that helps! We don't have any plans to support old browsers out of the box.
