### ISSUE TITLE
Incomplete styles for forms: lacking disabled state of controls

### ISSUE THREAD

**Issue by rart** [tailwindlabs/tailwindui-issues#1298]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: All forms

**Describe the bug**
Form controls (inputs, buttons, selects, etc) are lacking styles for disabled state.

**To Reproduce**
1. Set a control (e.g. submit button) to disabled
4. See control looks as if enabled (e.g. button still has hovers and no distinction to enabled states)

**Expected behavior**
Every control implements disabled state. 

I believe this to be a bug and not just a suggestion because "ready-to-drop" components and templates, should implement disabled states as this isn't a customisation but rather a basic aspect of forms usage.

For extra credit, ready only, submitting and loading states would be useful too.

**Comment by reinink** [comment]
Hey! Thanks for this feedback.

I agree, it would be great to have an example of a disabled input on Tailwind UI. To be honest, when we first created these form components Tailwind CSS didn't even have support for the `disabled` variant 😅

I've gone ahead and added a new disabled input component to Tailwind UI in the input groups category. You can find that here: https://tailwindui.com/components/application-ui/forms/input-groups#component-7cbbedb5c241c41093f698b30e1eff40

I don't think we want to add it to all inputs in Tailwind UI though, since it's not always required and I don't want to unnecessarily pollute those components with extra classes when it's not needed.

Hope that helps! 💪

**Comment by rart** [comment]
Thanks for adding the disabled input, @reinink. That's helpful.

The disabled button is probably one of the most important disabled states to have, maybe even the most. One of the reasons being: in a form, the submit button might be disabled whilst all the required fields aren't filled up, or some other condition — like submitting or validating — but the inputs are the primary objective of a form so, though surely there are cases where the inputs are disabled, I'd argue the button is more likely to require disabling.

I don't agree with not having all inputs with their disabled state, though; I think it makes that specific part of the product incomplete. Maybe the bare minimum is input and button at least? If it was up to me, I'd consider reopening and having further coverage.
