### ISSUE TITLE
Heroicon import not up to date.

### ISSUE THREAD

**Issue by 618457** [tailwindlabs/tailwindui-issues#1309]
Heroicon was updated to v2 so when new project init and run add @Heroicon/vue will setup V2.
With Heroicon in the tailwinds templates / components are import  from "@heroicons/vue/outline"  or so.
when running the project the console will throw out error"`You\'re trying to import \`@heroicons/vue/outline/${property}\` from Heroicons v1 but have installed Heroicons v2. Install \`@heroicons/vue@v1\` to resolve this error.`

So we have to choose keep Heroicon V1 to use the code in tailwinds ui or rewrite import and all the icon in them.

Sugget to upgrade with the latest Heroicon if possible. Thanks.

**Comment by reinink** [comment]
Hey!

So you're right, we recently updated Heroicons to v2, and that is the default now when you install the Heroicons package. We've also updated all of Tailwind UI to use these new icons. If you view the component snippets on the Tailwind UI website you can see that the imports have been updated there to use Heroicons v2.

Of course, any of your existing code that uses Tailwind UI prior to this change will still depend on Heroicons v1. So, like you said, you can choose to simply continue using Heroicons v1, or upgrade to v2.

I admit, this is a bit of a pain for an existing project that uses Heroicons v1, because as soon as you add new components you'll bump into a conflict, since those new components will depend on v2.

You have two options here:

1. **Keep your project on Heroicons v1.**
Don't use Heroicons v2 for these new components and instead use the corresponding Heroicons v1 version. Just be aware that some of the icon names have changed a little. You can find a table listing the old an new names in the release notes for v2 here: https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0
2. **Upgrade your project to Heroicons v2.**
Depending on the size of your app this might be a little more work, but it will make working with Tailwind UI easier moving forward as everything will be on the same version of Heroicons. You can find an upgrade guide in the release notes for v2 here: https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0

Again, I totally get how this is a bit of a pain — sorry about that!

Hope this helps 👍
