### ISSUE TITLE
Notification Component Bug

### ISSUE THREAD

**Issue by eskiesirius** [tailwindlabs/tailwindui-issues#1311]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/notifications#component-a065edf8f08a35f06943b2e266ca9af1
- Component name: Notification Simple

**Describe the bug**
Can't render component

**To Reproduce**
Copy the Code

**Expected behavior**
It should display the component without error

**Screenshots**
![Screenshot_111](https://user-images.githubusercontent.com/7463362/188117182-72e03654-fad5-409f-a474-61f5157f446d.png)

**Browser/Device (if applicable)**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 104.0.5112.102

**Additional context**
None

**Comment by adamwathan** [comment]
Hey! This is because we've updated all of the Tailwind UI examples to work with [Heroicons v2.0](https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0), and the imports have changed:

```diff
# Using React

- import { ... } from '@heroicons/react/solid'
+ import { ... } from '@heroicons/react/20/solid'

- import { ... } from '@heroicons/react/outline'
+ import { ... } from '@heroicons/react/24/outline'

# Using Vue

- import { ... } from '@heroicons/vue/solid'
+ import { ... } from '@heroicons/vue/20/solid'

- import { ... } from '@heroicons/vue/outline'
+ import { ... } from '@heroicons/vue/24/outline'
```

So you'll either want to change the imports back to the v1 paths if staying on Heroicons v1, or upgrade your project to use Heroicons v2 🍻

**Comment by eskiesirius** [comment]
yeah.. i checked my package.. I was using v1... thank you!
