### ISSUE TITLE
Converting Spotlight template page to Typescript breaks layout

### ISSUE THREAD

**Issue by danielvanc** [tailwindlabs/tailwindui-issues#1326]
**What component (if applicable)**
- Spotlight Template

**Describe the bug**
Using TypeScript in NextJS and using spotlight theme, moving from `.jsx` to `.tsx` breaks page layout/design. For example, the row of images on the homepage do not appear.

**To Reproduce**
1. Convert the nextjs project with spotlight theme to typescript
2. Rename a page from having a `.jsx` to `.tsx`
3. Load page in browser
4. See the layout break

**Expected behavior**
Page to appear as expected when not using typescript

**Screenshots**

**Browser/Device (if applicable)**
 - OS: MacOS Monterey
 - Browser: Brave
 - Version 1.43.93

**Comment by adamwathan** [comment]
Hey! This question is a better fit for our [Discord server](https://tailwindui.com/discord) since we unfortunately don't have the resources to offer technical help when customizing templates and want to keep issues here to strictly bugs 👍

If I had to guess though, perhaps your `content` configuration is wrong. By default it only looks for `js/jsx`, so you'll need to update your `tailwind.config.js` file to make sure it is scanning TypeScript files as well 👍
