### ISSUE TITLE
Syntax Template - On this page navigation not highlighting correct section

### ISSUE THREAD

**Issue by adamrichardson14** [tailwindlabs/tailwindui-issues#1327]
**What component (if applicable)**
- URL for category: https://syntax.tailwindui.com/#join-the-community
- Component name: Syntax Template

**Describe the bug**
There is an issue with the cyan "current article" highlighting on the right hand side "on this page" section when you select the last heading title.

**To Reproduce**
1. Go to https://syntax.tailwindui.com/#join-the-community
2. You will see that Submit an issue is selected

**To Reproduce **
1. Go to https://syntax.tailwindui.com/docs/the-butterfly-effect#reprehenderit-magni
2. You will see that only the main heading is selected, and no subheadings

**Expected behavior**
Current section should be highlighted

**Screenshots**

**Browser/Device (if applicable)**
 - OS: Windows
 - Browser Chrome
 - Version 105.0.5195.127

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is actually expected behaviour, but admittedly it looks a bit odd in this particular case. The heuristic that we apply is "As long as a section is visible, that section is the active one". In this case the "Adding middleware" is still visible and therefore still active. 
<img width="1846" alt="image" src="https://user-images.githubusercontent.com/1834413/191471519-08833cdf-7f40-451c-88e6-2b7d93da7ab7.png">

The "active" item in the sidebar is entirely controlled by the scroll position and nothing more.

Now, the alternative would be to highlight all the "visible" sections, but then your sidebar would look even more confusing:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/1834413/191471992-2b0fcd33-a638-4da7-85b4-87e0c1d67217.png">


Since this is scroll position driven and therefore also content driven, this will depend on the content you put in. If you have long sections you won't notice any issues.

One alternative solution you could apply as well is by providing an additional `<div class="h-screen"></div>`. This would allow you to scroll _a lot_ below the actual content. (Of course you can play with that value). That would look like this in practice 
<img width="1846" alt="image" src="https://user-images.githubusercontent.com/1834413/191472466-69774868-3e69-4268-bd33-f2c43f0128e3.png">


This is also a technique that a lot of editors use:
<img width="1846" alt="image" src="https://user-images.githubusercontent.com/1834413/191472719-bf546826-bdeb-43a9-8a86-0533af2bfd3a.png">


So while we probably won't change this behaviour right now, I hope the information helps you to understand why things behave the way they do.

**Comment by adamrichardson14** [comment]
Hi Robin, thanks for the explanation! Makes complete sense
