### ISSUE TITLE
Toggles not toggling

### ISSUE THREAD

**Issue by dudo** [tailwindlabs/tailwindui-issues#1332]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/pricing
- Component name: [Four tiers with toggle](https://tailwindui.com/components/marketing/sections/pricing#component-d18ab876bc346ed08c7499a16281777c)

**Describe the bug**

<img width="366" alt="image" src="https://user-images.githubusercontent.com/2963800/191886755-71ce689f-bab6-4686-896a-c7b6bdd265b8.png">

Toggle doesn't toggle. Same thing for [Three tiers on brand and feature comparison](https://tailwindui.com/components/marketing/sections/pricing#component-49165a9c77f14e07c2b4e18468dbfc6f)

**Browser/Device (if applicable)**
 - OS: OSX 12.5.1
 - Browser: Chrome latest

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is by design, these components are visual UIs that you can use to implement your own system around it. We provide you with the various states like the active button and non active button but we don't implement every single interaction. We also don't know what you want to change, do you want to just change the price, change the features, add a discount code? Similar to how the "buy" button doesn't actually buy you anything.

For more complete examples where we have more functionality, you can take a look at the templates.
For example, the `Pocket` template has an example implementation for pricing that toggles between monthly/annual.
- Preview: https://pocket.tailwindui.com/#pricing
- Template page: https://tailwindui.com/templates/pocket

Hope this helps!

**Comment by dudo** [comment]
That makes sense. Thanks for the heads up. And thanks the amazing tooling!
