### ISSUE TITLE
Syntax Template - Icon Quality is not as good in light mode

### ISSUE THREAD

**Issue by StevenBullen** [tailwindlabs/tailwindui-issues#1333]
**What component (if applicable)**

Syntax Template (https://syntax.tailwindui.com)

**Describe the bug**

Icons look weird in Light Mode

**Screenshots**

![Orange Icon - Dark Mode](https://user-images.githubusercontent.com/239862/191952441-6a768b17-e2ab-44e9-bff1-53babd29ada2.png)
![Orange Icon - LIght Mode](https://user-images.githubusercontent.com/239862/191952439-66e04cc2-20a0-4b86-b15e-912d6beef39d.png)

![Blue Icon - Dark Mode](https://user-images.githubusercontent.com/239862/191952494-6d524d4b-2a60-4a75-ab8c-c6893359060b.png)
![Blue Icon - Light Mode](https://user-images.githubusercontent.com/239862/191952491-312053f6-da2b-4410-b1e3-b2ad355bc019.png)

![Icons - Dark Mode](https://user-images.githubusercontent.com/239862/191952546-1674f010-0c79-4d14-a639-388b3bffdebf.png)
![Icons - Light Mode](https://user-images.githubusercontent.com/239862/191952536-cd96fd34-bab7-4dcd-909a-e54896820d49.png)

**Browser/Device (if applicable)**

* Safari
* Chrome
 

Sorry if reported to wrong place.

**Comment by reinink** [comment]
@StevenBullen Hey! 👋

When you say that the light mode icons "look weird", I assume you are referring to how the circle in the background is offset from the icon itself. This is actually by design — we like this effect! — although I can totally appreciate that it's a unique style that may not be for everyone.

If it's not for you, I'd suggest just replacing with an icon set that's more to your taste 👍

**Comment by StevenBullen** [comment]
Thanks for getting back to me.
It's not a problem for me as I have already removed the background circles from light mode and I had no issues with the icons themselves.

A few users who view my docs mentioned it, and thought it was broken (not sitting correctly). Not sure I agree on the design, but as you say maybe not right for everyone.
