### ISSUE TITLE
Ecommerce Product quick view react code doesn't work 

### ISSUE THREAD

**Issue by mpoonuru** [tailwindlabs/tailwindui-issues#1350]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/ecommerce/components/product-quickviews
- Component name:  Product Quick View

**Describe the bug**
I copied the product quick view component code for my nextjs project. I created a new page to test the product quick view component it doesn't work anymore. I get blank page. 

**To Reproduce**

**Expected behavior**
I copied the product quick view component code for my nextjs project. I created a new page to test the product quick view component it doesn't work anymore. I get blank page. 

**Screenshots**

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Safari, Chrome, Brave
 - Version [e.g. 22] Version 16.0 

**Additional context**

**Comment by reinink** [comment]
Hey, happy to try and help here, but I need a little more information.

Are you getting any type of console errors? If yes, can you share those errors?

Also, what version of Tailwind CSS and Headless UI are you on?

Thanks! 🙏

**Comment by reinink** [comment]
Hey @mpoonuru,

So it sounds like you've got this figured out, which is great, because I'm not *totally* following what you're saying 😅

I think one of the reasons you didn't see the product quickview modal in your app is maybe because by default we set the state of the modal to closed, in this line:

```js
const [open, setOpen] = useState(false)
```

You'll need to implement toggle behavior to set the `open` state to `true` to cause the modal to open.

Also, you mention wanting the main element code as well. I suspect you're asking for the surrounding code around/below the modal here. If that's the case, we've tried hard to only include the necessary code for each particular component, and not extra contextual code, as it makes it harder to insert the component into your own project.

I hope that helps! 👍👍
