### ISSUE TITLE
Template "Salient" has bug in small resolution

### ISSUE THREAD

**Issue by dirkil** [tailwindlabs/tailwindui-issues#1355]
**What component (if applicable)**
- URL for category: https://salient.tailwindui.com/
- Component name: Salient

**Describe the bug**
Tabs in template get cut off when browser is reduced in width.

**To Reproduce**
1. Open the Salient live preview
2. Hit F12 to open the developer tools in Chrome
3. Switch to mobile view and reduce width to approximately 530 pixels
4. Scroll down to the tab view underneath "Everything you need to run your books". There you can see that the tabs get cut off to the right when you reduce the width of the browser.

**Expected behavior**
I would expect the tabs to wrap around to the next line so that you can always see all tabs.

**Screenshots**
![image](https://user-images.githubusercontent.com/12883649/199244154-ad3bd793-c767-4c60-ad08-6c6133cc3f35.png)

**Comment by adamwathan** [comment]
Hey! This is actually by design, which is why the tab list is independently scrollable 👍

This is a pretty common pattern on mobile websites that works well IMO when interacting with a page with touch — here's an example of a similar pattern on the Stripe website:

https://user-images.githubusercontent.com/4323180/199247108-c572236d-0f37-407e-979f-f4365b0ab93e.mp4

Of course if you want them to wrap you can jump in and tweak the code however you like! Hope that's helpful either way.
