### ISSUE TITLE
switch to dark mode 

### ISSUE THREAD

**Issue by subralog** [tailwindlabs/tailwindui-issues#1357]
in the tailwindui.com homepage, we saw the dark and light mode switching advertised. but we are unable to find about the dark mode switch in the documentations. how do we switch to dark mode as shown in the homepage?

![Screenshot 2022-11-03 at 9 16 58 AM](https://user-images.githubusercontent.com/73687719/199644087-7b81139f-81eb-439f-bbbd-adc3d51615f2.png)

**Comment by reinink** [comment]
Hey! 👋

That dark mode switcher is from our [Syntax template](https://tailwindui.com/templates/syntax). You can find a demo of it here: https://syntax.tailwindui.com/

Right now the Tailwind UI website itself doesn't have a dark mode option, nor do our components. However, some of our individual templates, like the Syntax template and Spotlight template do have dark mode support.

We may add additional dark mode support in the future — you're welcome to upvote one of the existing ideas for this in our discussions section, here: https://github.com/tailwindlabs/tailwindui-issues/discussions?discussions_q=dark+mode

Hope that helps! 🙏

**Comment by vicary** [comment]
@reinink Sorry to bring this up again, but I don't see a discussion tab anywhere. How do I upvote for dark mode components?

**Comment by reinink** [comment]
@vicary Yeah sorry, we decided to get rid of the discussions area because we felt it was setting the wrong expectations — it started to feel like a roadmap and people were getting frustrated that something was posted x months ago or had x +1s on it and hadn't been built.

Definitely still want to hear everyone's ideas but I think just shooting us a tweet is a better way to put it on our radar, and if we like the idea then it's something we'll play with when it makes sense to be on the top of our priority list 👍
