### ISSUE TITLE
Styled Tabs examples from Headless UI

### ISSUE THREAD

**Issue by Howard86** [tailwindlabs/tailwindui-issues#1361]
**What component (if applicable)**
- URL for category: https://headlessui.com/react/tabs#styled-examples
- Component name: Tabs

**Describe the bug**

Curious if this is intended to be or should I submit a feature request 

Following the description on [Headless UI](https://headlessui.com/react/tabs#styled-examples) websites, it seems to indicate that we have _predesigned component examples using Headless UI and Tailwind CSS_ for Headless UI `Tabs`

> Styled examples
> 
> If you're interested in predesigned component examples using Headless UI and Tailwind CSS, check out Tailwind UI — a collection of beautifully designed and expertly crafted components built by us.
> 
> It's a great way to support our work on open-source projects like this and makes it possible for us to improve them and keep them well-maintained.
> 

However, when visiting the [component](https://tailwindui.com/components/application-ui/navigation/tabs) pages, all of the examples are using plain html instead

(I'm using React in this case)

**To Reproduce**
1. Go to https://headlessui.com/react/tabs#styled-examples
2. Click on `Tailwind UI` link https://tailwindui.com/
3. Go to `Tabs` section https://tailwindui.com/components/application-ui/navigation/tabs
4. For each example, click `Code` tab 

**Expected behavior**

Some examples will integrate Headless UI Tabs with predesigned TailwindCSS

**Screenshots**

https://ibb.co/ccs3kYY

**Browser/Device (if applicable)**

 N/A

**Additional context**

Thank you for your work and products! 

Tailwind UI is a great way to bootstrap and layout some skeleton codes before applying apps design system
It'd be really helpful to have more integrated examples so we could focus on business logic more.

**Comment by reinink** [comment]
Hey, thanks so much for sharing this feedback!

I agree, it would be great to have some JavaScript-based tab examples in the [tabs category](https://tailwindui.com/components/application-ui/navigation/tabs). When we originally released these tab examples Headless UI actually didn't even exist yet 😅

I do think there are good use-cases for the link-based tabs still. I know in my own apps that I'll often use a tab style navigation where each tab links to a different page, instead of switching content client-side.

Either way, we'll be sure to consider adding some JavaScript-based tab examples to this category in a future update to Tailwind UI. Until then, you can find some examples of these in the ecommerce bundle. Here's two in particular:

- [Product Features  / With tabs](https://tailwindui.com/components/ecommerce/components/product-features#component-1c59e9598a7ee96a39f2a1c1e6b270a7)
- [Product Pages / With tabs and related products](https://tailwindui.com/components/ecommerce/page-examples/product-pages#component-5d28bf260035512bddeb20cab56e052d)

Hope that helps! 💪

**Comment by Howard86** [comment]
thanks for sharing!
I will look into the examples for now

**Comment by sdoxsee** [comment]
@reinink appreciate this being on the team's radar. 

Note that the example links only benefit those with the ecommerce or all-access plan, not those with Application UI (for which tabs are advertised)
