### ISSUE TITLE
Spotlight template horizontal overflow on iOS Safari 16.0

### ISSUE THREAD

**Issue by klittlepage** [tailwindlabs/tailwindui-issues#1365]
**What component (if applicable)**
- Component name: Spotlight template

**Describe the bug**
Horizontal overflow on mobile Safari

**To Reproduce**

This is visible on the [Spotlight preview](https://spotlight.tailwindui.com/)

**Expected behavior**
No horizontal overflow/content should fit within viewport

**Browser/Device (if applicable)**
 - OS: iOS
 - Browser: safari
 - Version 16.0

**Comment by adamwathan** [comment]
Hey! Can you provide some more details? I can't find any horizontal overflow/scrolling issues or anything in my testing.

Are you talking about the images here by any chance?

<img width="588" alt="image" src="https://user-images.githubusercontent.com/4323180/201486973-857a1877-4423-479e-a808-be8cc336535f.png">

If so this is intentional, we liked the design that way with the images being cropped and serving as just a visual element in the design vs being actual content per se 👍 If you want them to stack or something though you can make those tweaks for your own site for sure.

**Comment by klittlepage** [comment]
Hey! Thanks for the quick response (and for the fantastic work on Tailwind). Embarrassingly, I went to repo/get a screenshot, and I could not do so on either my local build or the live preview. I restarted my phone (and, by extension, Safari)—that was the only change.

FWIW, the effect I saw earlier wasn't the intentional cropping you screenshotted–it was the loose viewport style of overflow whereby swiping leads to side-scrolling (overflow-x) into an empty background. I'm closing this and chalking it up to a Safari render glitch.
