### ISSUE TITLE
Notification is behind search bar

### ISSUE THREAD

**Issue by soasada** [tailwindlabs/tailwindui-issues#1368]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/notifications
- Component name: Simple

**Describe the bug**
Notification is shown behind search bar when using along with "Light sidebar with light header" Sidebar layout.

**To Reproduce**
I'm using Next.js 13 with typescript, I have a layout where the notification is placed at the end along with the children components that renders the whole page layout, using "Light sidebar with light header".

**Expected behavior**
The notification is above everything.

**Screenshots**

![image](https://user-images.githubusercontent.com/7634531/202306843-7e40fe8f-d18f-402d-963d-608347b47122.png)

**Browser/Device (if applicable)**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox 106.0 (64 bits)

**Comment by reinink** [comment]
Hey! Happy to help out here.

So sometimes when working with different Tailwind UI components you'll need to make small adjustments to make them compatible with each other — just because it's almost impossible for us to anticipate all the different combinations and situations our components can be used in.

In this situation I'd recommend two small changes to the outermost container of the "Simple" notification example. First, add a `z-50` to make it sit on top of the app header. I'd also recommend adjusting the top padding to `p-24` on small screen sizes (and larger) to make it sit below the app header — it just looks a little nicer.

```diff
- className="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6"
+ className="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6 sm:pt-24 z-50"
```

Here's what it looks like when you implement these changes:

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/882133/202451804-1dd9083a-95cc-436c-8c28-7367d5f8f908.png">

I hope that helps! 🤙

**Comment by soasada** [comment]
Spotless! Thanks for your help and also the suggestion :)
