### ISSUE TITLE
Template: Protocol - scroll restoration

### ISSUE THREAD

**Issue by richardbann** [tailwindlabs/tailwindui-issues#1387]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates
- Component name: Protocol

**Describe the bug**
When I scroll down on a page (say to the very end) and navigate to an other page from the menu, the new page appears scrolled.

**To Reproduce**
As described above.

**Expected behavior**
In this case the top of the page should be shown.

**Screenshots**

**Browser/Device (if applicable)**
 - OS: iOS
 - Browser:safari
 - Version ?

**Additional context**
I am not sure if this is a bug, I keep seeing this behaviour on various sites. Anyways it is bad user experience in my opinion.

**Comment by reinink** [comment]
@richardbann Hey! Thanks for sharing this. I just tried to reproduce this in Safari and was unable to. Would you be able to take a screen recording of this so I can see exactly how you're replicating this? 🙏

**Comment by richardbann** [comment]
https://user-images.githubusercontent.com/2426725/207974207-880fd48b-40a1-49bd-a690-63d04d41ff51.mp4

Also happens in firefox (iOS)
Thanks for having a look at it.

**Comment by reinink** [comment]
@richardbann Hey thanks, we're now seeing this issue as well and we're working to figure out a solution. Bit of a tricky problem 😅

**Comment by reinink** [comment]
Hey, thanks for your patience on this! We've figured out what was wrong here and have solved it upstream in Headless UI. You can fix this in your own Protocol site by making the following changes:

First, update your project to use the latest version of Headless UI:

```diff
- "@headlessui/react": "^1.7.8",
+ "@headlessui/react": "^1.7.11",
```

You can just run `npm install @headlessui/react@latest` to do this.

Next, make the following changes to your `/src/pages/_app.jsx` file:

```diff
+ Router.events.on('routeChangeStart', onRouteChange)
  Router.events.on('hashChangeStart', onRouteChange)
- Router.events.on('routeChangeComplete', onRouteChange)
- Router.events.on('routeChangeError', onRouteChange)
```

That's it!

A little background on what was wrong here:

The Headless UI `<Dialog>` component, used in this template for the mobile navigation, has to do some interesting things to prevent body scrolling on iOS — so that you can't scroll the site behind the dialog but instead only the dialog itself (if needed).

To accomplish this we disable scrolling on the body using `overflow: hidden` and then set the top margin on the page to match your current scroll position. Then, when you close the dialog we remove these styles and restore the scroll position back to where it previously was on the page.

The problem in this template is that the dialog has a close transition, so when you navigated to a new page and Next.js reset the scroll position back to the top of the page, the dialog scroll restoration logic  ran *after* the page navigation occurred, causing you to end up scrolled down the new page you just visited.

To solve this we've updated the dialog component in Headless UI to have a "pre-close" stage where we restore the scroll position back to where it previously was *before* the dialog close transition starts. Meaning the scroll locking styles are removed immediately when the dialog starts to close, instead of when the close transition completes.

For this fix to be effective in this template, we also needed to update it to use `routeChangeStart` instead of `routeChangeComplete`, otherwise the scroll restoration would still happen too late as the dialog closing wouldn't even start until the navigation was finished.

This new approach works great — although it's worth noting that the mobile navigation dialog now starts closing immediately when you click a link in the mobile navigation, and not after the page navigation occurred (as it did previously).

**Comment by osamaqarem** [comment]
hate to be the bringer of bad news 😓, but this issue has resurfaced since the template was updated to App Router - is there an equivalent workaround we could make there?

https://github.com/user-attachments/assets/88825554-6a1f-4f16-9e77-cb3b8963184a

**Comment by reinink** [comment]
@osamaqarem Hey thanks so much for bringing this to our attention. I believe this regression happened when we migrated from the pages router to the app router.

I've just pushed out an update to this template which fixes these issues. I'd recommend downloading the template again from the Tailwind Plus website, as there were quite a few changes to implement this fix, including an update to Headless UI. If you have an existing project you could probably just replace the files in the `/src/components` directory, as well as the `package.json` and `package-lock.json` files.

Thanks again!
