### ISSUE TITLE
Notification not compatible with Modal

### ISSUE THREAD

**Issue by bodokaiser** [tailwindlabs/tailwindui-issues#1388]
**What component (if applicable)**
- URL for category: [Overlays](https://tailwindui.com/components/application-ui/overlays)
- Component name: [Notifications](https://tailwindui.com/components/application-ui/overlays/notifications), [Modals](https://tailwindui.com/components/application-ui/overlays/modals)

**Describe the bug**

I have a form inside a Modal and would like t confirm the submission of the form with a global Notification. Unfortunately, I cannot place the Notification over the Modal's backdrop.

**To Reproduce**

Save and download the [index.html](https://gist.github.com/bodokaiser/0a209b71dd0be1b002e49f9b605839ce) and open it in your browser.

**Screenshots**

<img width="774" alt="image" src="https://user-images.githubusercontent.com/1780466/208294953-29635db6-b671-4ea1-a925-a851925f316c.png">

**Comment by reinink** [comment]
Hey! Happy to help out here.

So sometimes when working with different Tailwind UI components you'll need to make small adjustments to make them compatible with each other — just because it's almost impossible for us to anticipate all the different combinations and situations our components can be used in.

In this situation I'd recommend adding a `z-50` to the notification to make it appear on top of the dialog.

```diff
- <div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6">
+ <div aria-live="assertive" class="pointer-events-none fixed z-50 inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6">
```

Here's what it looks like with that change:

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/882133/208436914-76e3c3b7-a313-4071-9707-70a8f73f6a21.png">

I hope that helps! 🤙
