### ISSUE TITLE
Template: Protocol - no docs on how to add content to the Algolia index

### ISSUE THREAD

**Issue by bogdansoare** [tailwindlabs/tailwindui-issues#1395]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates
- Component name: Protocol

**Describe the bug**
There are no docs or script on how to add and structure content to the Algolia index

Multiple people are facing this issue on discord:
<img width="828" alt="Screenshot 2022-12-30 at 14 22 34" src="https://user-images.githubusercontent.com/2750170/210069777-8f50d719-4024-4a4e-be54-c42817b17083.png">

**Comment by reinink** [comment]
Hey! You're right, we could definitely do a better job of explaining how to setup search in this template — I'm going to make sure a note gets added to the README about this.

So for both of our documentation templates (Syntax and Protocol) search is implemented using [Algolia DocSearch](https://docsearch.algolia.com). This works great as it's free for open-source projects and really easy to setup. Basically you just sign up for their service and they automatically index your live website — meaning you don't need to do anything yourself to get the Algolia index setup or updated when your content changes. Once your DocSearch account is ready, all you need to do is update the following environment variables in our template with the values provided by Algolia:

```
NEXT_PUBLIC_DOCSEARCH_APP_ID=
NEXT_PUBLIC_DOCSEARCH_API_KEY=
NEXT_PUBLIC_DOCSEARCH_INDEX_NAME=
```

This felt like a great default for our templates since it provides a really smooth search experience for anyone creating open-source documentation. However, if you're working on a commercial project or are unable to use DocSearch for some other reason you'll need to build a custom Algolia integration to get your search index updated, as we don't include anything like that in our templates right now, largely because how you build this really depends on your particular project.

That said, if it helps, reading through the [DocSearch documentation](https://docsearch.algolia.com/docs/DocSearch-program#how-much-does-it-cost) they do mention that it's possible to run your own DocSearch instance alongside a paid Algolia account. I realize that's a big ask, but depending on your situation might still be a good option.

Hope that helps!

**Comment by bomshteyn** [comment]
This is really unfortunate and unexpected. I used to use the `@nuxt/content-theme-docs` on my previous API doc sites, but decided to try the Protocol template for this project. Nothing in the readme file mentioned that to get it to work as ion example it needs to be an open source project.

In the `@nuxt/content-theme-docs` there was to search components regular or algolia, I think it would be reasonable to expect something similar. Maybe you can see how they implemented it and incorporate something similar into the TailwindUI doc templates.

**Comment by reinink** [comment]
@bogdansoare Hey really sorry this caught you off guard, I agree, this is something that we could definitely have communicated better.

I remember when we first made our [Syntax](https://tailwindui.com/templates/syntax) template we debated whether we should even include any type of search feature at all, as our focus with these templates is really on the design and UI end of things, and search is a whole separate can of worms that can be solved in a variety of different ways depending on the business needs and project. We decided in the end to include DocSearch integration since this felt better than including nothing, and we kind of saw it as a bonus feature.

In hindsight I wonder if a better approach would be to just provided our own basic search implementation out of the box that doesn't rely on any third-party services like Algolia, and then let folks upgrade it to something more sophisticated if the project calls for it.

In general though we're really just trying to focus on the UI side of things, which is where we feel we provide the most value. This is the same reason why we didn't include other types of integrations — for example something with the Open API spec. We're really just trying to "stay in our lane" here.

Either way, totally get where you're coming from, and we've already had discussions internally on how we can improve this in the future. Thanks so much for this feedback!
