### ISSUE TITLE
Navbars have strange profile pic border behavior

### ISSUE THREAD

**Issue by ericshively** [tailwindlabs/tailwindui-issues#1405]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/navbars
- Component name: All navbars on page

**Describe the bug**
When you click on profile pics in top-right corner, the border appears momentarily (not sure if desired). Border goes away and the Dropdown is shown. If you click out of the Dropdown, the border around profile pic comes back. You have to then click somewhere again for border to go away. It is not clear to me when the authors intended for the border to appear, but it doesn't seem ideal right now. Especially why the profile pic is bordered even when Dropdown isn't there anymore.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/navigation/navbars
2. Click on any of the Navbar's top right profile pic.
3. Click outside the Dropdown that appears
4. Click somewhere on page again

**Browser/Device**
 - OS: [MacOs]
 - Browser [chrome, firefox]

**Comment by reinink** [comment]
Hey! So this is actually (mostly) the intended behavior. Let me explain 😊

First, when you focus the dropdown button (the profile image), we apply a focus style. This is for accessibility purposes so that the user knows which element they are focused on — especially important if they are using the keyboard.

Next, when you click the button it opens the menu and moves focus into that menu so that you can press up and down with the keyboard. However, when the menu becomes focused, the button looses focus, which is why the outline goes away.

Finally when you close the menu we return focus back to where it previously was — the button, which causes the outline to come back.

I say this is *mostly* the intended behavior because we actually generally prefer to only have focus styles appear when using the keyboard, and not the mouse. And there is a way to do that with modern CSS using the `focus-visible` pseudo-class. However, because browser support hasn't been great for this pseudo-class until more recently, we've had to just stick with the regular `focus` pseudo-class in Tailwind UI.

If you'd like to change this in your own app, it's pretty easy to update the Tailwind UI component to use `focus-visible` instead. Here's an example of how to do this from the [Simple dark with menu button on left](https://tailwindui.com/components/application-ui/navigation/navbars#component-70a9bdf83ef2c8568c5cddf6c39c2331) component:

```diff
  <!-- ... -->

  <!-- Profile dropdown -->
  <x-menu as="div" id="user-menu" open="false" class="relative ml-3">
    <div>
-     <x-menu-button class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
+     <x-menu-button class="flex rounded-full bg-gray-800 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-gray-800">
        <span class="sr-only">Open user menu</span>
        <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
      </x-menu-button>
    </div>

  <!-- ... -->
```

You can see which browsers support `focus-visible` here: https://caniuse.com/css-focus-visible

There is also a focus-visible polyfill put out by WICG, which you can find here: https://github.com/WICG/focus-visible

You might also be interested in the companion PostCSS focus-visible plugin that's designed to work with the WICG polyfill, which you can find here: https://www.npmjs.com/package/postcss-focus-visible

We've used both of these libraries in projects of ours, but I do think we're getting close to not needing these as browser support has become a lot better.

Hope that helps! 💪
