### ISSUE TITLE
Extremely slow compiling for templates

### ISSUE THREAD

**Issue by stephenavocado** [tailwindlabs/tailwindui-issues#1406]
**What component (if applicable)**
- URL for category: https://github.com/stephenavocado/personal

**Describe the bug**
Codes takes several minutes to compile when firing up dev server (yarn dev). Changes to the code require refreshes and another several minutes each time making it pretty unmanageable. 

**To Reproduce**
1. Go to my public repo https://github.com/stephenavocado/personal
2. Open a workspace
3. Enter yarn dev in the command line
4. See several minute wait time for code to compile

**Expected behavior**
Code should compile quickly. Changes should appear instantly once dev server is open. 

**Browser/Device (if applicable)**
 - Browser Chrome

**Additional context**
I used the spotlight template

**Comment by adamwathan** [comment]
Hey! The issue is you changed your `content` configuration to scan every single file/folder in the project including `node_modules` which makes things take a very long time.

Update your `tailwind.config.js` file to be more specific about the location of files that could contain classes and it's all very fast:

```diff
  content: [
-   './**/*.{js,jsx}' 
+   './components/**/*.{js,jsx}',
+   './lib/**/*.{js,jsx}',
+   './pages/**/*.{js,jsx}',
  ],
```

Out of the box we put everything under `src` which makes it easy to write a one-liner content configuration that only looks in the right place, would recommend just keeping things set up that way personally 👍

**Comment by stephenavocado** [comment]
Ah ok - gotcha. Thank you!
