### ISSUE TITLE
Table components don't render as expected

### ISSUE THREAD

**Issue by md97212** [tailwindlabs/tailwindui-issues#1407]
**What component (if applicable)**
- URL for category: 
- https://tailwindui.com/components/application-ui/lists/tables
- Component name: 
Full Width 
**Describe the bug**
Several tables don't render to look like they do in the examples

**To Reproduce**
1. Include the component on a page

**Expected behavior**
I expect to see a full width table

**Screenshots**
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1189243/214912982-882337fd-293d-4a24-bd68-3423f2018eaf.png">

**Browser/Device (if applicable)**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version 109.0.5414.87 (Official Build) (x86_64)

**Additional context**
Other tables also don't render as expected, i.e. the 'Add' button is positioned where it is in the examples

**Comment by adamwathan** [comment]
Hey! I just copy and pasted the [Full width table](https://tailwindui.com/components/application-ui/lists/tables#component-cc6b046f8b3180ace676ce4847f3826f) example and I can't seem to reproduce:

https://play.tailwindcss.com/2m1gCcdtOd

Can you share something to reproduce the issue?

**Comment by md97212** [comment]
hi, 

yes, thanks for the fast response.

go to https://dev.d211amyybexkb2.amplifyapp.com/customer
login with 'dwm97212@gmail.com' and use password of 'password'

**Comment by reinink** [comment]
Hey! Just jumping in to try and help out here.

Looking at the website you provided, I think that your Tailwind CSS configuration maybe isn't quite setup right. It doesn't appear that Tailwind is generating all the necessary classes found in your templates. For example, I don't see `divide-gray-300` or `min-w-full` in your outputted CSS, and both of these classes are used by the table component.

The most likely cause of this is an incorrectly configured `content` key in your `tailwind.config.js` file. Be sure to include *all* of your templates in this option. You can read more about this on the Tailwind CSS website here: https://tailwindcss.com/docs/content-configuration

Also, it appears that you're using Next.js, so maybe check out our guide for this framework if you're wondering how to set things up: https://tailwindcss.com/docs/guides/nextjs

Finally, it's possible that you maybe forgot to rebuild your CSS prior to deploying, or during your deployment process, so that's something else to check out as well.

Hope that helps — good luck! 💪

**Comment by md97212** [comment]
Many Thanks. This helped me resolve it
