### ISSUE TITLE
Lack of spot for feedback / suggestions

### ISSUE THREAD

**Issue by jonfriesen** [tailwindlabs/tailwindui-issues#1408]
👋  hey all,

I've noticed some inconsistencies in places to give feedback or make suggestions. It seems that recently the discussions section of this repo was removed, and the #feedback channel in discord has been restricted asking people to give feedback as an issue, however creating an issue restricts users to the bug reporting workflow.

This isn't anything major, but I figured it was worth noting.

PS. the feedback I wanted to provide is that I love y'all and if you need idea for another template an agency template would be sweet. 

Cheers!

**Comment by adamwathan** [comment]
Ah thanks, didn't notice that inconsistency in Discord! Yeah we decided to get rid of the discussions area because I think it setting the wrong expectations — it started to feel like a roadmap and people were getting frustrated that something was posted _x_ months ago or had _x_ +1s on it and hadn't been built. Definitely still want to hear everyone's ideas but I think just shooting us a tweet is a better way to put it on our radar, and if we like the idea then it's something we'll play with when it makes sense to be on the top of our priority list 👍 

Agency template is a great idea — we've actually been riffing on one since November, hoping to take it over the finish line in the spring:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/4323180/215067560-c92b85e2-35b2-4780-b048-7174cf1a5104.png">
