### ISSUE TITLE
Multi-Column Layouts:  

### ISSUE THREAD

**Issue by mvanbergen** [tailwindlabs/tailwindui-issues#1415]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/application-shells/multi-column
- Component name:  Constrained Three Column

**Describe the bug**
I'm getting the dreaded exception:  "Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports...."

This error happened while generating the page. Any console logs will

**To Reproduce**
1. i copied and pasted the React version of the markup into a new next.js page.
2. I confirmed the component is being exported and enabled the tailwindcss forms in my tailwind.config file.
3. Access the page in my browser
4. See the error as described above. 
5. If i remove the navbar <Disclosure....     </Disclosure> and everything in between it, the page loads fine.  Something is wrong in this area of the code.  This section includes line numbers 32 through 210.  Remove these lines and all is good, but of course I lose the menu.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you attach a minimal reproduction repo so that we can properly debug this?

Some things to try in the meantime:
- Make sure to clear some Next.js related caches: `rm -rf ./.next`
- Make sure you are on the latest Headless UI version: `npm install @headlessui/react@latest`
- Restart your dev server

**Comment by adamwathan** [comment]
@RobinMalfait My guess is this is an issue with using the snippet in a React Server Component playing with the Next.js `/app` directory stuff?

**Comment by RobinMalfait** [comment]
Hmm, the reproduction doesn't use the `app` folder. The issue is not Headless UI in this case but the Heroicon imports.

```
import { MagnifyingGlassIcon } from '@heroicons/react/solid'
import { Bars3CenterLeftIcon, XMarkIcon } from '@heroicons/react/outline'
```

Those 3 icons result to `undefined`, so therefore it results in `<undefined />` when using them. 

Will have to dig deeper, but maybe @thecrypticace has an idea about this.

**Comment by thecrypticace** [comment]
The reason those are undefined is because they are Heroicons v2 icons but are being used with Heroicons v1.

I would upgrade to v2 _if you can_.

If not v1 has some similar icons you can use:
- `MagnifyingGlassIcon` -> `SearchIcon`
- `XMarkIcon` -> `XIcon`
- `Bars3CenterLeftIcon` -> Unfortunately there's no v1 version of this one but I grabbed the JSX from the website and wrapped it in a function so you can pop it in your project instead of importing from the heroicons package:

```jsx
function Bars3CenterLeftIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
      <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12H12m-8.25 5.25h16.5" />
    </svg>
  )
}
```

**Comment by mvanbergen** [comment]
Thank you!  I was able to upgrade to v2 and that did the trick.
