### ISSUE TITLE
Short toggle: White background roundness missmatch

### ISSUE THREAD

**Issue by tordans** [tailwindlabs/tailwindui-issues#1419]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/forms/toggles#component-b3e0a15571300f79fced5845f97fa972
- Component name: Short Toggle

**Describe the bug**

When placed on a dark background, the white background does not have the same corner radius than the inner light gray background.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/forms/toggles#component-b3e0a15571300f79fced5845f97fa972
2. Change the background color of the wrapper div to something dark
4. See error:
    <img width="89" alt="image" src="https://user-images.githubusercontent.com/111561/220397537-98ccdb81-6258-44fa-b6b2-d6c03bc8f6b1.png">

**Expected behavior**
Ideally, the white background would have the same roundness as the inner gray background. 

In addition, a bit of padding on the circle might be good.

_OR:_ The toggle should not have any white background at all, so the gray touches the blue directly.

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: Chrome
 - Version: 109.0.5414.119

**Comment by adamwathan** [comment]
Hey! So TL;DR is just make sure you adjust the background color on this `span` to match the background color of wherever you are using the toggle:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/4323180/220422623-5c5b0407-7846-4a40-a579-247d9872c952.png">

Here is the deep-dive into why this is set up this way though for the curious...

---

So when we first built this component, that element I highlighted above just didn't exist. But without it, look what happens when you focus the toggle...

![image](https://user-images.githubusercontent.com/4323180/220422875-573ec9a8-c6cf-4afe-9822-5e5a849eb536.png)

See that super thin arc of color inside the focus ring on the right? What's happening there is a weird browser rendering glitch where the focus ring style is "bleeding" through a bit on the inside. This happens when you use a box shadow to simulate a ring (like we need to because until like 5 minutes ago browsers didn't respect `border-radius` on the `outline` property), and you give the ring an offset.

To fix this, we need to mask that area with another element that covers it up. That's where that element I talked about above comes in. The problem is, if you give that little cover-up element `rounded-full`, you _still_ get that annoying bleed.

To fix it, we need to give that element just the right amount of corner radius that it doesn't cover up the focus ring, but does cover up the bleed. That's where `rounded-md` comes from, and you can see it more clearly here after making it pinks:

<img width="178" alt="image" src="https://user-images.githubusercontent.com/4323180/220423627-52e42bc9-0cbe-4904-b09e-4a979a697405.png">

See how it's just enough to not interfere with the ring, while still covering up as much as possible? That's the only way to cover that arc without messing up the focus style.

Kind of a nightmare this styling-for-the-web stuff right?

---

Safari _just_ shipped support for rounded outlines in technology preview a few weeks ago, so once support feels mainstream you'll be able to just swap the ring stuff for real `outline` utilities and then this bleed problem goes away too:

```html
  <button type="button" class="group relative inline-flex h-5 w-10 flex-shrink-0 cursor-pointer items-center justify-center rounded-full focus:outline focus:outline-2 focus:outline-indigo-500 focus:outline-offset-2" role="switch" aria-checked="false">
    <span class="sr-only">Use setting</span>
    <!-- Enabled: "bg-indigo-600", Not Enabled: "bg-gray-200" -->
    <span aria-hidden="true" class="pointer-events-none absolute mx-auto h-4 w-9 rounded-full bg-gray-200 transition-colors duration-200 ease-in-out"></span>
    <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
    <span aria-hidden="true" class="pointer-events-none absolute left-0 inline-block h-5 w-5 translate-x-0 transform rounded-full border border-gray-200 bg-white shadow ring-0 transition-transform duration-200 ease-in-out"></span>
  </button>
```

Hope that helps!
