### ISSUE TITLE
Sidebar/Dialog component breaks when migrating bg-opacity-75 in given templates to v3.2.7

### ISSUE THREAD

**Issue by SharadKumar** [tailwindlabs/tailwindui-issues#1422]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: [Light sidebar with light header](https://tailwindui.com/components/application-ui/application-shells/sidebar#component-ba754bf465a594eb075045eb9e940b60) - React

**Describe the bug**
Dialog component opens/close and then is not restored. Instead I have the greyd-out background left as-is, unless I hard refresh. This happens *after* I have changed existing `bg-opacity-75` to `opacity-75`, as per screenshot below. Defect is fixed when I put the value back. VSCode shows squiggle for `bg-opacity-75` with v3.2.7.

**To Reproduce**
1. Copy above component in your react project/page.
2. Test and it all works fine. 
3. Then change `bg-opacity-75` to `opacity-75`
4. Retest and sidebar will emerge just fine. But when you close it...
5. See error i.e. your background is not cleared.

**Expected behavior**
Allow migrating to v3 values.

**Screenshots**

<img width="619" alt="image" src="https://user-images.githubusercontent.com/5488144/221488177-e2e945d2-da25-4fc6-ba5d-27c3283e0deb.png">

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: Chrome

**Additional context**

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Not 100% sure where these migrations are coming from, but I don't think you want to use `opacity-75` in this case.

`bg-opacity-75` is about the background color only, but `opacity-75` would be for the full element. In this specific case it _might_ be fine (because you don't have content) however there is another issue. The transition component is already transitioning from `opacity-100` to `opacity-0` and back. If you already add `opacity-75` not a lot of transitioning is going to happen.

Instead, I would recommend you to change the color itself:

```diff
- bg-gray-600 bg-opacity-75
+ bg-gray-600/75
```

In this case you are only changing the background color using the new syntax. More info on this syntax can be found here: https://tailwindcss.com/docs/background-color#changing-the-opacity

Hope this helps!

**Comment by SharadKumar** [comment]
Thanks @RobinMalfait for clarifying.
https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/migration-from-tailwind-2.md
