### ISSUE TITLE
The definition of class styles is missing in the example configuration screen

### ISSUE THREAD

**Issue by davidmartin** [tailwindlabs/tailwindui-issues#1423]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-de918ddc41eab4f395f5e48ce2815937
- Component name: [With tiered sidebar navigation](https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-de918ddc41eab4f395f5e48ce2815937)

**Describe the bug**
I can't find the definition of these classes neither in tailwindcss nor in the example:

bg-blue-gray-50
text-blue-gray-600

**To Reproduce**
1. Go to settings screen example 
2. Click on Code for React
3. Copy all example in a project with tailwindcss (3.2.7)
4. The above classes do not have styles.

**Expected behavior**
The expected behaviour is that the following classes have styles:

bg-blue-gray-x
text-blue-gray-x

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11908901/222103166-b9265eb3-b15e-468f-a1c5-798c82ce302d.png">

**Browser/Device (if applicable)**
 - Browser chrome
 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/11908901/222103524-714957f7-da43-4729-8468-fd9b116a9db5.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a left over from the v2 colors (https://tailwindcss.com/docs/upgrade-guide#renamed-gray-scales), I've updated them to the v3 colors and this change should be fixed in production right now. You can re-copy the code from taillwindui.com or if you already made some changes, you can apply the changes in your project. 

You should be able to replace the following:

- Change `blue-gray` to `slate`
- Change `warm-gray` to `stone`

Hope this helps!
