### ISSUE TITLE
components/marketing/sections/heroes - "With phone mockup"

### ISSUE THREAD

**Issue by KillTomer** [tailwindlabs/tailwindui-issues#1434]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name: With phone mockup

**Describe the bug**
Mobile menu doesn't close after clicking the link /#... It scrolls down correctly under the menu, but it doesn't close the menu. 

**To Reproduce**
Vue JS version, if width < 640px. If you open the mobile menu, it never closes it after clicking on any (scroll down) link /#... in the mobile menu.
- There are no errors in the compilation. 

**Expected behavior**
After clicking on a link it should close the menu.

**Screenshots**

**Browser/Device (if applicable)**
 - OS: any
 - Browser any
 - Version newest

**Additional context**
I

**Comment by thecrypticace** [comment]
Hey! Totally get's what you're saying here. By default we do not close the menu on these components. Because every app is different, the way you close this menu would be implemented differently based on the framework you're using or situation you are in.

Some examples:
1. In server-side-rendered apps you would change the urls to the appropriate pages and the browser refresh would cause the menu to close.
2. In an SPA with a router (e.g. Vue Router) you can add a listener to the router to close the menu when the route changes.
3. For other situations where you have a hash/fragment link to the _same_ page you can add an `@click` handler to the link to close the menu.

Because the ways to handle these are different enough there is generally no one-size-fits-all approach which is why we don't provide these behaviors by default in the components.

Hope that helps — let me know if you have any further questions! ✨
