### ISSUE TITLE
HeadlessUI supported Tab examples

### ISSUE THREAD

**Issue by OliverRC** [tailwindlabs/tailwindui-issues#1438]
**What component (if applicable)**
- [Application UI](https://tailwindui.com/components#product-application-ui) / [Navigation]https://tailwindui.com/components#product-application-ui-navigation)
- Component name: Tabs

**Describe the bug**
It would be great if the tabs in the examples were functional like many of the other examples that use HeadlessUI for the javascript side of things.

**Expected behavior**
Functional tabs supported by [Tabs - Headless UI](https://headlessui.com/vue/tabs)

**Comment by reinink** [comment]
Hey, thanks so much for sharing this feedback!

I agree, it would be great to have some JavaScript-based tab examples in the [tabs category](https://tailwindui.com/components/application-ui/navigation/tabs). When we originally released these tab examples Headless UI actually didn't even exist yet 😅

I do think there are good use-cases for the link-based tabs still. I know in my own apps that I'll often use a tab style navigation where each tab links to a different page, instead of switching content client-side.

Either way, we'll be sure to consider adding some JavaScript-based tab examples to this category in a future update to Tailwind UI. Until then, you can find some examples of these in the ecommerce bundle. Here's two in particular:

- [Product Features  / With tabs](https://tailwindui.com/components/ecommerce/components/product-features#component-1c59e9598a7ee96a39f2a1c1e6b270a7)
- [Product Pages / With tabs and related products](https://tailwindui.com/components/ecommerce/page-examples/product-pages#component-5d28bf260035512bddeb20cab56e052d)

Hope that helps! 💪

**Comment by OliverRC** [comment]
Ah! nice one, thanks for the links to the eCommerce examples.
It wasn't hard to get working with the joy that is HeadlessUI + Tailwind ❤️
