### ISSUE TITLE
Duplicate ring highlights on mouseDown

### ISSUE THREAD

**Issue by kenn** [tailwindlabs/tailwindui-issues#1462]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/radio-groups#component-45612766894822db447a2837d79355f5
- Component name: Cards

**Describe the bug**
React code does not behave the same way as preview.

- On mouseDown, nothing happens in Preview (feels right), but ring highlights in real code (feels wrong)

**To Reproduce**
1. Click and hold the mouse press on one of the cards
2. See ring highlights duplicated on multiple cards

**Expected behavior**
Nothing happens on mouseDown

**Screenshots**
<img width="959" alt="Screenshot 2023-06-06 at 16 10 18" src="https://github.com/tailwindlabs/tailwindui-issues/assets/10350/f149d8a7-2412-46da-8478-27b613a648c6">

**Additional context**
Remix v1.16.1 / React

**Comment by bradlc** [comment]
Hey @kenn. Thanks for bringing this to our attention. I understand that it's confusing that the preview on the website doesn't match what you are seeing in your own app.

With that in mind, it is actually the React version that you are using that behaves as originally intended. The two rings represent two different states:

- The more prominent ring (on the middle item in your image) is the "active" style. Items become active immediately on mouse down.
- The smaller ring is the "checked" (or "selected") style. When using a mouse an item does not become checked until mouse up.

Hopefully that explains why you may see multiple rings at the same time.

We have now fixed the component preview so that it works as originally intended 👍

**Comment by kenn** [comment]
Ah, that's good to know. Thanks for clarifying.

But doesn't that leave the state in a weird way?

- Click one box, but it wasn't the one you intended to click
- So keep pressing and move out the mouse, then release

This I think is a common pattern for UI — for buttons, etc.

On [the new updated page](https://tailwindui.com/components/application-ui/forms/radio-groups#component-45612766894822db447a2837d79355f5), if I follow the same "press, move out, release" pattern, that leaves two highlighted boxes permanently.

Is this also intentional?

<img width="942" alt="Screenshot 2023-06-28 at 7 29 45" src="https://github.com/tailwindlabs/tailwindui-issues/assets/10350/4c0edd4a-f9c2-40f7-a0af-a020ae507656">
