### ISSUE TITLE
Studio template code highlights seem to be missing colors in code highligther. Is this by design ?

### ISSUE THREAD

**Issue by ymolists** [tailwindlabs/tailwindui-issues#1478]
**What component (if applicable)**

latest studio template 
https://tailwindui.com/templates/studio

**Describe the bug**
The code higligther is not showing any code colors. Which to me is not intuitive but i could be wrong. Is there a setting i have to set to get a particular theme ? 

**To Reproduce**
default studio template

**Expected behavior**
My expectation was that it would look like the one in the spotlight template which is the second attached image

**Screenshots**
Currently this is what it shows
![studio-current](https://github.com/tailwindlabs/tailwindui-issues/assets/6591993/8bef2a00-5b84-4d6d-b736-0e022b8870a2)

Expected as in spotlight template

![studio-shouldbe](https://github.com/tailwindlabs/tailwindui-issues/assets/6591993/e1a85fa9-b21c-49ca-bca5-b3d2024634b5)

**Comment by adamwathan** [comment]
Hey! This is by design at the moment at least — since the whole template is grayscale/monochromatic we opted for using just shades of gray for the built-in syntax highlighting.

You can edit this really easily in the `typography.css` file though — you'll see a bunch of CSS variables like this declared near the top of the file:

```css
  --shiki-color-text: theme(colors.white);
  --shiki-color-background: theme(colors.neutral.950);
  --shiki-token-constant: theme(colors.neutral.300);
  --shiki-token-string: theme(colors.neutral.400);
  --shiki-token-comment: theme(colors.neutral.500);
  --shiki-token-keyword: theme(colors.neutral.400);
  --shiki-token-parameter: theme(colors.neutral.400);
  --shiki-token-function: theme(colors.neutral.300);
  --shiki-token-string-expression: theme(colors.neutral.300);
  --shiki-token-punctuation: theme(colors.neutral.400);
```

If you edit those variables, that'll update the syntax highlighting. If you like the colors from Spotlight, you can open up the `prism.css` file in that template to see the colors we're using there. We used Prism.js on that project but we're using Shiki on newer ones because I find it a little nicer to customize since it's just a handful of CSS variables 👍 

Hope that helps!
