### ISSUE TITLE
Mutating dialog leaves areas not repainted

### ISSUE THREAD

**Issue by marco-de-angelis** [tailwindlabs/tailwindui-issues#1513]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/command-palettes
- Component name: Dialog

**Describe the bug**
Dialogs that modify their internal content gets incorrectly displayed.

**To Reproduce**
1. Go to "Command palettes" with images and descriptions at https://tailwindui.com/components/application-ui/navigation/command-palettes#component-f55d785e34cd53505459e68e32af879f
2. Start typing some filter in the search bar, e.g. "asd". The empty state will be displayed
3. Start deleting characters to the filter until some data is displayed
4. See the error of partial dialog being drawn.

**Expected behavior**
The dialog should be painted completely, based on the filtering criteria

**Screenshots**

**Browser/Device (if applicable)**
 - OS: macOs
 - Browser Both Chrome and Safari
 - Version: latest

**Additional context**
I tried also not to use ComboBox, thinking the issue was caused by that, but the issue still remains.

**Comment by thecrypticace** [comment]
Hey, if I'm reading this right, this sounds like a possible browser bug to me. Can you give me more details on your environment and also provide a screenshot of what you're seeing?

**Comment by marco-de-angelis** [comment]
Hi.

I'm using

Safari Version 16.6 (18615.3.12.11.2) on macOS Ventura 13.5.2. I tried replicating with Chrome and Arc Browser, but the error is not showing up. Seems you're right at pointing at the specific browser issue.

Attaching a low-resolution screencast that shows the behaviour. Hope it helps!

https://github.com/tailwindlabs/tailwindui-issues/assets/74043581/5d6f9bd4-2e70-4c05-91cb-28daf9d67784

<img width="1140" alt="Screenshot 2023-10-12 at 20 26 53" src="https://github.com/tailwindlabs/tailwindui-issues/assets/74043581/e24b330b-5ee7-4b5f-9d03-beafcb6d3419">

**Comment by thecrypticace** [comment]
Hey, so this is 100% a Safari bug that was introduced sometime after 16.3 and I've seen this one before on other websites too. And, from my testing, it's been fixed in Safari 17.

Here's a similar issue to this related to our template:
https://github.com/tailwindlabs/tailwindui-issues/issues/1470

If you see this in your own project I'd suggest placing `transform-gpu` on possibly the options element in this case and see if it works.

Gonna update our preview to account if/when I can reproduce this myself on 16.x. It'll take a bit before I can do that as I'm already on Safari 17 so I'll need to test in a VM to verify (and they take a while to download)

**Comment by thecrypticace** [comment]
I've updated the three affected examples on the page (and the code snippets) to have `transform-gpu` to work around the Safari bug.

**Comment by marco-de-angelis** [comment]
Awesome, thanks for the super-swift reaction!
