### ISSUE TITLE
Alpine.js source missing

### ISSUE THREAD

**Issue by sprightlydev** [tailwindlabs/tailwindui-issues#1515]
Hello, the UI includes HTML components with behavior that isn't included in the displayed source, making working with this framework difficult for anyone not using React.

If you're not going to support Alpine development in the documentation examples, how about providing the source somewhere so people can use it? The examples are/were good and work fine, just dump them somewhere and call it "unofficial" or "the last release" if necessary.

**Comment by adamwathan** [comment]
Hey! So the Alpine code used in the demos is unfortunately just far from production-ready which is why we don't go out of our way to make it easy to get, and don't market it as part of the product. The stuff built with Alpine is missing lots of important accessibility functionality and includes lots of hard-coded "demo-mode" behavior (like dialogs that automatically re-open after you close them for example), and is purely there to demonstrate the visual states of the components.

For this reason, long-term we plan to remove all of the Alpine code in the live demos and replace it with React, which is what we already do for all of the newer components.

So sorry to disappoint here but we don't plan to provide the source for the current Alpine stuff — it would just be irresponsible of us and mislead people into thinking the code was suitable to use in real projects when it's nowhere close to that. Hope that is at least helpful!
