### ISSUE TITLE
Multi column layouts don't seem to be working on demo page

### ISSUE THREAD

**Issue by mschipperheyn** [tailwindlabs/tailwindui-issues#1517]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/multi-column
- Component name: Multi Column Layout

**Describe the bug**
It doesn't work on the demo page. None of them do. Selecting React or Vue seems to make no difference

**To Reproduce**
Go to the page and try clicking on anything

**Expected behavior**
I expect some kind of slide out menu I guess

**Screenshots**

**Browser/Device (if applicable)**
 - OS: [e.g. iOS]: Mac OS
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 119.x

**Additional context**

**Comment by RobinMalfait** [comment]
Hey!

Can you share a screenshot of what you are seeing exactly?

Looking at the page they do seem to work as expected to me, they are currently implemented where you have multiple columns, but on smaller screens some of the columns go away. The columns right now also have placeholders to indicate where you can insert your own contents. If you copy the code you will find comments like these:
```html
<main>
  <div>
    <div>
      <!-- Main area -->
    </div>
  </div>
</main>

<aside>
  <!-- Secondary column (hidden on smaller screens) -->
</aside>
```

Some screenshots of what I see and what you should see as well:

<img width="1349" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/1834413/2b620dca-05c7-4f58-95d4-225e372cea9a">
<img width="1342" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/1834413/f182fb70-fd06-43c2-a9b9-56a882ec3cb0">

Is this what you see as well? If so, then this is currently the expected behaviour.
If you don't see this, can you try in another browser or a private/incognito window where browser extensions are disabled?

Could you also elaborate what you mean with `Go to the page and try clicking on anything`? The only clickable things on these examples should be the sidebar and the menu button (on smaller displays).

Thanks!
