### ISSUE TITLE
Backdrop effect of mobile menu is not visible

### ISSUE THREAD

**Issue by kamal-choudhary** [tailwindlabs/tailwindui-issues#1523]
**What component (if applicable)**
- URL for category: [Headers](https://tailwindui.com/components/marketing/elements/headers)
- Component name: [With stacked flyout menu](https://tailwindui.com/components/marketing/elements/headers#component-27e5f71ced91b88e3f6b59ca69033a83)

**Describe the bug**

On the mobile version, the backdrop of the **Modal** is not visible.

In the code, we have this part:

```
<Dialog as="div" className="lg:hidden" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
        <div className="fixed inset-0 z-10" />
        <Dialog.Panel>
            // omitted for brevity
        </Dialog.Panel>
</Dialog>
```

I looked into the [Headless UI docs](https://headlessui.com/react/dialog#adding-a-backdrop), and found that this **empty div** element is basically used for backdrop effect.

**Expected behavior**
The effect of the **Backdrop** should be visible.

Adding a **background-color** actually fixes this.

So, the solution would be something like this:

```
<Dialog as="div" className="lg:hidden" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
        <div className="fixed inset-0 z-10 bg-black/30" />
        <Dialog.Panel>
            // omitted for brevity
        </Dialog.Panel>
</Dialog>
```

**Additional context**

1. Without a **background-color** or a comment, it can be a source of confusion for new users that why this **empty div** exists.
2. Maybe, we can add **aria-hidden="true"** attritbute on **empty div** also, as it is being used [here](https://headlessui.com/react/dialog#adding-a-backdrop).
3. This is same for the other examples on the [Headers](https://tailwindui.com/components/marketing/elements/headers) page.

**Comment by reinink** [comment]
Hey! Happy to help explain why things are setup this way for these components.

So you're absolutely right, the dialog backdrop in these header components isn't visible. This was an intentional design decision — we didn't want a visible backdrop for the mobile nav dialog in these particular components. Technically we could remove this element entirely.

However, with Tailwind UI we try to build our components in such a way that they are easy to customize. If we were to remove this backdrop entirely it would make it more difficult for people to add a class like `bg-black/30` should they want a visible backdrop in their project.

This backdrop is also useful for the HTML-only version of this component, as it prevents a user from being able to click on interactive elements in the background while the dialog is open.

And finally, yes, we could add `aria-hidden="true"` to this backdrop since it's a visual-only element, but since it's not interactive and since it has no content, assistive technology is going to skip right over it either way. Honestly, we should probably just remove this attribute from the Headless UI docs.

I hope that helps explain why these components are built in this way. And, of course, once you copy and paste a component into your application you are completely free to modify it however you like 👍

**Comment by kamal-choudhary** [comment]
Hi @reinink, thank you so much for explaining this - this clears all the confusion.

Totally agree with you on `aria-hidden="true"`, I was also going to remove it from code thinking that empty `div` is non-interactive element. But kept it only because Headless UI docs example used this.

**Just my humble suggestions:**

Adding a comment like this:
```
{/* The backdrop, rendered as a fixed sibling to the panel container */}
```
above the **empty div** element can help future users quickly figure out the purpose of this element. 

And once again, thank you for the detailed response.
