### ISSUE TITLE
Tailwind UI with React: On new page loads, the sidebar does not animate on show

### ISSUE THREAD

**Issue by jaison2007** [tailwindlabs/tailwindui-issues#1525]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar#component-966a548c3d7225d9155a443e979057b5
- Component name: [Light sidebar with constrained content area](https://tailwindui.com/components/application-ui/application-shells/sidebar#component-966a548c3d7225d9155a443e979057b5)

**Describe the bug**
On new page loads, the sidebar does not animate on show. Follow-up shows and hides animate properly. This affects the React version of the component, but I don't believe it affects VueJS so this might be a bug in the @headlessui/react library.

**To Reproduce**
1. Clone https://github.com/jaison2007/tailwind-ui-debug
2. Pack and compile code using instructions in README.md
3. Open index.html in Chrome or Firefox.
4. Click on hamburger menu.
5. Sidebar does not animate on page load (please see recording for more information)

**Expected behavior**
Sidebar should animate on page load.

**Screenshots**
[Screencast from 2023-11-17 22-55-31.webm](https://github.com/tailwindlabs/tailwindui-issues/assets/76921484/d0e2ff5a-e131-4953-9b17-44fc8159140a)

**Browser/Device (if applicable)**
 - OS: Fedora
 - Browser Chrome / Firefox tested
 - Version Chrome 118.0.5993.117 (Official Build) (64-bit)

**Comment by thecrypticace** [comment]
Hey! So this is happening because you're using the CDN. The way it works internally is it uses `MutationObserver` to discover classes in the DOM and then generate any new ones it finds on-the-fly.

You're seeing a flicker because the timing for transitions is *very* particular. If you add a class in one frame, and then define it in the next (for example `transition`, or `-translate-x-full`), you will get extremely odd results which can include flickering or jumping straight to the end of the transition. And, in the case of Headless UI's `<Transition>` component — the components are injected only when you change the state to show the dialog rather than always being present in the DOM. There's nothing _we_ can do to address this in the CDN due to the way `MutationObserver` works in browsers. Changes to the DOM are batched together but they're delivered at a different time then we'd want to be able to introduce the classes for transitions to work properly.

This is one of the major reasons we don't reocmmend using the CDN for anything other than quick development (and definitely **do not use it in production**). In your setup I would install Tailwind CSS proper, setup the content, and have webpack compile the CSS.

However, as a workaround, if you still want to use the CDN, you can add some unconditionally rendered divs that include the classes so they'll be generated immediately when the page loads instead of when the transition is trying to animate the dialog in.

Place these outside of the `<Transition.Root>` and the flicker will disappear.
```
{/* Force the CDN to generate classes ahead of time */}
<div className="transition transition-opacity"></div>
<div className="ease-linear ease-in-out "></div>
<div className="duration-300"></div>
<div className="-translate-x-full translate-x-0"></div>
<div className="opacity-0 opacity-100"></div>
<div className="transition transform"></div>
```

Hope that helps! ✨

**Comment by jaison2007** [comment]
Thanks so much for getting back - we had noticed that when we put breakpoints into the animation and broke it down we noticed that with the Play CDN the page animated backwards (!!) and snapped back within a frame on first page load. Switching to the bundled CSS did fix this for us. Glad for the confirmation by the team.

It might be a good idea to add a warning to https://tailwindcss.com/docs/installation/play-cdn or https://tailwindui.com/documentation that says that certain animations might not work? Thanks again!
