### ISSUE TITLE
<Table> <th> and <td>: Excessive Width Issue Due to Long Texts

### ISSUE THREAD

**Issue by zulkufdemirhan** [tailwindlabs/tailwindui-issues#1531]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/lists/tables
- All table components

**Describe the bug**
When long texts are used within the tags in the table, the texts cause the table to expand undesirably, exceeding its width.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/lists/tables
2. Pick "Simple in card" or other table components code
3. Insert long text into `<th>` or `<td>` elements.
4. See the bug

**Expected behavior**
Ensure that by default, `<th>` and `<td>` elements control long texts with causing excessive table width or restrict them appropriately.

**Screenshots**

<img width="1206" alt="Screenshot 2023-12-20 at 22 53 22" src="https://github.com/tailwindlabs/tailwindui-issues/assets/95721351/fd908003-b580-49f2-99ed-8c4e8fc5dea4">

<img width="1193" alt="Screenshot 2023-12-20 at 22 55 50" src="https://github.com/tailwindlabs/tailwindui-issues/assets/95721351/c2afcbc9-c4b3-43ec-b498-6948f1cc61da">

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: Mozilla Firefox 
 - 14.2.1

**Comment by reinink** [comment]
Hey! Happy to help out here.

So by default we include the `whitespace-nowrap` class in the cells of the tables in Tailwind UI, since that generally works pretty well with responsive tables. However, think of this as just a suggestion/starting point — Tailwind UI components are designed to be customized to fit the needs of your particular project. For example, in this situation you might need to make some tweaks to accommodate this longer content in the table.

One option is to simply remove the `whitespace-nowrap` class from the `<td>` with the long content, which will allow this content to wrap:

```diff
- <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">Magna laboris occaecat laboris...</td>
+ <td class="px-3 py-4 text-sm text-gray-500">Magna laboris occaecat laboris...</td>
```

<img width="883" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/080b8b0d-4dc4-4832-a57e-225041a49c56">

[View live demo →](https://play.tailwindcss.com/brmzR7kYgV?size=824x720)

Alternatively you could wrap the long content in a `<div>` with a max-width and the `truncate` class, which will cause this content to truncate before getting too long:

```diff
- <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">Magna laboris occaecat laboris...</td>
+ <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
+   <div class="max-w-xs truncate">Magna laboris occaecat laboris...</div>
+ </td>
```

<img width="883" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/b51d3c81-1ef2-4ff9-84bd-adace3ecbbab">

[View live demo →](https://play.tailwindcss.com/lLmU6zoo1W?size=824x295)

I hope that helps! 🤙

**Comment by tordans** [comment]
_Update:_ I ran into this today and it looks like things changed, so the solution is different today:

Using the example from https://catalyst.tailwindui.com/docs/table, there is no `whitespace-nowrap` on the `td`/`th` but the text still behaves like it. 

> <img width="968" alt="image" src="https://github.com/user-attachments/assets/7f6176cf-e109-4ac4-8e83-b8f65f9da15a">

The issue is, that the `whitespace-nowrap` from the wrapper DIV changes the behavior of the cells as well.

Since we need the class on the wrapper, the solution seems to be to add an explicit `whitespace-normal` to `TableHeader`, `TableCell`

``` diff
clsx(
        className,
+         'whitespace-normal',
        'font-medium border-b
```

> <img width="908" alt="image" src="https://github.com/user-attachments/assets/6609bfb7-b267-4cb6-8851-70a2ef692f57">

---

This cost me way too much debugging time and I think it would be worth mentioning this on the docs at https://catalyst.tailwindui.com/docs/table @reinink

**Comment by zulkufdemirhan** [comment]
Hi @tordans, @reinink  ,
I just tested this issue on my end and encountered the same behavior. Maybe this solution could hepl you:

<img width="1400" alt="Screenshot 2024-10-30 at 12 41 55" src="https://github.com/user-attachments/assets/ee3f25a0-e859-4c8d-a4e9-53eace81a9ff">

In your main stylesheet, try applying the following styles directly to `<td>` or `<TableCell> `element:

```
{
  overflow: hidden;
  text-overflow: ellipsis;
}
```

If you’d prefer not to truncate the text, you can simply apply this code to the same element:

```
{
 white-space: normal;
}
```

By setting a maximum width on the `<td>` or `<TableCell>` elements with these methods, you can effectively control text overflow in your table layout from a single point and achieve a cleaner appearance.

<img width="1409" alt="Screenshot 2024-10-30 at 12 43 14" src="https://github.com/user-attachments/assets/3e33c8b4-a736-4089-8709-247056ad5761">

I hope these suggestions help you resolve your issue.
