### ISSUE TITLE
[Catalyst] Modals overflow behavior causes quirks

### ISSUE THREAD

**Issue by arronhunt** [tailwindlabs/tailwindui-issues#1532]
**What component (if applicable)**
Any Catalyst component that causes the html element to have `overflow: hidden;` applied. 

**Describe the bug**
Since certain elements cause the html tag to hide its overflow, the scrollbar will appear or disappear, causing a vertical shift in the page layout. 

**To Reproduce**
1. Go to https://catalyst.tailwindui.com/docs/dialog
2. Open the dialog

**Expected behavior**
Not that!

**Screenshots**

![Dec-20-2023 17-01-13](https://github.com/tailwindlabs/tailwindui-issues/assets/298336/b1a0c315-168e-445e-a5ea-978fd6b68e02)

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: Safari
 - Version: 17.1

**Additional context**
I haven't tested the components in my own project yet, so it's unclear if this is a bug with the components or just the docs site.

**Comment by mryechkin** [comment]
This isn't exclusive to Catalyst I'm afraid - several other libraries that prevent scrolling when the popover is open have the same behaviour. For example:

React Aria Components: https://react-spectrum.adobe.com/react-aria/Select.html

Radix-UI: https://www.radix-ui.com/primitives/docs/components/select

I'm not sure if there's a way around it while maintaining the "modal" behaviour. I know in React Aria you can set the `Select` to be non-modal, not sure if that's an option in Catalyst.

**Comment by srcn** [comment]
Angular CDK solves this problem by blocking the scroll. It adds the following class to the `html` when any overlay-like behavior is active:

```css
.cdk-global-scrollblock {
  position: fixed;
  width: 100%;
  overflow-y: scroll;
}
```

Forcing `overflow-y` ensures the scrollbars are not hiding when the position is fixed so they don't cause horizontal shift. It then calculates the current scroll positions and adds them to `html` as well. This way scroll positions are not lost and can be restored when overlay dismissed:

```css
html {
  left: 0px;
  top: -484px;
}
```

Not sure if this would be a feasible solution for Catalyst (or HeadlessUI) but it's there. I implemented this solution countless times (without Angular CDK) and it works just fine.

Full code for this strategy: https://github.com/angular/components/blob/main/src/cdk/overlay/scroll/block-scroll-strategy.ts

**Comment by heychazza** [comment]
I noticed this same thing happens on the home page too (where the modal itself shifts to one side)

https://github.com/tailwindlabs/tailwindui-issues/assets/47271716/76a9cacb-4cb0-4845-8a7e-938cd4da4433

**Comment by tomirons** [comment]
I don't see the same issue on either the home page **or** the dialog page with safari 17.2. Maybe it was a browser issue?

**Comment by mryechkin** [comment]
> I don't see the same issue on either the home page **or** the dialog page with safari 17.2. Maybe it was a browser issue?

Looks like they did some tweaks in Headless UI shortly after this issue was logged: https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui/react%40v2.0.0-alpha.3

Likely it wasn't updated upstream yet, and now is - because I'm also not seeing the original issue, the scroll bars are staying in place now.

**Comment by reinink** [comment]
Hey folks!

Thanks so much for the quick feedback on Catalyst. We tried really hard to catch all these bugs before release day, but isn't that how these things always go? 😆

We've corrected the listbox page shifting issue — this was actually an issue with our docs themselves. Basically, as some of you have suggested, when Headless UI does scroll locking the browser removes the scrollbar which causes the page to shift. To counter this we automatically add right padding to the page.

This generally works great, but we were using some fixed positioning in our docs that doesn't respect the right padding on the body, which caused this shift to still occur. That's all fixed up now.

As for the dialog (and alert) shifting issue — that problem is also related to scroll locking, but the fix here was to tweak the components themselves. We've made that change and have already published a new version of Catalyst.

You can update these components in your own project (if you happen to already have a Catalyst project up and running! 😮), by downloading Catalyst again from the Tailwind UI website and replacing the `dialog.tsx` and `alert.tsx` files.

Alternatively you can just make this change to each of these files:

```diff
        <HeadlessTransitionChild
-         className="fixed inset-0 overflow-y-auto pt-6 sm:pt-0"
+         className="fixed inset-0 w-screen overflow-y-auto pt-6 sm:pt-0"
```

That's all it should take!

Thanks again for reporting — and enjoy Catalyst! 🙌

**Comment by ivan-kleshnin** [comment]
What is the difference between `Alert` and `Dialog`? They look so similar I wonder why not have just one of them.
