### ISSUE TITLE
404 page does not render at full height

### ISSUE THREAD

**Issue by dimerman** [tailwindlabs/tailwindui-issues#1536]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/feedback/404-pages
- Component name: simple, with background image

**Describe the bug**

**To Reproduce**
- Created a 404.js page in Gatsby
- added the <html class="h-full"> and <body class="h-full"> tags via Head API (confirmed on browser)

**Expected behavior**
the background image covers full screen

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/633961/eb6841da-5a30-4ca6-afd4-d0ab03accbad)

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser chrome
 - Version 120.0.6099.109

**Additional context**

**Comment by adamwathan** [comment]
Hey! The issue here is those two extra `div` elements Gatsby is adding in between `body` and `main` — those both need `h-full` as well in order for the `min-h-full` on the `main` tag to inherit the correct height.

Alternatively you could use `min-h-lvh` on the `main` element which is a nice modern solution to this problem as long as you don't need to support older browsers 👍

**Comment by dimerman** [comment]
thanks @adamwathan !
