### ISSUE TITLE
Catalyst Button does not operate fully

### ISSUE THREAD

**Issue by timmeade** [tailwindlabs/tailwindui-issues#1542]
**What component (if applicable)**
- URL for category:  
- Component name:  Button

**Describe the bug**
Default Button does not perform click through in a manner consistent with either button or shadcn Button.

Example:  Next-Auth signin in create-t3-app with NextJS 14.0.4

```
      <form
        action={async () => {
          "use server";
          await signIn("google");
        }}
      >
        <Button >
          Sign in with Google
        </Button>
      </form>
```

if button or shadCN button this works very well.   If catalyst Button.  Nothing.

**Expected behavior**
Button should let the server action occur and signin occur.  Note this also is same issue and results for SignOut.

**Comment by reinink** [comment]
@timmeade Hey, just a real quick thought here — the default button `type` in Catalyst is `button`, not `submit`. Can you try adding `<Button type="submit">` and let me know if that fixes things for you?

**Comment by timmeade** [comment]
Yes it fixed it.

I did not see that.  

If plain "button" instead of the catalyst Button import the code works also, but setting to submit in catalyst fixed the issue i am having.

**Comment by reinink** [comment]
Okay great!

We had some discussion as a team while building Catalyst about whether we should stick with the browser default of `type="submit"`, but opted to go with `type="button"` since, at least from our experience, that felt like the more common use-case.

Further, if you're not careful and forget to set a type, the default of `type="submit"` can actually lead to unexpected form submissions if the button happens to exist within a `<form>`, but you don't get those kinds of issues with `type="button"`.

To make this more clear I've added the `type` prop (which shows the default as `button`) to the Catalyst docs: https://catalyst.tailwindui.com/docs/button#component-api

Hope that helps! 🤙

**Comment by timmeade** [comment]
Much thanks.  Helps a lot.
