### ISSUE TITLE
Catalyst Textarea

### ISSUE THREAD

**Issue by KitsonBroadhurst** [tailwindlabs/tailwindui-issues#1543]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs/textarea
- Component name: Textarea

**Describe the bug**

Passed in classnames to the Textarea component are applied to the parent span rather than the actual textarea component. e.g. passing in tailwind class `resize-none` doesn't apply to the textarea.

**To Reproduce**
Add classname `resize-none` to the Textarea component

**Expected behavior**
The rendered textarea shouldn't be resizable.

**Additional context**
Simple workaround is to manually update the Textarea implementation in my code:
<img width="292" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/8405069/a04a1445-06f0-40ea-8dba-b8be32690f3f">

**P.S.**
Thank you so much for this new Catalyst UI library, it's awesome and I'm very grateful.

**Comment by reinink** [comment]
Hey! So you're right, the `className` prop is applied to the wrapping `<span>` around the `<textarea>` and not the textarea itself. This is by design as it allows you to apply spacing and layout styles to the textarea — like a top margin. However, this does make it more difficult to apply styles like `resize-none` to the textarea itself.

I think the best way to handle this situation is to add a new `resizable` prop to the textarea that defaults to `true`, but when set to `false` adds the `resize-none` class.

I've gone ahead and made this change to this component, so feel free to download Catalyst again and grab the updated `textarea.tsx` component.

Alternatively, you can make this change yourself. First, add the new `resizeable` prop to the `Textarea` component:

```diff
- export const Textarea = forwardRef<HTMLTextAreaElement, HeadlessTextareaProps>(function Textarea(
-   { className, ...props },
-   ref
- ) {
+ export const Textarea = forwardRef<HTMLTextAreaElement, { resizable?: boolean } & HeadlessTextareaProps>(
+   function Textarea({ className, resizable = true, ...props }, ref) {
```

Next, in the class list, conditionally apply the resize classes based on this new prop:

```diff
            // Disabled state
            'disabled:border-zinc-950/20 disabled:dark:border-white/15 disabled:dark:bg-white/[2.5%] dark:data-[hover]:disabled:border-white/15',
+
+           // Resizable
+           resizable ? 'resize-y' : 'resize-none',
```

I hope that helps! 🤙

**Comment by KitsonBroadhurst** [comment]
Awesome, thanks for the update
