### ISSUE TITLE
When copying Multi-Column Layouts, the components selected are incorrect.

### ISSUE THREAD

**Issue by DionneChelini** [tailwindlabs/tailwindui-issues#1553]
I've identified another issue on your site and have created a video to demonstrate the problem. It appears that certain components displayed on your site do not match what is copied. This inconsistency is causing inconvenience as I require accurate components for a client project. Could you please address this issue at your earliest convenience? Thank you.

Video here
https://share.vidyard.com/watch/VTNNXrMyKwjvWihD6J9gzJ?

**Comment by adamwathan** [comment]
Hey! At a quick glance it looks like the problem here is that the responsive styles aren't being respected (you're seeing the mobile layout at all sizes). The code that's copied in your video is the correct code though!

Can you double check that your `content` configuration is correct and that it covers the file where you're using this code?

https://tailwindcss.com/docs/content-configuration

If that all looks good, can you provide a reproduction project we can clone down and take a look at?

**Comment by DionneChelini** [comment]
Hey Adam, yeah the code being copied in my video is directly copied from tailwindui kit.  Here is my content configuration. 
```
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
```
Are you not getting the same result as I when copying the component into a project? I can reproduce and something I can probably look to provide over the.weekend

**Comment by reinink** [comment]
Hey!

Going to close this one for now because we haven't heard back, but feel free to still share a minimal reproduction and we can have a closer look.

The `content` configuration that you provided looks right to me. I've even setup a new Next.js project with similar folders, but couldn't reproduce this. I was thinking that maybe the parentheses in the `[lang]` and `(public)` folders were potentially causing issues here, but apparently not.

Sorry, can't be more helpful than that without a reproduction 👍
