### ISSUE TITLE
`Simple toggle` example is not showing a toggle

### ISSUE THREAD

**Issue by eRuaro** [tailwindlabs/tailwindui-issues#1557]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/toggles
- Component name: Simple Toggle

**Describe the bug**
What's being shown on the preview is different from what I'm seeing on my screen.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/forms/toggles
2. Copy the code for `Simple Toggle`
3. Paste code in your own editor
4. Check browser to see the UI

**Expected behavior**
The same toggle that's shown on tailwind UI will be shown in my app.

**Screenshots**

1. Here's the screenshot on tailwind UI
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/69240261/9a4ff333-ead2-4fb7-8c4e-ca270f8af6fe)

2. Here's the screenshot on my app
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/69240261/956e3f61-c616-4058-819d-984a10d411ec)

**Browser/Device (if applicable)**
 - OS: WSL, Windows
 - Browser chrome, safari

**Additional context**
Here's the code for the specific component:
```
import { useState } from "react";
import { Switch } from "@headlessui/react";

function classNames(...classes) {
	return classes.filter(Boolean).join(" ");
}

export default function UpgradeAccount() {
	const [enabled, setEnabled] = useState(true);

	return (
		<div className="isolate bg-white py-24 sm:py-32">
			<div className="mx-auto max-w-7xl px-6 lg:px-8">
				<div className="mx-auto max-w-4xl text-center">
					<p className="mt-2 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
						Time to upgrade your plan
					</p>
				</div>
				<p className="mx-auto mt-6 max-w-2xl text-center text-lg leading-8 text-gray-600">
					Small Investment. Huge Returns.
				</p>

				<Switch
					checked={enabled}
					onChange={setEnabled}
					className={classNames(
						enabled ? "bg-indigo-600" : "bg-gray-200",
						"relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2"
					)}
				>
					<span className="sr-only">Use setting</span>
					<span
						aria-hidden="true"
						className={classNames(
							enabled ? "translate-x-5" : "translate-x-0",
							"pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out"
						)}
					/>
				</Switch>

			</div>
		</div>
	);
}
```

Copying in examples from headless UI directly shows the same issue as well.

**Comment by eRuaro** [comment]
Changing the height and width associated with the `Switch` component fixes the UI not looking the same. But now I'm stumbling into the `span` not moving when `enabled` is changed

**Comment by RobinMalfait** [comment]
Hey!

Pasting this directly in CodeSandbox without any changes works fine: https://codesandbox.io/p/devbox/exciting-galois-mcfr5h?file=%2Fsrc%2FApp.jsx

So I'm guessing that there is something wrong with the setup of your project, a few potential issues that come to mind:
- It could be that Tailwind itself in your project isn't setup correctly. E.g.: the file you are pasting this in isn't covered by the `content` configuration. More info about that: https://tailwindcss.com/docs/content-configuration
- It could be that you are using some browser extension that injects custom styles or edits the DOM.
- You have other stylesheets loaded that make your site look like this.

If it's not caused by any of these, could you create a minimal reproduction repo and share that with us so that we can take a look at what's going on exactly?

Hope this helps!

**Comment by eRuaro** [comment]
Ah yup, got it fixed now, thanks!

Turns out I don't have `ts` and `tsx` files in my `tailwind.config.js`
