### ISSUE TITLE
[Catalyst] [type='*'] missing

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#1561]
Hi,
I'm using Tailwind CSS 3.4.1

I see that when I focus a field on Catalyst, I do not have the following styles, although I have them on my local site. Is this normal?
![focus](https://github.com/tailwindlabs/tailwindui-issues/assets/12116264/117f74ac-8e60-4190-96c7-6d1986a3fcd2)

**Comment by reinink** [comment]
Hey! Happy to help out here, just not 100% clear on what you're saying. What styles are you seeing locally that you're not seeing elsewhere? Where specifically are you not seeing them?

The only thing I can guess is that you're maybe looking on a mobile device and not seeing the focus styles. If that's true, that's because we intentionally don't show the focus input styles on mobile screen sizes, as this is consistent with how native mobile UIs behave.

If you look in the `src/components/input.tsx` file on line 28, you'll see this:

```js
// Focus ring
'after:pointer-events-none after:absolute after:inset-0 after:rounded-lg after:ring-inset after:ring-transparent sm:after:focus-within:ring-2 sm:after:focus-within:ring-blue-500',
```

Notice here how we're only adding the focus styles on `sm` screens and larger.

If you'd like to see these on mobile, you can easily update Catalyst to do this, just remove the `sm:` variant:

```diff
  // Focus ring
- 'after:pointer-events-none after:absolute after:inset-0 after:rounded-lg after:ring-inset after:ring-transparent sm:after:focus-within:ring-2 sm:after:focus-within:ring-blue-500',
+ 'after:pointer-events-none after:absolute after:inset-0 after:rounded-lg after:ring-inset after:ring-transparent after:focus-within:ring-2 after:focus-within:ring-blue-500',
```

If you do this, you'll probably want to update the input, listbox, select, and textarea components, just to be consistent.

Does that answer your question?

**Comment by seb-jean** [comment]
It's probably because I use the `tailwindcss/forms` plugin in my project.

**Comment by reinink** [comment]
Ahh yes, that's it. You're not going to want to use the `@tailwindcss/forms` plugin with Catalyst — it's not required by Catalyst and will cause issues if you do include it 👍
