### ISSUE TITLE
Spotlight template doesn't load mdx files when deployed to Vercel

### ISSUE THREAD

**Issue by KitsonBroadhurst** [tailwindlabs/tailwindui-issues#1562]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/spotlight
- Component name: Spotlight template

**Describe the bug**
MDX files are not loading on the spotlight template when deployed to vercel.

I was adapting the Spotlight template and running into issues loading mdx files in my setup. I assumed the issue was my implementation, but when deploying the base template I'm seeing the same issue.

**To Reproduce**
1. Download the ts version of the spotlight template
2. Create a github repo and pus the code there
3. Deploy the repo to Vercel
4. See the error: https://tailwindui-spotlight-6xbhymgt2-kitson.vercel.app/articles

**Expected behavior**
I expect to see the articles load as per the live demo: https://spotlight.tailwindui.com/

**Screenshots**
<img width="1089" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/8405069/2d36c3a9-1d28-4fc2-9405-7a5477f8707f">

**Additional context**
I downloaded the template last week, maybe Monday 11th March 2024

**Comment by KitsonBroadhurst** [comment]
The problem isn't Vercel specific - same default codebase deployed to Netlify: https://stupendous-fox-09912e.netlify.app/articles

**Comment by reinink** [comment]
Hey! So we host https://spotlight.tailwindui.com on Vercel, so it definitely should work. And just to make sure, I just deployed both the JavaScript and TypeScript versions to Vercel, and they deployed without any issues:

https://spotlight-js-alpha.vercel.app/

Just to confirm, are you saying that you downloaded and deployed the template to Vercel without any changes, and it failed to build properly?

Kind of stuck on this one — can you provide any extra information?

**Comment by KitsonBroadhurst** [comment]
I've deleted, re-downloaded and re-deployed the base template and this time it works!
 
 I'm also at a loss as to why I can't get the template to work in another format, but it seems it's an issue on my side somehow. Closing thanks for helping

**Comment by KitsonBroadhurst** [comment]
For anyone who ends up here due to an issue loading mdx files with next app router, it seems there is an open issue relating to the `searchParams` variable: https://github.com/vercel/next.js/issues/54804

**Comment by reinink** [comment]
@KitsonBroadhurst Got you got it figured out! 👍

**Comment by reinink** [comment]
Hey there! So I think I finally got to the bottom of this 😅

By default Next.js automatically purges all files it deems unnecessary for production builds (learn more [here](https://vercel.com/guides/how-can-i-use-files-in-serverless-functions)), and since the MDX files included in the Spotlight template aren't needed after the initial build (at least from what Next.js and Vercel can tell), they aren't included in the production artifacts.

The way to (apparently) solve this is using the experimental `outputFileTracingIncludes` option to explicitly tell Next.js to keep certain files around in the production build.

To fix this in the Spotlight template, update your `next.config.mjs` file to include the following:

```diff
  /** @type {import('next').NextConfig} */
  const nextConfig = {
    pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'mdx'],
+   experimental: {
+     outputFileTracingIncludes: {
+       '/articles/*': ['./src/app/articles/**/*.mdx'],
+     },
+   },
  }
```

Alternatively, you can just re-download this file from the Tailwind UI website.

That should fix it! 🤞

**Comment by reinink** [comment]
> Thanks for this comment ! Note : it's not experimental anymore in 2025. https://nextjs.org/docs/pages/api-reference/config/next-config-js/output#caveats

@laem hey thanks for the heads up on that! 🙏
