### ISSUE TITLE
Week View Component's Header Does Not Scroll as Expected

### ISSUE THREAD

**Issue by cantutar** [tailwindlabs/tailwindui-issues#1565]
**What component (if applicable)**
- URL for category: [Week View Component](https://tailwindui.com/components/application-ui/data-display/calendars)
- Component name: Week view

**Describe the bug**
Upon integrating the Week View component from Tailwind UI into our project, the expected functionality for the header to scroll both horizontally and vertically with the page content was not observed. The issue persists across both our main and test projects, indicating a broader compatibility or implementation issue. This behavior diverges from the advertised functionality on the component's documentation page.

**To Reproduce**
1. Copy and paste the provided template for the Week View component into a fresh React project set up with Vite and SWC.
2. Observe the behavior of the header in the context of page scrolling.

**Expected behavior**
The header of the Week View component should scroll both horizontally and vertically, maintaining its position relative to the viewport as illustrated on the Tailwind UI documentation page. This ensures a consistent and accessible user experience across different sections of the calendar.

**Actual Behavior:**
The header does not adhere to its expected behavior of scrolling in both directions. Instead, it remains static, not adjusting to scroll actions, which leads to a disjointed user experience.
**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/43760169/32501cca-66a0-438b-95f8-6054bd29cbca)
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/43760169/055762a3-9779-41bb-8f68-38b9afb7c352)

**Browser/Device (if applicable)**
 - OS: Windows 11
 - Browsers Tested: Chrome 123, Firefox 125

**Additional context**
The issue was initially identified during routine development work, prompting a series of tests across different projects and browsers to ascertain the scope and impact. A minimal test environment was created using a fresh Vite + SWC project to eliminate potential conflicts or external influences, confirming the issue's reproducibility.

Main Project: React + SWC, TSX
Test Project: React + SWC, JSX

**Comment by adamwathan** [comment]
Hey thanks for the report! So for the header in the week view calendar to stick, you need to make sure you are putting the calendar inside of an element that has a defined height, otherwise the page is going to just expand to fit he whole calendar which will prevent the overflow from happening that causes the sticky header to trigger.

For example:

```html
<div class="h-[768px]">
  <!-- Paste calendar here -->
</div>
```

You can use utilities like [`h-dvh`](https://tailwindcss.com/docs/height#dynamic-viewport-height) to make it the height of the screen if you want it to be full height 👍 

We should improve the instructions for this component and add a comment to the top of the code explaining this, so going to leave this open until we have a chance to do that.

Hope that helps.
