### ISSUE TITLE
Pricing page contains "Lorem Ipsum" texts

### ISSUE THREAD

**Issue by Can-Sahin** [tailwindlabs/tailwindui-issues#1568]
URL: https://tailwindui.com/components/marketing/sections/pricing

<img width="1367" alt="Screenshot 2024-04-08 at 20 23 39" src="https://github.com/tailwindlabs/tailwindui-issues/assets/33245689/9e46087c-bf66-4300-b873-2aa60e77b210">

**Comment by adamwathan** [comment]
Hey! Yeah this is intentional — basically every component in Tailwind UI uses lorem ipsum placeholder text because you are meant to replace it with whatever makes sense for your project 👍 

<img width="1393" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/046442db-2a08-4c03-8590-67f7177b56ed">

<img width="1381" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/a31aa56c-81b8-4376-87bf-cb02bf5f6f5e">

<img width="1397" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/93bdd8f4-4c2a-4772-9fef-3033f16e7699">

**Comment by Can-Sahin** [comment]
oh wow. Thats unexpected :) Thanks

**Comment by Can-Sahin** [comment]
For feedback, I just realized its the components page. If you google 'tailwindui pricing' it comes up first and makes me think that its the actual pricing info.

**Comment by adamwathan** [comment]
> For feedback, I just realized its the components page. If you google 'tailwindui pricing' it comes up first and makes me think that its the actual pricing info.

Ah that's a good catch, we can improve that! Thank you 👊🏻
