### ISSUE TITLE
clsx misuse in Catalyst — className functions don't work

### ISSUE THREAD

**Issue by Benjamin-Dobell** [tailwindlabs/tailwindui-issues#1571]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs
- Component name: Alert, Badge, Button, Checkbox etc. Most components, except maybe Avatar?

**Describe the bug**
All components that make use of `clsx` will silently fail to apply class names if you provide a `className` that is a function taking render args.

**To Reproduce**
1. Grab the latest Catalyst zip at the time of writing. Add it to any project. 
2. Create a component with a `className` that is a function:
  ```
  <Button className={({ active }) =>  active ? 'drop-shadow-2xl' : ''}>
     Hi
  </Button>
  ```
4. Interact with the component (in this case click) and note that the tailwind classes have not been applied.

**Expected behavior**
In the example above, when you click the button you should see a large drop shadow appear.

**Additional context**
The issue is `clsx` does not support classNames as render functions. They're a Headless UI thing so it's understandable. What's not great is the fact the current Catalyst source makes it past TypeScript's type checker. Sadly, clsx simply has really poor types:

https://github.com/lukeed/clsx/blob/master/clsx.d.ts#L3

Basically they accept `Record<string, any>`, which a function is:

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAggIgSwMbAQewHYEMBOIBKCA5gBbBQC8U+ESaOAJgDwDOwOCGRANFFhiAB8AKGF0MbKAHccmIgC5YiFOmx5CpclQAUASkqCo4lmgA2EAHSm0RbQHIsUqXd3CgA

_Anyway_, the correct solution is for Catalyst to provide its own class merging functionality that is render arg function aware e.g.

```tsx
import { ClassNameValue as TWMergeClassNameValue, twMerge } from 'tailwind-merge'

type ClassNameValue<T> = ClassNameArray<T> | TWMergeClassNameValue | ((renderArgs: T) => string)
type ClassNameArray<T> = ClassNameValue<T>[]

const isSimpleClassList = (className: ClassNameValue<any>): className is TWMergeClassNameValue =>
  Array.isArray(className)
    ? className.find((nestedClassName) => !isSimpleClassList(nestedClassName)) === undefined
    : typeof className !== 'function'

const resolveClassNames = <T>(renderArgs: T, className: ClassNameValue<T>): TWMergeClassNameValue =>
  Array.isArray(className)
    ? className.map((nestedClassName) => resolveClassNames(renderArgs, nestedClassName))
    : typeof className === 'function'
      ? className(renderArgs)
      : className

export function classMerge(...classLists: TWMergeClassNameValue[]): string
export function classMerge<T>(...classLists: ClassNameArray<T>): ((renderArgs: T) => string)
export function classMerge<T>(...classLists: ClassNameArray<T>): string | ((renderArgs: T) => string) {
  return isSimpleClassList(classLists)
    ? twMerge(classLists)
    : renderArgs => twMerge(resolveClassNames(renderArgs, classLists))
}
```

A few things to note about this implementation:
1. I've used tailwind-merge instead of clsx. It's just a personal preference. I'm not expecting Catalyst to swap.
2. The types and usage of `isSimpleClassList` are very intentional. The implementation would no doubt be simpler if we just always return a function. _However,_ if we do that then we're going to run afoul of server side components i.e. every component would need to be converted to 'use client'. I suppose, it's not a _huge_ issue since Headless UI components are for the most part client-side. Still, best to push the client-side boundary as deep down as possible.
3. A quick search and replace of `clsx` with `classMerge` won't get us to where we need to be. However, since we've real types at this point, the problems become much more apparent. Components like `Textarea` for example are applying the `className` on the wrapper span, but `span` doesn't accept a function for `className`. This does highlight some potential design issues with Headless UI itself, but they're largely out of scope as far as this issue is concerned.

One potential annoyance here is that currently Catalyst is component only. That's nice and makes it easy to drop in. However, as a result it's not strictly clear where this utility function ought to belong. Honestly, I'm skeptical that Catalyst ought to remain _just_ components — what if you need a hook in the future? — but still, it's worth mentioning here. If the Tailwind team are dead set on Catalyst remaining component only then `classMerge` (or some similar implementation) could be pushed to an NPM package. Putting it in `@headlessui/react` itself is certainly an option, but I imagine you want to avoid the `clsx` dependency — it'd also make it very difficult for consumers to swap out clsx. Including the utility function in Catalyst would provide the most flexibility for consumers.

**Comment by reinink** [comment]
Hey @Benjamin-Dobell! Thanks for sharing this. You're absolutely right, our `className` types are incorrectly showing the render function right now.

This is because we're using the types exposed by Headless UI in a bunch of our components, and since the `className` type in Headless UI includes the render function it's getting passed on to the Catalyst components.

We're working on a pretty significant update to Catalyst at the moment (that adds application layouts and some other components), and I've already corrected these types in that branch — so stayed tuned for that release for our fix to this.

For a bunch of the `className` props we're actually applying it to a wrapper element and not the Headless UI components themselves, so in those cases the render function won't work. Given that, I opted to simply omit the render function from the types by doing this:

```diff
- export function CheckboxField({ className, ...props }: HeadlessFieldProps) {
+ export function CheckboxField({ className, ...props }: { className?: string } & Omit<HeadlessFieldProps, 'className'>) {
```

Plus, as of Headless UI v2.0 the render function isn't really necessary any longer since you can use the new `data-*` attributes to conditionally apply styles to your components. This is what we've done throughout the Catalyst components, as I'm sure you've noticed.

Of course you're welcome to do something different in your own project — feel free to modify your components however you prefer to handle things.

Thanks again for reporting this! 🤙
