### ISSUE TITLE
Shadow in new Catalyst template

### ISSUE THREAD

**Issue by shavonn** [tailwindlabs/tailwindui-issues#1592]
**What Template**
- Template demo: https://catalyst.tailwindui.com/demos/stacked
- Component name: NavbarItem

**Describe the bug**
A shadow appears on the TeamDropdown when the first menu item has the **current** page default styling. 

**To Reproduce**
1. Go to the first NavbarItem link
2. Click on the Team Dropdown (Tailwind Labs on this page)
3. See the shadow in the upper right corner

**Expected behavior**
I would expect it to appear as it does when any other NavbarItem is current. There is no shadow there.

**Screenshots**
<img width="291" alt="Screenshot 2024-06-01 at 10 54 36 AM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/3074595/ccdc2749-395d-4e6a-8413-87b01273ad72">

First item current, shadow showing on dropdown

<img width="371" alt="Screenshot 2024-06-01 at 10 44 12 AM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/3074595/d2a34239-3669-4915-9314-367942afe2bc">
Second item current, no shadow showing on dropdown

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser Chrome
 - Version 125.0.6422.114

It doesn't look as noticeable in the screenshot as it does when I see it live. 😂

**Comment by RobinMalfait** [comment]
Hey!

This is done on purpose, the dropdown has a background with an opacity and with a backdrop blur present such that you can see that something is behind it. The little shadow you see is coming from the underline that is seen on the `Home` tab.  When the `Events` tab is active, then you don't see it because the black underline is not directly underneath the dropdown.

If you don't like this behavior, then you can update the `DropdownMenu` component to get rid of it:

```diff
  // Popover background
- 'bg-white/75 backdrop-blur-xl dark:bg-zinc-800/75',
+ 'bg-white dark:bg-zinc-800',
```

The result looks like this:
<img width="282" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/1834413/ba3c7d64-b8c2-4ff4-b0bd-1298ae2f8112">

Hope this helps!
