### ISSUE TITLE
Catalyst: Listbox component

### ISSUE THREAD

**Issue by fouteox** [tailwindlabs/tailwindui-issues#1603]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs/listbox
- Component name: Listbox

**Describe the bug**
Switching from desktop to mobile screen causes some sort of state loss, see video

**To Reproduce**
See video

**Expected behavior**
I do not really know

**Screenshots**

https://github.com/tailwindlabs/tailwindui-issues/assets/88294294/ca04d225-e169-4ee6-a503-0b06341a4f6d

**Browser/Device (if applicable)**
 - OS: Mac OS (but all I think)
 - Browser Firefox and Safari
 - Version 127 for firefox and latest for safari

**Comment by reinink** [comment]
Hey there! Really sorry for the long delay on this one. This issue was caused by an bug in Headless UI, see here: https://github.com/tailwindlabs/headlessui/pull/3466

Good news though, we got this fixed and released today! To fix this in your app, upgrade to the latest version of Headless UI:

```sh
npm install @headlessui/react@latest
```

Hope that helps, and apologies again for the delay.
