### ISSUE TITLE
Docs: Ability to click and copy the colors

### ISSUE THREAD

**Issue by ivosabev** [tailwindlabs/tailwindui-issues#161]
This would be a small nice-to-have feature to to have the ability to click on the colors and get a copy with their class name or at least on hover. Easiest fix would be to add `title` attribute and let the browser handle it.

https://tailwindui.com/documentation#how-tailwindcss-ui-extends-tailwind

**Comment by simonswiss** [comment]
Hey, good suggestion.

There may be better implementations, but since we're pushing a few important projects forward, I can't justify making this a priority.

For now I have added a title attribute to the color swatches, as you suggested, so you can see what color it it on hover.

That should be already helpful! 👍
