### ISSUE TITLE
Catalyst Input & Button component glitches within Dialog component

### ISSUE THREAD

**Issue by sahebyuvrajsingh** [tailwindlabs/tailwindui-issues#1618]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/catalyst
- Component name: Input, Button
- Framework: React

**Describe the bug**
When the above-mentioned components are used in the Dialog component, the component's height shifts and glitches. I think it's due to the calc function used within the inline class as mentioned alongside, `px-[calc(theme(spacing[3.5])-1px)] py-[calc(theme(spacing[2.5])-1px)]`.

**Screenshots**
![Catalyst Input   Button Glitch In Dialog](https://github.com/user-attachments/assets/fab20e4c-cd63-40f7-a59d-de99766d5cee)

**Comment by reinink** [comment]
Hey! Thanks so much for reporting this issue.

So the problem here is that we need to include the `will-change-transform` class to basically instruct the browser to prepare for an upcoming animation.

I've just deployed a fix for this, so you're welcome to re-download the components from the Tailwind UI website, or you can just apply the following fix to the `dialog.tsx` and `alert.tsx` files on line 42:

```diff
- 'transition duration-100 data-[closed]:data-[enter]:scale-95 data-[closed]:opacity-0 data-[enter]:ease-out data-[leave]:ease-in'
+ 'transition duration-100 will-change-transform data-[closed]:data-[enter]:scale-95 data-[closed]:opacity-0 data-[enter]:ease-out data-[leave]:ease-in'
```

Hope that helps! 🤙

**Comment by sahebyuvrajsingh** [comment]
@reinink Excellent, its working great now thanks a lot! 💯

**Comment by reinink** [comment]
@sahebyuvrajsingh Amazing, glad that solved it for you! 🙌
