### ISSUE TITLE
[Catalyst] Navbar misaligns items if checkbox or switch components are used as Dropdown items

### ISSUE THREAD

**Issue by haltsir** [tailwindlabs/tailwindui-issues#1626]
**What component (if applicable)**
- Component name: Navbar, Dropdown, related components

**Describe the bug**
I have a Navbar with a logo dropdown, as in the examples. In the DropdownMenu, inside DropdownItem, instead of the company names in the example, I'm trying to use a CheckboxField component. Inside of it are the usual Checkbox and Label components. However if I do that the top Settings menu item and the bottom New team item are being offset, starting from where the longest CheckboxField ends. I tried putting the CheckboxField inside of a DropdownLabel component, and the top and bottom components are back to normal, but now the checkbox components are indented.

**To Reproduce**
Just use code from the examples and put checkbox/switch components in the Navbar Dropdown.

**Expected behavior**
I expect for the checkbox/switch components to be aligned with the rest of the menu items, as per the examples.

**Screenshots**
<img width="308" alt="Screenshot 2024-09-04 at 20 49 18" src="https://github.com/user-attachments/assets/acf8aa00-a5ab-4d29-8e19-377221c14b23">

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Firefox
 - Version: 129.0.2

**Additional context**
N/A

**Comment by reinink** [comment]
Hey! Unfortunately our `Dropdown` component wasn't designed to support either the `Checkbox` or `Toggle` components in the icon column. Sorry about that!

I agree that this would be nice to have, but the challenge here is that the `Switch` component is too wide to work alongside other icons, should you have them.

That said, you might be able to make the `Checkbox` work, since it's the same size as the icons (16px by 16px). To do this wrap the checkbox in a `<div>` with the `data-slot` attribute set to `icon`. Something like this:

```js

import * as Headless from '@headlessui/react'
import { Checkbox } from '@/components/checkbox'
import { DropdownItem, DropdownLabel } from '@/components/dropdown'

<Headless.Field as={DropdownItem}>
  <div data-slot="icon" className="flex items-center">
    <Checkbox aria-label="Allow embedding" name="allow_embedding" />
  </div>
  <DropdownLabel>Allow embedding</DropdownLabel>
</Headless.Field>
```

Notice how I also had to use the `Headless.Field` component, rendered as a `DropdownItem`.

I just gave this a try and here's the result I get:

<kbd><img width="444" alt="image" src="https://github.com/user-attachments/assets/dc178c3d-483a-4355-93f1-3eb9ddf2fd79"></kbd>

Fair warning — while this mostly works from my testing, it wasn't designed to be used this way, so I'm not 100% sure everything is going to be correct from an accessibility perspective.

Maybe some day we can look at officially supporting these components in this way 👍
