### ISSUE TITLE
Setting the defaultOpen prop of sidebar's Disclosure component to true results in a rules-of-hooks error

### ISSUE THREAD

**Issue by seanpcoyle** [tailwindlabs/tailwindui-issues#1627]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/sidebar-navigation
- Component name: [With secondary navigation](https://tailwindui.com/components/application-ui/navigation/sidebar-navigation#component-ea2064949c1427bc69284e1713dbbd6d)

**Describe the bug**
When setting the `defaultOpen` prop of `Disclosure` to true, the rules of hooks are violated.

```
   Previous render            Next render
   ------------------------------------------------------
1. useId                      useId
2. useContext                 useContext
3. useContext                 useContext
4. useRef                     useRef
5. useRef                     useRef
6. useLayoutEffect            useEffect
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**
1. In the provided example, set the `defaultOpen` prop of `Disclosure` to true

**Comment by reinink** [comment]
Hey! So I think you found a bug in Headless UI, the library used for the disclosure in this example. The issue seems to be the fact that we're using a `DisclosureButton` within the `DisclosurePanel`.

This should work — it's used this way so that the disclosure closes when you click a link. Now that may, or may not be what you want, so I'm going to show you two ways to solve this.

### Close on click

As of Headless UI v2.0, we introduced a new `CloseButton` component that you can use to close the disclosure. Here's how to do that:

```diff
+ import { CloseButton } from '@headlessui/react'

- <DisclosureButton
+ <CloseButton
    href={subItem.href}
    className={classNames(
      subItem.current ? 'bg-gray-50' : 'hover:bg-gray-50',
      'block rounded-md py-2 pl-9 pr-2 text-sm leading-6 text-gray-700',
    )}
  >
    {subItem.name}
+ </CloseButton>
- </DisclosureButton>
```

### Remain open on click

However, if you'd prefer the disclosure to stay open when you click a link, you can just use a plain `<a>`:

```diff
- <DisclosureButton
-   as="a"
+ <a
    href={subItem.href}
    className={classNames(
      subItem.current ? 'bg-gray-50' : 'hover:bg-gray-50',
      'block rounded-md py-2 pl-9 pr-2 text-sm leading-6 text-gray-700',
    )}
  >
    {subItem.name}
+ </a>
- </DisclosureButton>
```

If you're using Next.js, or some other client-side router, you can, of course, use the `Link` component here as well.

---

Hope that helps! I'm going to record this bug internally either way for us to look at, since as mentioned, using the `DisclosureButton` this way should work 👍

**Comment by seanpcoyle** [comment]
Awesome - thanks a bunch for the detailed response. Exactly the question I was looking to have answered.
