### ISSUE TITLE
[catalyst feature requests] cards, theme switcher, floating labels

### ISSUE THREAD

**Issue by kjjd84** [tailwindlabs/tailwindui-issues#1630]
this repo said its for feature requests, so here are some of mine for catalyst:

# cards

similar to: https://tailwindui.com/components/application-ui/layout/cards

would be sweet to have this baked into catalyst - header, body, footer, etc.

# theme switcher

similar to: https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection

a button or something to switch the theme and have it stay in local storage would be nice

# floating label

similar to: https://flowbite.com/docs/forms/floating-label/

a bonus would be if it works with empty selects, as I haven't found many ui libs that can do this

thanks for your time & consideration

**Comment by reinink** [comment]
Hey @kjjd84! So these days this repo is now only used for reporting bugs discovered in Tailwind UI, not a place to submit feature request ideas. We used to have the GitHub Discussions feature enabled in this repo for this purpose, but we decided to rid of it because it was setting the wrong expectations (see [here](https://github.com/tailwindlabs/tailwindui-issues/issues/1408#issuecomment-1406325333)).

That said though, you're absolutely right, the repo description still said "feature request tracking" in it — sorry about that! I've updated it to "A place to report bugs discovered in Tailwind UI."

That all said, thanks for sharing these ideas. We'll definitely keep these in mind as we consider future updates to the product.

Thanks for being a Tailwind Ui customer! 🙌
