### ISSUE TITLE
Support for React 19 / NextJS 15

### ISSUE THREAD

**Issue by leebenson** [tailwindlabs/tailwindui-issues#1642]
**What component (if applicable)**

Catalyst UI kit

**Describe the bug**

Curious if you have an ETA for React 19 / NextJS 15 support for the Catalyst UI kit please?

There have been a number of changes, including the removal of `forwardRef` and type changes, that are currently preventing adopting React 19.

HeadlessUI released v2.2 yesterday which now supports React 19.

Thank you.

**Comment by harrybawsac** [comment]
For example, `motion.span` now gives an error saying `className` is not a property.

**Comment by reinink** [comment]
@leebenson Hey! So Catalyst should already work with React 19 — I've tested it myself and it seems to work without any issues. While React 19 has removed the need for `forwardRef`, it still exists for backwards compatibility, so that shouldn't be an issue.

Even the release we made to Headless UI last week (v2.2) was mostly just a change to suppress a React warning that Next.js v15 was showing as an error — even before that change Catalyst should have still worked with React 19.

What specifically isn't working for you?

@harrybawsac What React types package are you using? I know that Next.js v15 is still using the React 18 types.

**Comment by harrybawsac** [comment]
I'm using the React 19 types.

**Comment by reinink** [comment]
@harrybawsac Thanks for sharing that! It looks like if you want to use Catalyst with React 19 types, you'll also need to update to the latest Framer Motion alpha where they have been working on React 19 support:

https://github.com/framer/motion/issues/2843

Should be as easy as this:

```
npm install framer-motion@canary --force
```

Once React 19 is actually released we'll make sure to publish a Catalyst update that has it in there by default. Right now is sort of a weird time where React 19 isn't stable but the latest stable version of Next is using it anyways so it's creating a bit of disruption in the ecosystem :/
