### ISSUE TITLE
Usability enhancements to headers and flyout menus

### ISSUE THREAD

**Issue by connecteev** [tailwindlabs/tailwindui-issues#191]
**What component (if applicable)**
- URL for category: 
https://tailwindui.com/components/marketing/elements/headers
https://tailwindui.com/components/marketing/elements/flyout-menus
- Component name: All Headers and FlyOut menus

**Describe the bug**
This is more of an enhancement, but it would greatly improve the accessibility of headers and flyout menus

**Expected behavior**
1. When the flyout menu is open: 
- the caret icon could change direction (point up versus point down all the time)
- the active menu item could have a different styling or color

2. The flyout menu should close when you click anywhere outside. You shouldn't have to click on the exact menu link again to cause it to close.

3. Please consider an option to trigger / open the flyout menu on hover instead of click.

Thanks for tailwindui and for considering this.

**Comment by simonswiss** [comment]
Those are good suggestions! 👍

I have captured them in the list of things to do. I cannot give you a time estimate on when this will be available due to other, more important priorities.

So, maybe not now, but definitely going to implement this in the future for those fly-out menu examples, and other places where you can't "exit" in any other way than clicking in a specific location.
