### ISSUE TITLE
Appearance is not supported in all browsers

### ISSUE THREAD

**Issue by parker-codes** [tailwindlabs/tailwindui-issues#237]
- URL for category: https://tailwindui.com/components/application-ui/forms/select-menus

It looks like the form-select class uses `appearance: none;`, which does not work on Firefox (and perhaps not webkit-based browsers), so I'm seeing the native dropdown *on top of* the neat SVG icon. There is no such thing as appearance, but there is `-webkit-appearance` and `-moz-appearance`. Firefox uses either one of those variations, but I'm not sure about other browsers. 

Autoprefixer DOES handle this, but I think it would be nice to have it work without that.

**To Reproduce**
1. Go to the select menus page in Firefox
2. Use the devtools to remove the moz and webkit variations from .form-select
3. See that the native icon appears

I think handling these variations directly, without autoprefixer, would be great.

![image](https://user-images.githubusercontent.com/17652149/86304589-1fd10e80-bbc4-11ea-88d5-076692afa00e.png)

**Browser/Device (if applicable)**
 - OS: Windows 10
 - Firefox Developer Edition
 - Version 79.0b2

**Additional context**
I realize that this might be changed upstream in TailwindCSS itself.

**Comment by simonswiss** [comment]
Tailwind CSS is pretty straightforward about [recommending including autoprefixer](https://tailwindcss.com/docs/browser-support/#vendor-prefixes), and all the examples everywhere of how to use Tailwind contain the `require('autoprefixer')` in the plugins array.

I don't think this is going to change, since Tailwind itself is built on PostCSS, so adding the autoprefixer plugin doesn't add "baggage" to using Tailwind.
