### ISSUE TITLE
Form input focus colors are wrong

### ISSUE THREAD

**Issue by aerni** [tailwindlabs/tailwindui-issues#238]
**What component (if applicable)**
Any form elements using the `@tailwindcss/custom-forms` plugin.

**Describe the bug**
The focus color of any form element uses the Tailwind CSS shadow and border color.

**Expected behavior**
It should extend the Tailwind UI color palette.

Example:
In Tailwind UI the class `shadow-outline` has `box-shadow: 0 0 0 3px rgba(118, 169, 250, 0.45)`
In Tailwind CSS the class `shadow-outline` has `box-shadow: 0 0 0 3px rgba(66, 153, 225, 0.5)`

Any form element should use the `box-shadow` that comes with Tailwind UI. Also, the focus `border-color` should be the same.

**Comment by simonswiss** [comment]
It's actually an intentional decision to use the default "blue" focus color on form elements rather than the coloured `shadow-outline` and `border`, as you can see in this screenshot.

![image](https://user-images.githubusercontent.com/485747/89847198-abc45600-dbc6-11ea-899a-32b426e80474.png)

Nothing stops you from changing it in your implementation to be "on brand", but in Tailwind UI, the decision was to make these keep the default blue on form elements.
