### ISSUE TITLE
Source code Javascript components available? 

### ISSUE THREAD

**Issue by smeedijzer-internet** [tailwindlabs/tailwindui-issues#286]
Hi,

I see that 'Select Menus: Custom with avatar' on https://tailwindui.com/components/application-ui/forms/select-menus uses Alpinejs. Is the unminified source code of /js/iframe.js available?

**Comment by Braunson** [comment]
@smeedijzer-internet I believe @adamwathan mentioned this a while back about it being added back to the site at some point in the future.

For now @KevinBatdorf [in this thread](https://github.com/tailwindlabs/tailwindui-issues/issues/183) has a nice workaround using the TaperMonkey extension for your browser.

**Comment by simonswiss** [comment]
Hey! 👋

We don't share the JS code in the examples because some implementations are more geared towards an interactive demo than a production ready, battle tested JavaScript implementation, as mentioned in the docs.

We are working on React, Vue and potentially AlpineJS versions of the component output in the future.
