### ISSUE TITLE
Breakpoints with multiple app shells (with & without sidebar)

### ISSUE THREAD

**Issue by dan-kwiat** [tailwindlabs/tailwindui-issues#291]
Are there any thoughts on how to deal with breakpoints on sites with multiple application shells?

The config option `layout: 'sidebar'` accounts for the reduced width in a sidebar layout but messes with the breakpoints on pages without a sidebar.

Example use case: home page is used for marketing (no sidebar) but the route `/app` uses a sidebar layout.

**Comment by simonswiss** [comment]
Hy @dan-kwiat 👋

Thanks for reaching out. There is a discussion thread with this specific topic: https://github.com/tailwindlabs/tailwindcss/discussions/2200

You're not the first one to point that scenario out, so this is something we might look at improving, or at least come up with a recommendation on how to handle multi-layout apps.

We have captured this internally already. I encourage you to join the discussion thread linked above, which is where we'll publicly keep track of this request. 👍

**Comment by dan-kwiat** [comment]
Thanks, I didn't see that. For now I've decided to avoid the sidebar layout for this reason + reported issues on iOS.

**Comment by adamwathan** [comment]
Best bet is to create two separate CSS files, since there's no real way to support multiple breakpoint values in the same file based on the presence of a sidebar or not.

If it were me personally, I would just not use the sidebar config option at all and accept that I might need to adjust the breakpoints on certain components. For example if you try to stick a complex wide table or list component into the content area of a sidebar layout, it might not quite fit and you might need to take `lg:` utilities and bump them up to `xl:` sort of thing.

**Comment by dan-kwiat** [comment]
That sounds reasonable, thanks for the suggestion.

**Comment by simonswiss** [comment]
Going to close this, since there is [an existing related discussion thread](https://github.com/tailwindlabs/tailwindcss/discussions/2200).
