### ISSUE TITLE
Small input styling bug on section heading.

### ISSUE THREAD

**Issue by Oscarteg** [tailwindlabs/tailwindui-issues#295]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/headings/section-headings#component-df8f39d7313327ae424064d721e61dad
- Component name: Section Headings With input group

**Describe the bug**
The input is a pixel smaller than the sort button.

**Screenshots**
![image](https://user-images.githubusercontent.com/8656565/91385577-845dc200-e831-11ea-9d17-5b498b0e3c5e.png)

**Additional context**
I fixed it with adding a `h-full` on the search input. Not sure if that is the correct way.

**Comment by simonswiss** [comment]
Hey @Oscarteg 👋

Thanks for reporting this! What browser / OS are you using when this happens? 

If this happens on this component, it is likely to happen in other places as well, so I'd like to be able to reproduce it before fixing.

Just tried on Chrome / Firefox / Safari on MacOS, and it doesn't break like that.

Using `h-full` breaks the vertical alignment of the input text/placeholder in these browsers 😅 

If you give me more information, I'll try get it sorted 👍

**Comment by Oscarteg** [comment]
Sorry for the missing information. I am using the following:
 - OS: MacOS
 - Browser: Chrome
 - Version: 84.0.4147.135 

I didn't know that. Learned something new.

**Comment by simonswiss** [comment]
Thanks for that! 👍

Can you check if the same happens on this component (I assume so, since it's essentially the same)?

https://tailwindui.com/components/application-ui/forms/input-groups#component-a8d111fef35bfae4c800af505ea0d276

It looks fine on Chrome for me, but I can definitely see that if the button height is bigger (if I add some vertical padding in devtools), the search input breaks like on your example.

My first thought is to add the classes `flex items-stretch` to the element that wraps both the search icon and input(s).

That will make the input to use 100% of the parent height.

Here's an example of just that below, while I work on a proper fix in the various places where this component is used:

```html
<div>
  <label for="search_candidate" class="sr-only">Search</label>
  <div class="flex rounded-md shadow-sm">
    <div class="relative flex-grow flex items-stretch focus-within:z-10">
      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
        <x-heroicon type="solid" name="search" class="h-5 w-5 text-gray-400" />
      </div>
      <input id="search_candidate" class="form-input block w-full rounded-none rounded-l-md pl-10 transition ease-in-out duration-150 sm:hidden" placeholder="Search" />
      <input id="search_candidate" class="hidden form-input w-full rounded-none rounded-l-md pl-10 transition ease-in-out duration-150 sm:block sm:text-sm sm:leading-5" placeholder="Search candidates" />
    </div>
    <button class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-r-md text-gray-700 bg-gray-50 hover:text-gray-500 hover:bg-white focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-100 active:text-gray-700 transition ease-in-out duration-150">
      <x-heroicon type="solid" name="sort-ascending" class="h-5 w-5 text-gray-400" />
      <span class="ml-2">Sort</span>
      <x-heroicon type="solid" name="chevron-down" class="ml-2.5 -mr-1.5 h-5 w-5 text-gray-400" />
    </button>
  </div>
</div>
```

Your `h-full` class did the trick too, but for me it makes the text jump a few px down, where the `flex items-stretch` approach keeps it nicely aligned 👍

**Comment by Oscarteg** [comment]
@simonswiss So sorry for the late response. 

When I look at the input group in the link there is no issue. 

![image](https://user-images.githubusercontent.com/8656565/91992024-ef2c6300-ed33-11ea-8f6a-beb24bb95860.png)
