### ISSUE TITLE
Card heading button classes seem off

### ISSUE THREAD

**Issue by meanspa** [tailwindlabs/tailwindui-issues#303]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/headings/card-headings
- Component name: "With Action"

**Describe the bug**
The `rounded-md` and `shadow-sm` classes seem like they should be part of the button, not the span that contains it?

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/headings/card-headings
2. Click on `With Action`
3. View code
4. Look at the markup for the button

**Screenshots**
![image](https://user-images.githubusercontent.com/403478/91753809-463c0780-eb7d-11ea-9e60-e66ba87d4966.png)

**Comment by RobinMalfait** [comment]
This is not a bug this is done so that you could `stack` the shadows. Because if you look at the button itself there is a `focus:shadow-outline-indigo`. Which means if the button gets focus, this shadow will show, but the `shadow-sm` would be gone. The extra rounded is so that the shadow follows the button correctly.

**Comment by meanspa** [comment]
Ah I see, thanks for clarifying.
