### ISSUE TITLE
Different favicon for tailwindui

### ISSUE THREAD

**Issue by tim-kilian** [tailwindlabs/tailwindui-issues#304]
**Screenshots**
![image](https://user-images.githubusercontent.com/5788010/91797302-830e0a00-ec22-11ea-8abe-8e56c72139e2.png)
Screenshot of my pinned tab section.

**Additional context**
I can not distinguish which tab is tailwindui and which is tailwindcss. Tailwindui should have a different favicon than tailwindcss.

**Comment by simonswiss** [comment]
That's an interesting point! I have captured it internally and will raise it with the team.

Fun fact: I myself always open the wrong tab because I see 12 of these favicons in my chrome tabs 🤣

This is my chrome tabs right now:

![image](https://user-images.githubusercontent.com/485747/94881310-75a9a100-04a8-11eb-90a0-c8296e5e0e4e.png)

Will close this issue, but have captured this suggestion! Thank you 👍
