### ISSUE TITLE
JSX Copy

### ISSUE THREAD

**Issue by employee451** [tailwindlabs/tailwindui-issues#318]
It would be great to have the option to copy component code as JSX, like there is an option for this on heroicons.dev

**Comment by alexanderbluhm** [comment]
@employee451 This is in the pipeline I think! :) It takes a bit longer because they refactor the whole "copy code" thing. Adam's vision is to have tabs like React, Vue, etc. where you can copy the code.
In the time between you can use [this](https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676) to copy as JSX.

**Comment by alexanderbluhm** [comment]
#224

**Comment by simonswiss** [comment]
This is definitely in the pipeline! 👍

The React & Vue version of Tailwind UI components are in the making. It will take a little while to come out because of the various dependencies this project is relying on (release of Tailwind 2.0 being one of them).

But - it's definitely happening - stay tuned!

**Comment by karanchawla** [comment]
There's a chrome extension called Tailwind UI React that converts code snippets for components to JSX. https://chrome.google.com/webstore/detail/tailwind-ui-react/binfindfddkgfibeajgkmjioklcgigjn

**Comment by simonswiss** [comment]
Closing this issue now - tune in to follow the evolution of the [Headless UI](https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react) library which will power Tailwind UI's React (and Vue!) components in the future 👍
