### ISSUE TITLE
Toggle for React

### ISSUE THREAD

**Issue by ajonp** [tailwindlabs/tailwindui-issues#383]
**Screenshots**
Place a toggle so that comments switch from html 
`<!-- Solutions menu -->`
to jsx/tsx
`{/* <!-- Solutions menu --> */}`

And also changes `class` to `className`.

**Additional context**
This is out of pure laziness, but as a paying subscriber thought it was worth a feature request :D

**Comment by davidluhr** [comment]
@ajonp Thanks for the feedback!

While I understand the convenience this would provide for React, Tailwind UI needs to remain framework-agnostic because we can't predict what types of projects our users are building/working in. Additionally, it isn't feasible for us to create and maintain transformers to change normal HTML into different framework-specific versions (testing this adds a lot of overhead and frameworks are a moving target). The required UI to offer this to users when viewing a component might also add more complexity for users.

I've made note of this request, and will keep you posted on any developments, but at current this doesn't seem feasible.

**Comment by ajonp** [comment]
Just a follow up if anyone wants an easy way of converting.

https://transform.tools/html-to-jsx
