### ISSUE TITLE
Form styling selectors are removed by purgeCSS despite adding `[type='text']` into the purgeCSS safelist option. 

### ISSUE THREAD

**Issue by daemonsy** [tailwindlabs/tailwindui-issues#419]
URL for category:  https://tailwindui.com/components/application-ui/forms/form-layouts

**Describe the bug**
Form styling selectors are removed by purgeCSS despite adding style selectors `[type='text']` etc into the purgeCSS safelist option. 

**To Reproduce**
1. Using Rails, so my input builders are like `<%= f.text_field :some_text_field %>`, hence the view templates don't include raw input tags.
2. When using this command to build, `postcss input.css -o ./styles.css --env production`, the output CSS doesn't include `[type='text']` selectors for the form. 
3. Tried adding `[type='text']` selectors into the `safelist` options, but it was still purged away. 
4. If I created an unused view template and added html like `<input type='text'>` in the markup, the CSS output now includes `[type='text']` selectors. 

```javascript
tailwind.config.js
module.exports = {
  purge: {
    content: [
       'my_views/**/*.html.erb'
    ],
    options: {
      // What I have now. Tried many combinations, including using deep, greedy
      safelist: [/col-span/, /type='text'/, /\[type='w+'\]/],
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
  ],
};

```

```javascript
//postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```

```css
/* input.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

```

**Comment by daemonsy** [comment]
After posting, I tried poking at it again. If I put a very loose `safelist: [/type/]` , it seems to work. 

If it's just matching the selectors, perhaps it will be good to have some documentation on a reasonable matcher for matching the form styling elements, since its a common enough case that to have to safelist these selectors.

**Comment by davidluhr** [comment]
@daemonsy Thanks for reporting this. My guess is that Purge CSS is looking for double quotes (`"`) instead of single quotes (`'`), as this is how the CSS file would be authored.

Looking at their documentation, I'm guessing the safelist looks for an exact match with the quote characters as part of the regex: https://purgecss.com/safelisting.html

If you do find an issue, I would recommend filing one on their GitHub repo: https://github.com/FullHuman/purgecss

Hope this helps! I'm closing this issue for now as I don't believe this involves Tailwind UI itself.
