### ISSUE TITLE
Modals don't seem to be height-responsive.

### ISSUE THREAD

**Issue by mikebronner** [tailwindlabs/tailwindui-issues#42]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Simple alert with left-aligned buttons (and possibly the others as well)

**Describe the bug**
When modal height is greater than screen height, one cannot access the sections extending beyond screen height.

**To Reproduce**
1. Add a modal with lots of content to make it about 3 times as tall as the example.
2. Open the modal on a small screen.

**Expected behavior**
Thinking that giving the modal vertical scrollbars and some form of indicator to let the user know that there is more to the modal.

**Additional context**
It's not that we cannot create our own solution to the problem, its that we would love to see how something like this would be implemented with a lot of forethought and best practices in mind.

**Comment by simonswiss** [comment]
Hi @mikebronner! 👋  

I would argue that in terms of best practices, if the content of the modal is larger than the screen, it should perhaps not be a modal.. I am however sure that there are cases where this is not practical.

What I _would_ do is wrap the modal in an extra containing div with the following classes:

```html
<div class="absolute inset-0 flex items-center justify-center py-12">
  <!-- modal here -->
</div>
```

And then add the following classes to the actual white modal container: `max-h-full overflow-auto`

You could probably also move the logic for show/hide and animation transitions onto the (new) parentmost div.

What this would do is make sure the modal is never higher than the viewport (and add some vertical padding that you can probably tweak on certain breakpoints to your liking), and then vertically center the modal.

If there is more content that the viewport can contain, a scrollbar will show within the modal:

#### With small amount of content

![image](https://user-images.githubusercontent.com/485747/89854990-af60d880-dbd8-11ea-8adc-3360504ce258.png)


#### With large amount of content


![long-modal](https://user-images.githubusercontent.com/485747/89855413-c227dd00-dbd9-11ea-9c95-f178edf87702.gif)

---

I am not sure this is something we want to add to Tailwind UI modal components, since we're deliberate about these component containing small amounts of content, but.. this is how I would personally solve this overflowing content issue. 👍

**Comment by mikebronner** [comment]
@simonswiss Thanks, yes, I solved it in a very similar manner. The one area use-case I have for this is lead capture forms.

**Comment by simonswiss** [comment]
So, we're actually going to fix this and make it look a little better, with the scrollbar not inside the modal. Stay tuned! 👍

**Comment by dwainscheeren** [comment]
Any news on this?

**Comment by lnfel** [comment]
I made some modification to simonswiss' answer:

```
<div class="absolute inset-0 flex items-center justify-center py-12">
    <div class="modal">
        <div class="modal-heading">Some modal title</div>
        <div class="content max-h-96 overflow-y-auto"></div>
    </div>
</div>
```

Just move the max height and scroll bar into the modal's content, this makes the modal heading and close button always visible.
Then we got this baby right here:
![image](https://user-images.githubusercontent.com/47680867/116501196-cc624680-a8e2-11eb-8662-837b83cbf589.png)
