### ISSUE TITLE
No Javascript reliance :)

### ISSUE THREAD

**Issue by neuroswarm** [tailwindlabs/tailwindui-issues#420]
I would like to request TailwindCSS rely less on javascript to perform simple UI changes (hide/show) that should be handle by CSS.  Javascript costs more CPU, and quite frankly it is less elegant than using pure CSS to get the job done smoothly.

For instance the navbar code you have available on TailwindUI or various other elements do no work without javascript.  It's shameful for what is touted as a CSS Framework.  You don't need anything but CSS to hide a navigation menu dropdown, and to show it when a user hovers or clicks on it.

Why the reliance on javascript?  Please explain.

**Comment by davidluhr** [comment]
Thank you for this feedback.

We aim to only use JavaScript when it is necessary for custom functionality and interaction. Most CSS-only techniques for showing/hiding UI (such as a dropdown, accordion, menu, etc.) rely on things like the checkbox hack or do not support keyboard navigation. As a result, they are largely inaccessible.

Accessibility is a major focus of Tailwind UI, and JavaScript is often required to build interactive components, per accessibility best practices. For example, all the design patterns demonstrated by WAI-ARIA involve JavaScript to make the functionality possible and also handle keyboard focus properly: https://www.w3.org/TR/wai-aria-practices-1.1/#aria_ex. HTML, CSS, and JavaScript are the 3 main pillars of the web, and we follow best practices with all 3 languages working in tandem to create a performant and accessible experience.

It should be noted that Tailwind UI doesn't provide JavaScript code directly, as those implementation details vary by project and are largely framework dependent.

As accessibility advocates, we hope that HTML and browser standards continue to evolve over time to introduce more native elements that have this functionality and accessibility baked-in. We opt to use standard HTML elements with native behavior whenever possible, but the reality is that most custom UI with any interactivity will have some reliance on JavaScript.

Feel free to continue the conversation and let me know if there's any other questions around this I can answer. I appreciate the feedback and am closing this issue for now, but feel free to re-open if you have further suggestions around this.

**Comment by inopinatus** [comment]
I sort-of understand this position but as a default assumption it's an open invitation to breach [the first rule of ARIA](https://www.w3.org/TR/using-aria/#firstrule).

I believe that's a reason to support ARIA decoration of _HTML that already works_, progressively enhanced via Javascript. 

When a website demands that I enable Javascript to make it function _at all_, I am very likely to simply leave it.  I am not alone in this preference. Adopting the WAI guidelines wholesale is a divisive choice, not an inclusive one.

These recommendations are practically an alien dialect of HTML from a standards body in direct competition with the WHATWG (who actually develop HTML), so hanging one's hat on the W3C/WAI is not a technical choice, it is a political choice with technical, social, and product consequences, such as the TUI form toggle that does not update form state, or the expandable sidebar sections that reinvent `<details>/<summary>`.

I (and others) have instead adapted Tailwind UI components to use HTML Living Standard + CSS native/builtin behaviours for toggles/tabs/slideovers/modals/dropdowns, so that my service actually works out of the box, and then applies progressive enhancement via JS for ARIA hints and minor cosmetic aspects. However, we are forbidden by the license from sharing these components.

I think "shameful" is a stronger term than I'd choose however; I'd go with "mild disappointment" myself. Tailwind is otherwise so well aligned with the server-rendered progressively-enhanced plain HTML philosophy. Thankfully, the components themselves are not slathered with ARIA attributes the way some toolkits do (often in violation of [No ARIA is better than Bad ARIA](https://w3c.github.io/aria-practices/#no_aria_better_bad_aria)) making them readily adaptable and still just as beautiful.

c.f. [ARIA is Spackle, Not Rebar](https://css-tricks.com/aria-spackle-not-rebar/).

_This comment brought to you with JS disabled._
