### ISSUE TITLE
Could you please close tags like `img` or `input` ?

### ISSUE THREAD

**Issue by l0c0luke** [tailwindlabs/tailwindui-issues#422]
When copying and pasting into a JSX app with standard linting involved, I get errors because img and input tags are not self closing.

`<img ...>` really should be `<img ... />` and the same for `inputs`

Thanks for a great library!

**Comment by adamwathan** [comment]
Hey! We have plans to add first-class "copy as JSX" support which will help this I think, but in the mean time a lot of folks (myself included) use this nice bookmarklet @RobinMalfait wrote to convert to JSX:

https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676

It handles converting class to className, properly camel-casing SVG attributes, changing "for" to "htmlFor", etc.

I don't think we will change how self-closing tags are handled in the pure HTML examples since doing so doesn't really solve the JSX problem, and not using the closing slash seems much more common in vanilla HTML than using it.

Hope the bookmarklet is more helpful in general anyways though 👍
