### ISSUE TITLE
Add stimulus support

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#459]
Hi :),

It would be great to have Stimulus support like React / Vue soon.

**Comment by davidluhr** [comment]
@seb-jean Could you elaborate on what is needed to support Stimulus?

In my experience, most of the HTML work for Stimulus is adding custom `data-` attributes for your specific controller, target, and action. In order to support all projects, we don't provide JavaScript as part of Tailwind UI, so I'm not sure that we'd be very helpful by adding example attributes, since we don't know how the components will be used. The current features for React/Vue simply transform the HTML into respective flavors of markup (JSX, for example), but with Stimulus I don't believe any transformation is needed.

Feel free to let me know if I'm missing something!

**Comment by davidluhr** [comment]
@seb-jean Sorry; I completely misinterpreted your request. My mind was stuck on the copy code to clipboard feature, which is why all I talked about was markup. My mistake!

I caught up with the team and we've made note of adding Stimulus support similar to the React/Vue componentization that you were referring to. Please note that we are starting with React and Vue, and we hope to support other frameworks in the future, based on demand.

Sorry for the miscommunication and thanks for your suggestion!

**Comment by xt0rted** [comment]
This probably goes along with the [web components](https://github.com/tailwindlabs/headlessui/issues/210) request. [GitHub's Catalyst project](https://github.com/github/catalyst) is inspired by Stimulus and is what I'm using in my projects. The only way I got some of the Tailwind UI components to work was by building web component versions of the Headless UI React/Vue components.
