### ISSUE TITLE
Missing code in Content Section - Split With Image

### ISSUE THREAD

**Issue by toddmurphy** [tailwindlabs/tailwindui-issues#482]
### Describe the problem:
There are missing classes in the component code that when you look at the webpage it's fine, but when you look at the code, it's missing the code that gives the styles in the code. I installed the typography library.

### Link to a minimal reproduction:
Here's a picture of the code from Tailwind CSS site 

## Code
As you can see, there are missing classes to give the Preview output. I'm curious how the Preview shows the correct styling without the classes attached.
![Screen Shot 2021-02-06 at 6 48 56 PM](https://user-images.githubusercontent.com/7282612/107131461-d1e45d80-68ac-11eb-9981-f290b1d72300.png)

##
Preview of Code on Tailwind
![Screen Shot 2021-02-06 at 6 49 47 PM](https://user-images.githubusercontent.com/7282612/107131465-df014c80-68ac-11eb-90a0-15af80e98a9b.png)

## My website 
As you can see, I'm missing the styles as well when I copy the code and view it.
![Screen Shot 2021-02-06 at 6 55 46 PM](https://user-images.githubusercontent.com/7282612/107131477-fb9d8480-68ac-11eb-8f00-41a3a8a3662f.png)

**Comment by davidluhr** [comment]
@toddmurphy The component code is all there and is working as expected. Please note that Tailwind UI components are presented in the example frame on the website, which has a max-width set on it, and occasionally includes example background colors or padding. We don't include these opinionated example details, so that customers can use the components wherever they see fit without having to remove unwanted code.

In this case, the content section can be placed wherever it is needed, and the image/prose will each occupy half of the available space. In your screenshot, it looks like you have quite a large viewport, so the content section will span the full width, as expected. If you don't want it to span across the entire screen, you could wrap the content section in an element that has a max-width.

Closing this issue, as the component's code is correct, but happy to respond here to any questions/feedback you have!
