### ISSUE TITLE
Flash of open dropdowns on page load

### ISSUE THREAD

**Issue by ep-01** [tailwindlabs/tailwindui-issues#491]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens
- Component name: Dropdowns

**Describe the bug**
Dropdown options and context menus are not hidden by default; instead they are hidden by javascript, which creates a flash of open dropdowns on page load.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/page-examples/home-screens
2. In the first example, "Full-width with sidebar", right click and select "Reload Frame" a couple of times to observe the behavior. Opening the browser's devtools exacerbates the issue.

**Expected behavior**
Dropdown options and context menus should be hidden by default instead of flashing until javascript hides them.

**Screenshots**
![image](https://user-images.githubusercontent.com/75614074/107615283-889d6080-6c54-11eb-962c-e42d36ccb542.png)
![image](https://user-images.githubusercontent.com/75614074/107615202-6a376500-6c54-11eb-9af4-9840f996e9bd.png)

**Browser/Device (if applicable)**
 - OS: macOs
 - Browser Chrome 88, Firefox 85

**Comment by adamwathan** [comment]
Hey! I agree you should hide these by default when you implement the JavaScript, but since we don't actually provide any JavaScript there's not really any way for us to do this that is universal. We could add an inline style of `display: none;` to everything that should be hidden by default, but that would be confusing to people translating things to React or Vue where the solution to this would be totally different.

So no plans to make any changes here for the vanilla HTML output I don't think, but once we release official examples using common JS libraries I think this will be less of a concern.
