### ISSUE TITLE
'Updated' badge on updated sections?

### ISSUE THREAD

**Issue by gavinhewitt** [tailwindlabs/tailwindui-issues#50]
And maybe a 'new' badge on newly added items? It' now hard to see what's new.

**Comment by DanHarrin** [comment]
The team have now created a [changelog](https://www.notion.so/Tailwind-UI-Changelog-3698ab7cba254cd2bbcbcc30d132651d) so you can see any component additions and updates.

Hope this helps.

**Comment by adamwathan** [comment]
Yeah this would be nice to have, unfortunately it's probably a couple of days work because it would mean re-writing our import process to be much more intelligent and preserve timestamps. Right now we just delete every component and re-import everything fresh on every deploy which is reliable and simple, but means every component looks equally "new" from the app's perspective so it's not something we can display dynamically.

Definitely something to explore in the near-ish future but don't want to prioritize it over actually building components for y'all.

**Comment by gavinhewitt** [comment]
> The team have now created a [changelog](https://www.notion.so/Tailwind-UI-Changelog-3698ab7cba254cd2bbcbcc30d132651d) so you can see any component additions and updates.
> 
> Hope this helps.

Thanks, but it was actually the email/changelog that made me write the suggestion ;-) I found myself going back and forth between the changes and the website to see what was updated. I then thought a label would be clearer.

**Comment by gavinhewitt** [comment]
> Yeah this would be nice to have, unfortunately it's probably a couple of days work because it would mean re-writing our import process to be much more intelligent and preserve timestamps. Right now we just delete every component and re-import everything fresh on every deploy which is reliable and simple, but means every component looks equally "new" from the app's perspective so it's not something we can display dynamically.
> 
> Definitely something to explore in the near-ish future but don't want to prioritize it over actually building components for y'all.

I understand. Keep up the awesome work!

**Comment by simonswiss** [comment]
I have captured this request internally, and will now close this issue. 

If we get around to having some time to implement it, it would be a nice addition - thanks for the suggestion! 👍
