### ISSUE TITLE
Menu component does not work on mobile and

### ISSUE THREAD

**Issue by growandwin** [tailwindlabs/tailwindui-issues#500]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/navigation/navbars#component-b6bd4615a762a0d24780157803ad319e
- Component name: Navbar with search

**Describe the bug**

**To Reproduce**
1. Copy paste the code to a div in a new component in Next.js. Install and update config with tailwind forms. 
2. Save the component and include it on a new page to test
3. There will be a lot of errors with unclosed img tags and comments. 
4. Close the unclosed tags by adding / before >. Remove the comments from code. 
5. Display the component in a new empty Next.js page 

**Expected behavior**
Menu that is nice and profile icon that extends after clicking. 
A burger menu that shows when the browser resolution is shrinked. 

Instead there is the opposite of the expected behavior. 

**Screenshots**
![tailwind - profile submenu doent hide](https://user-images.githubusercontent.com/41911497/107978102-86246900-6fbc-11eb-9f20-67cc88e243e1.PNG)
![tailwind - burger doesnt expand](https://user-images.githubusercontent.com/41911497/107978109-89b7f000-6fbc-11eb-9e9a-1a0c4569c719.PNG)

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] Up to date Windows 10 pro
 - Browser [e.g. chrome, safari] Newest Firefox, Chrome

**Comment by adamwathan** [comment]
Hey! Tailwind UI does not include any JS, so you need to implement any interactive behaviors like opening menus yourself using whichever tools you prefer.

We have some documentation on integrating with JavaScript frameworks here:

https://tailwindui.com/documentation#integrating-with-javascript-frameworks

We're working on official support for popular JS frameworks, but at the moment Tailwind UI is very much "bring your own JavaScript" in order to make it useful to as many people as possible.

For converting our HTML to JSX, you can use a tool like this:

https://transform.tools/html-to-jsx

That will automatically handle the changes you mentioned like changing "class" to "className", "for" to "labelFor", or adding the `/` characters to self-closing tags.

The comments in the code explain all of the different styles you need to add for the different states of the interactive components, so you'll certainly want to keep those around for reference as you implement the interactive behaviors.

**Comment by growandwin** [comment]
Thanks for fast reply. Now I understand. The converter is working well. 

But what about the mobile version? I think the mobile version should work in pure tailwind without additional javascript.

**Comment by adamwathan** [comment]
Cool glad that helped! For the mobile menu there still needs to be some sort of click handler to open and close it, which you could implement with pure CSS with some hacks like hidden checkboxes and stuff, but those solutions have a lot of accessibility issues so it's much better to implement them with JS and follow something like the [WAI-ARIA Disclosure pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure) to make sure it works well for keyboard and screen reader users.
