### ISSUE TITLE
Improper Use of Definition Lists (dl, dt, dd)

### ISSUE THREAD

**Issue by Adrianjs42** [tailwindlabs/tailwindui-issues#509]
**What component (if applicable)**
- URL for category: [Feature Sections](https://tailwindui.com/components/marketing/sections/feature-sections)
- Component name: Alternative side-by-side with images

**Describe the bug**

`<dl>'`s do not contain only properly-ordered `<dt>` and `<dd>` groups, `<script>`, `<template>` or `<div>` elements.

Definition list items (`<dt>` and `<dd>`) must be wrapped in a parent `<dl>` element to ensure that screen readers can properly announce them. [Learn more](https://web.dev/dlitem/?utm_source=lighthouse&utm_medium=devtools).

Similar to issue #221 

**To Reproduce**
1. Run Google Lighthouse
2. Go to Accessibility

**Expected behavior**
No Error Messages in Google Lighthouse. Proper HTML

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**
Every Component with dl should be checked.

**Comment by davidluhr** [comment]
@Adrianjs42 Thanks for reporting this. I'm looking into ways to improve the `<dl>` markup used in this component and others (such as those mentioned in https://github.com/tailwindlabs/tailwindui-issues/issues/407).

It's valid to have a single child `<div>` between the `<dl>` and the `<dt>`/`</dd>` elements, but not multiple layers of nested `<div>` elements between the definition list parent/child elements.

I will keep you updated on improvements to this, because we want to make sure the markup is valid.

**Comment by davidluhr** [comment]
@Adrianjs42 Alright, after digging into all uses of `<dl>` in Tailwind UI, I've updated all related components to only have a single `<div>` between the `<dt>` and `<dd>`, which should pass the HTML Validator.

Thanks again for bringing this to our attention; accessible and valid HTML is really important to us! The corrected components should appear on the site shortly.
