### ISSUE TITLE
Modals not centered on mobile (viewport width <640px)

### ISSUE THREAD

**Issue by zmwangx** [tailwindlabs/tailwindui-issues#510]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Modals

**Describe the bug**

Modals are not centered on mobile (<640px); instead they are a fixed padding away from the bottom of the viewport.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/overlays/modals;
2. In any example, drag the viewport divider all the way to the left;
3. The modal stops being centered once the viewport is narrower than 640px; instead, the modal is always 5rem from the bottom of the viewport due to a `pb-20`.

**Expected behavior**
Modals are always centered, including on mobile.

**Screenshots**

<img src="https://user-images.githubusercontent.com/4149852/108954689-2575ea00-76a8-11eb-92db-6cf1f60852fa.png" width="300">

**Browser/Device (if applicable)**
N/A, not OS/browser dependent.

**Comment by davidluhr** [comment]
@zmwangx This is expected behavior, and can be customized as you see fit. It's considered best practice to keep dialogs closer to the bottom of the screen on mobile to help with ergonomics, and this is often seen in iOS, Android, and mobile apps.

If you'd like them to be centered at all breakpoints, then you can remove the `pb-20` on the modal and also update the "centering element" to appear at all breakpoints like so:

```html
<!-- This element is to trick the browser into centering the modal contents. -->
<span class="inline-block align-middle h-screen" aria-hidden="true">&#8203;</span>
```

**Comment by yan3321** [comment]
https://user-images.githubusercontent.com/9079480/156927166-5356aba0-ba5c-4c99-ba5f-17f3be4eae5f.mp4

Hi! Just came across this issue and tried @davidluhr's recommended solution, but it doesn't seem to have the intended effect.

Tailwind Play link: https://play.tailwindcss.com/kVBwVFfR95?size=636x855

Is there anything I'm missing?
