### ISSUE TITLE
Call to action button has extra borders (Marketing: Landing Page Examples)

### ISSUE THREAD

**Issue by kendalled** [tailwindlabs/tailwindui-issues#516]
**What component (if applicable)**
- URL for category: [https://tailwindui.com/components/marketing/page-examples/landing-pages](https://tailwindui.com/components/marketing/page-examples/landing-pages)
- Component name: Background image hero with alternating features

**Describe the bug**
The call to action button in the top right (gradient of indigo shades, says 'Sign up') has extra borders on the left and right. The left is a blueish color while the right has an indigo shade. Neither match the button and it appears to be a visual bug. 

**To Reproduce**
1. Go to 'Landing Page Examples'
2. Click on 'Background image hero with alternating features'
3. See button with extra borders

**Expected behavior**
The gradient to clip to the edge of the button on both sides.

**Screenshots**
<img width="342" alt="Screen Shot 2021-03-03 at 2 08 54 PM" src="https://user-images.githubusercontent.com/22782727/109858605-020fe980-7c2a-11eb-8a61-2bb536265a66.png">
<img width="335" alt="Screen Shot 2021-03-03 at 2 09 32 PM" src="https://user-images.githubusercontent.com/22782727/109858675-1b189a80-7c2a-11eb-9526-91513babddea.png">

**Browser/Device (if applicable)**
 - OS: Any
 - Browser: Any
 - Version: Latest

**Additional context**
Hope this helps!

**Comment by davidluhr** [comment]
@kendalled Great catch! Turns out this is how transparent borders appear on top of gradient backgrounds in CSS (even outside of Tailwind CSS).

Hmm…we'll have to think of a different way to style gradient buttons to have consistent box sizing with other buttons. I'll keep you updated on what we do! Thanks for reporting this.

**Comment by kendalled** [comment]
@davidluhr Thanks! Let me know if you figure out / push a solution. Love the work you guys have done so far. Also, I noticed your youtube video "Customizing your design system" is actually titled "Customizing **you** design system". Have a great week! <img width="915" alt="Screen Shot 2021-03-08 at 1 02 12 PM" src="https://user-images.githubusercontent.com/22782727/110361821-8984a080-800e-11eb-9a86-b97d81366a1f.png">

**Comment by davidluhr** [comment]
@kendalled Thanks for letting us know about the YouTube video title. Looks like it was fixed recently.

**Comment by kendalled** [comment]
Is this being worked on still?

**Comment by davidluhr** [comment]
@kendalled Sorry for the delayed response. It took a while to find a fix, but the solution is to use `background-origin: border-box;` so that the background image gradient spans across the entire button, including the transparent border.

I've actually added dedicated `bg-origin` utilities to Tailwind CSS so we can solve this issue directly in Tailwind UI: https://github.com/tailwindlabs/tailwindcss/pull/4117

Currently, we are waiting for a few new features to be ready in Tailwind CSS so we can do a minor version release, at which point we will be able to incorporate this fix using the new utility classes.

As a short-term workaround, you could manually add this class to your project:
```css
.bg-origin-border {
  background-origin: border-box;
}
```

Thanks again for reporting this; it helped us improve both Tailwind CSS and Tailwind UI! I'll let you know once the final fix is live.

**Comment by davidluhr** [comment]
@kendalled Thanks again for all your patience with this issue!

With the release of [Tailwind CSS v2.2](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0), we now are able to use the `bg-origin-border` utility, which solves this visual issue.

The corrected version should be live on the site shortly!
