### ISSUE TITLE
AlpineJS - Components that to also be downloaded with AlpineJS

### ISSUE THREAD

**Issue by btihen** [tailwindlabs/tailwindui-issues#535]
I would love it if you offered a button that had the code for AlpineJS - since that is what you are going to do for React and Vue - why not the default behavior for AlpineJS too.  You have it in your site anyway - that would be easier than inspecting and selecting the code and copying it.  I'd be willing to pay extra (depending on the cost) for the default behaviour working out of the box.

**Comment by adamwathan** [comment]
Hey! We're planning to add proper support for Alpine in the future, and just starting with React/Vue because we have to start _somewhere_.

The reason we don't make the current Alpine demos easily available (other than copying from dev-tools) is that the code is very incomplete and not production ready. They are just quick proof-of-concept snippets to demo the different states, and don't include proper keyboard support, focus trapping, or other accessibility concerns. Some things behave in totally demo-specific ways as well, like the modal dialogs that automatically re-open after you close them.

First-class production-ready Alpine examples are definitely something we hope to tackle though!
