### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by itsjab** [tailwindlabs/tailwindui-issues#553]
I'm sure you have thought about a dater picker, maybe you are already working on a component.

Nonetheless, date pickers are widely used, but relatively time-consuming to build. So, I assume many people would benefit from Tailwind UI providing them. 

**Screenshots**
AirBnB's date picker works very smoothly, especially for selecting date ranges.
<img width="900" alt="Screenshot 2021-04-11 at 11 48 45" src="https://user-images.githubusercontent.com/12183357/114299578-60977580-9abc-11eb-9cf2-15989ea00821.png">
<img width="716" alt="Screenshot 2021-04-11 at 11 49 49" src="https://user-images.githubusercontent.com/12183357/114299579-63926600-9abc-11eb-889d-53d4d7ef151f.png">

**Additional context**
I'd be great to have different status indicators for dates, similar to what is already available for select fields.

Thanks in advance.
Cheers, Jan

**Comment by davidluhr** [comment]
@itsjab Thanks for the suggestion! This is actually our most popular request, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/jVnND6De/47-date-picker

**Comment by mikeycannon** [comment]
@davidluhr  this has almost 3x more requests than the current work in progress on the roadmap. Currently rebuilding a large application in Tailwind using TailwindUI and I'm wanting to wait for this component to be complete but getting close now to working on a custom one. Any idea when you think it will be started?

**Comment by adamwathan** [comment]
@mikeycannon Hey! Stuff in the "Ideas" column is just stuff suggested by the community, there are no guarantees we work on anything in there. Adding datepickers is a huge project and would involve first building a datepicker for Headless UI, so it's a big commitment and something we aren't prepared to commit to yet.

At this point Tailwind UI is out of "early access" and we consider it "complete" in the sense that we think that what's included is a great value for the price, but we do still plan to keep updating it and improving it and customer feedback is a big part of that. 

I'd like to explore adding datepickers one day for sure but I would not wait for us to build one because we might never do it. Hope that makes sense. I don't want people to get the wrong impression with stuff in the "ideas" column — if people start looking at it as stuff that's coming for sure we'll likely have to just get rid of the public Trello board to avoid mismatched expectations.

**Comment by mikeycannon** [comment]
No worries. Just making sure you weren't moving it into backlog/designing any time soon. A "nope" would have been good enough for me but appreciate the detailed reply. I'm just being lazy waiting for you guys to do the work 😂
