### ISSUE TITLE
Jitter and no transition on on settings screen example when opening menu

### ISSUE THREAD

**Issue by pdevito3** [tailwindlabs/tailwindui-issues#561]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-b9b7390f97e69f1148aa2d030e274ae9
- Component name: Brand nav with overlap and sidebar form

**Describe the bug**
When clicking the hamburger menu the search input has a distinct jitter. It also doesn't look like the transition is working.

**To Reproduce**
1. Open in mobile view
2. Click the hamburger menu
3. no transition and search input jitter

**Expected behavior**
No search jitter and the menu should transition out

**Screenshots**
Don't have a good way to record a gif on this comp, sorry :-(

**Browser/Device (if applicable)**
 - OS: Windows 10
 - Browser Firefox
 - Version 87.0 

**Additional context**

**Comment by davidluhr** [comment]
@pdevito3 Thanks for reporting this. Please note there is no transition for these menus, so that is expected.

I tested this on Windows 10 in Firefox and Edge. The jitter you're setting is actually a scrollbar appearing temporarily as the content's height changes with the expanded menu. This is expected behavior coming from the operating system, and not something caused by Tailwind UI.
