### ISSUE TITLE
Disclosure not exported

### ISSUE THREAD

**Issue by caestrada** [tailwindlabs/tailwindui-issues#565]
**What component (if applicable)**
- URL for category: 
- Component name: `Disclosure`

**Describe the bug**
I'm trying to import **Disclosure** from **@headlessui/react** but I receive an error stating:
`Module '"@headlessui/react"' has no exported member 'Disclosure'.ts`

**To Reproduce**
Just import **Disclosure** from **@headlessui/react**

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Make sure you are on the latest version of Headless UI. `npm install @headlessui/react@latest`.

Some people have reported this issue, and these were the common culprits:
- Not using the latest Headless UI version (double check `node_modules`)
- When using tools like Next.js, nuke the `.next` folder because caching

Are you using Next? Or tools that use a cache? Try nuking that!

Let me know if any of these steps fix it for you!

**Comment by caestrada** [comment]
Hey Robin.

That was the issue! As soon as I switched to `latest` and removed the `.next` directory issue got fixed. 

Thanks for the quick reply.
