### ISSUE TITLE
Pagination section are missing some UX states (selected page, focus, etc)

### ISSUE THREAD

**Issue by StErMi** [tailwindlabs/tailwindui-issues#592]
**What component**
- URL for category: https://tailwindui.com/components/application-ui/navigation/pagination
- Component name: Pagination

**Describe the bug**

1) there's not a UI state to showcase which page is currently selected at least for the first example (Card footer with page buttons)
2) there's not a UI state for the focus page number (all examples)
3) the UX behavior for the hover status is different if compared to desktop/mobile view. In the desktop view when you hover a page number the bg-color change, in the mobile view, when you hover the Prev/Next button the text-color change

**Browser/Device**
 - OS: macOS
 - Browser: chrome
 - Version: 90.0.4430.85

**Additional context**

Are the page numbers missing the focus state because they are not buttons and they should behave differently?
So should we change them to buttons?

**Comment by davidluhr** [comment]
@StErMi Thanks for reporting this!

1. I've updated the first pagination example to have a current state, and added `aria-current="page"` for accessibility.
2. Because pagination uses links, we do not provide custom focus styles. Currently in Tailwind UI, we provide custom keyboard focus styles for interactive elements that aren't links.
3. Good catch. I've updated the hover styles to be consistent in how background and text color change.

The updated version should be live on the site soon!

**Comment by StErMi** [comment]
Hi @davidluhr thank you for the answer. Using links for the pagination is an accessibility choice? I know that Tailwind is investing a lot of time (also thanks to you!) into accessibility so I would also like to learn which are the best way to improve accessibility while I design my website.
