### ISSUE TITLE
`<Popover />` render props out of sync

### ISSUE THREAD

**Issue by lensbart** [tailwindlabs/tailwindui-issues#595]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/elements/flyout-menus#component-988e9eed61ec84450b9650c7f6ad805e
- Component name: `Popover`

**Describe the bug**
If I use `open` from the Popover render props to toggle between two icons depending on whether the menu is open, I don’t observe the desired behaviour under certain circumstances. Toggling works as expected when clicking on the icon itself, but it doesn’t work when closing the menu via the Escape key or by clicking outside of the menu

**To Reproduce**
```tsx
import { Fade as Hamburger } from 'hamburger-react'
import { Popover } from '@headlessui/react'

<Popover className="relative">
  {({ open }) => (
    <>
      <Popover.Button className="text-gray-300 group rounded-md inline-flex items-center text-base font-medium mr-4 mt-1.5">
        <Hamburger rounded toggled={open} />
      </Popover.Button>
      // ...
    </>
  )}
</Popover>
```

**Expected behavior**
One version of the icon shows when the menu is open, another version shows when closed, regardless of how the menu is closed

**Tailwind version**
 - latest

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This looks like a bug in `hamburger-react`, more specifically here: https://github.com/luukdv/hamburger-react/blob/master/src/Burger.tsx#L69 they are using `toggled` if you pass it in, otherwise use the internal state. However, they have to check for `undefined` not truthyness. This results in the fact that you can never untoggle.

Here is a an example where the `state` is synced correctly: https://codesandbox.io/s/winter-dew-4euch?file=/src/App.js
