### ISSUE TITLE
Multi-level sidebar with icons layout non-ideal with longer labels.

### ISSUE THREAD

**Issue by OwenMelbz** [tailwindlabs/tailwindui-issues#607]
**What component (if applicable)**
https://tailwindui.com/components/application-ui/navigation/sidebar-navigation#component-ea27fcb96a81748146d26ffa281c3f6d

**Describe the bug**
![image](https://user-images.githubusercontent.com/1094740/117144920-6ece6e00-adaa-11eb-9c00-df3f26f9dc55.png)

**To Reproduce**
1. Inspect a menu item element
2. Create a longer name

**Expected behavior**
I'd imagine the expected outcome would be the icon stays the same size and the text would remain left aligned - not centered

**Comment by davidluhr** [comment]
@OwenMelbz Thanks for reporting this!

I've updated all sidebar components to allow text to wrap and be left-aligned instead of centered. The icons also will retain their size and won't shrink if the text wraps.

Thanks for finding this and helping us improve the components! The fixed version should be live on the site soon.
