### ISSUE TITLE
Consider adding an option to customize brand colors instead of a default color.

### ISSUE THREAD

**Issue by vignejs** [tailwindlabs/tailwindui-issues#608]
I think it would be great if we get to customise brand colours like primary, secondary with css variables or tailwind config, instead of that default static indigo color, which we have to change in every component for our current project.

**Comment by davidluhr** [comment]
@vignejs Thanks for the suggestion. We've had similar requests in the past, and unfortunately there are some complexities that make this not very feasible.

The central challenge is ensuring sufficient color contrast across various themes or brand color scales. For example, each component and page example in Tailwind UI is specifically designed with color contrast in mind, so swapping between other colors in the palette (or a custom color) may not have sufficient contrast.

Additionally, a hurdle with semantic color names (primary, secondary, etc.) is that the naming doesn't scale well to accommodate all situations. Even outside of Tailwind CSS, many design systems that might use semantic class names stick with a color value naming scheme (red-100, red-200, etc.) to avoid this limitation. This would make mapping semantic names to colors in each component very difficult to achieve or maintain.

Due to these reasons, I'm not sure it is possible for Tailwind UI to provide this. But, I've made note of this feedback with the team, and we do think about these considerations quite a bit. I'm closing this issue for now, but feel free to reply here with any further thoughts and suggestions, as we appreciate your ideas!
