### ISSUE TITLE
Shifting heights when using buttons in slide-over with overflow

### ISSUE THREAD

**Issue by Caroga** [tailwindlabs/tailwindui-issues#624]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/slide-overs#component-62a04be4dcfb133783a1a2b1774a73fa
- Component name: Slide-over - File Details

**Describe the bug**
I stumbled across the problem on one of the sidebars where repeating content adds to the height of the body that in turn adds a vertical scrollbar. Even though the sidebar has an overflow defined, and functioning, it still adds a lot of space beneath it. 

I found that removing all the button elements solves this. I have no idea how to fix this. 

**To Reproduce**
1. Go to https://gist.github.com/Caroga/2be7b536408f23eb3c97af6c2febab15 or https://play.tailwindcss.com/lTe83HDQC0
2. Create HTML file from snippet, open it, and scroll down in the center

**Expected behavior**
Not add the space on the page when adding buttons inside the slideover.
The main section should have a fixed height/width as is your viewport where the sidebar's content can expand and have a overflow (and therefore be scrollable).

**Screenshots**
![image](https://user-images.githubusercontent.com/4005934/119271373-88244680-bc01-11eb-8af4-a1912daa33b9.png)

**Browser/Device (if applicable)**
 - OS: Windows and Linux
 - Browser Chrome
 - Version 90.0 on windows, linux unknown at the moment.

**Additional context**
I have a feeling this might not be a bug but actually something wrong with how I copy-paste this together, but Discord has never yielded any response on my questions (neither in #help nor when directly pinging) therefore this issue, I am sorry in advance.

**Comment by pjprateek** [comment]
https://play.tailwindcss.com/CyYOfFz8q4 - I removed the "h-screen" from the <div> tag just under the <body> tag.

**Comment by Caroga** [comment]
Hi @pjprateek, thank you a bunch for looking into this.
I will expand the question a bit more and edit the issue to include this.
The solution you are providing is removing the overflow entirely from the sidebar which does help but not in my case. I wish to have the page at a fixed height (entire screen) and have the sidebar's content be scrollable.

**Comment by Caroga** [comment]
To prevent confusion, this issue has not been resolved.

**Comment by Caroga** [comment]
Some more information:

To further explain the issue I am facing you can check the following page: https://play.tailwindcss.com/5WnkMWUkYz
The issue appears only on Chrome, Firefox seems to handle this correctly. 
The goal is to have nothing scrollable with the exception of the sidebar that contains the div#entry. Multiple div#entry's should trigger a scrollbar inside that div and not on the main page.

The issue occurs only on Chrome and when repeating div#entry OR when scaling the browser window.

Robin's remark to add the following DOES solve it on Chrome however, I wonder if this is the solution or if something else might be wrong: `body { @apply overflow-hidden }`

I hope this helps give a clear example of my issue. I'm sorry for any frustration I might have caused.

**Comment by reinink** [comment]
Hey there @Caroga,

So I think the issue here is simply how you're implementing the slide-over. It appears that you are placing your page content (`OVERVIEW`) within the slide-over, which isn't how this component is intended to be used. Instead, your page content should be a sibling of your slide-over component. Something more like this: https://play.tailwindcss.com/kFJFoMXg82

I hope that helps. Let me know if you have any further issues!

**Comment by Caroga** [comment]
Hi @reinink, thank you for your message. However I do not agree with closing this ticket just yet.

The issue is not that this component should be a slide-over, as I implemented the code behind this it is clearly not intended to do this.
The idea is that the last column should have scrollable content, but appears staticly. 
If a different component would fit better I would gladly implement this, but I do feel this setup should work.

**Comment by reinink** [comment]
Hey @Caroga, happy to keep working through this with you. To be totally honest, I'm not sure exactly what you're after. 😅

It appears that you're having issues with extra space being added to the page when adding buttons inside the slide-over. However, from what I can tell, this is happening in your example because you're not positioning the slide-over using something like position `fixed` and `inset-0`

If I update [your example](https://play.tailwindcss.com/OrKbfG05vv), and add these classes, that extra space goes away:

```diff
- <div class="h-screen flex overflow-hidden">
+ <div class="fixed inset-0 h-screen flex overflow-hidden">
```

Of course, that has implications on the page layout, which may or may not make sense for you.

In general though, the slide-overs within Tailwind UI are designed to be positioned `fixed`, and sit above the contents of your app. That's what I was trying to illustrate in my [last example](https://play.tailwindcss.com/kFJFoMXg82).

I hope that helps @Caroga! 🙏
