### ISSUE TITLE
AlpineJS examples / code

### ISSUE THREAD

**Issue by victorelec14** [tailwindlabs/tailwindui-issues#634]
Hello,

It is possible that you can put the components also with AlpineJS, for now they are only in VUE and React.

It seems to me that the examples were previously in AlpineJS but since the new version are they based on Vue?

Thanks

**Comment by davidluhr** [comment]
@victorelec14 Thanks for your request! This suggestion has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap. This is where the community can vote for what they'd like to us to add:

https://trello.com/c/8EZrsfzZ/121-provide-alpinejs-code-for-components

As for the default example code snippets, they have always been in HTML without AlpineJS. We use AlpineJS under the hood to drive the interactive previews, which is still visible in the iframe DOM in the examples, but please note that this code is not production-ready and not guaranteed to be fully accessible. The level of functionality and accessibility that [Headless UI](https://headlessui.dev/) offers is beyond the scope of what we can currently achieve in AlpineJS, which is why we offer HTML, React, and Vue as the final output code.

Hope this helps give context to things. Thank you!
