### ISSUE TITLE
Settings screen update state

### ISSUE THREAD

**Issue by Manubi** [tailwindlabs/tailwindui-issues#635]
Hey,

I'd like to see the update state in the settings screen. :)

Thanks for your great work. In general, there are already many states added since react and vue support but i'd love to see more as it really would save many hours of adjusting stuff. Thanks again!

![CleanShot 2021-06-02 at 16 18 19](https://user-images.githubusercontent.com/20935138/120496925-4728f080-c3be-11eb-9d80-9f17b55b5590.png)

**Comment by davidluhr** [comment]
@Manubi Thanks for your request. Can you please provide more information on the state that you'd like us to add? Would it be a spinner/saving indicator? Would you expect this to appear next to the "Update" button, or be a full-screen state?

Thanks for the extra detail on this, it'll help us understand what specifically would benefit your project.

**Comment by Manubi** [comment]
I would like to see the `<input />` when I click on Update. :) So eg. the <p>Chelsea Hagon<p> should be become the Input... 
Thanks!

**Comment by davidluhr** [comment]
@Manubi Thank you for the follow up. This would be beyond the scope of Tailwind UI, since the page examples are intended to show a specific example of how to combine other Tailwind UI components.

You could use a [Modal](https://tailwindui.com/components/application-ui/overlays/modals) with the Update button as a trigger, and place a form inside the modal. The [Headless UI documentation](https://headlessui.dev/) should be helpful if you want to create something like this.
