### ISSUE TITLE
compents should be React, Vue, HTML, and Alpine. 

### ISSUE THREAD

**Issue by AndreiMotinga** [tailwindlabs/tailwindui-issues#665]
I mean, if this is how you offer do plain js, then at you should provide code for it. otherwise, it's extra work.

**Comment by thorrak** [comment]
Unfortunately, the lack of this was ultimately why I requested a refund of Tailwind UI. I'm not developing a single-page app, and that seems to be what the Tailwind UI components are designed for. Honestly - I'd even take official renderings of the Alpine demos (which are already being built, per the documentation) if that's what is available.

**Comment by AndreiMotinga** [comment]
@thorrak Got this notification and wasn't even if sure if I wrote the message (the one you wrote) cause that's what I did. 

feeling exactly the same and got a refund. 
I like how it looks, but I'd like something more like bootstrap, where I can just take a code for a component and only pipe in my data. 

since I didn't want to use front-end framework, this doesn't work.

**Comment by davidluhr** [comment]
@AndreiMotinga and @thorrak thank you for the feedback.

Offering HTML is our main focus, so that the components can be used in any project. The Alpine code is only used to run the examples to demo interactions, but isn't 100% feature complete with the Headless UI components found in the React and Vue output.

Headless UI is still pretty new, so our initial focus is on React and Vue to meet the majority of demand from our customers. While we enjoy using vanilla JS and Alpine, they don't represent a large user base currently, which is why we've prioritized things the way we have as a small team.

I'm closing this issue for now, as you've been refunded, but please feel free to reply here with further feedback.

**Comment by AndreiMotinga** [comment]
hey @davidluhr, sorry, work is getting in the way. 

I think these components are pretty useful and tailwind is really growing on me.  Some components/pages I believe do justify the price. However, it's also not complete and lacking seriously to be used in production. 

At the moment, Rails and Turbo don't work with alpine even, and you may ask, what does it have to do with tailwind components. Well, it's exactly problem, some commonly used elements (dropdowns, some layouts) simply don't work. 

So while it looks nice and pretty, there is no way to actually bring it into the project that doesn't go full SPA path. 

I never heard of headless UI, will check it out. can I use it without react?  I'm trying to keep things simple.
