### ISSUE TITLE
Banners being dismissable

### ISSUE THREAD

**Issue by rdoyle99** [tailwindlabs/tailwindui-issues#678]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/marketing/elements/banners
- Component name:  all banners

**Describe the bug**
Each banner includes an "Exit" icon to dismiss the banner, but not the functionality to do so.

**Expected behavior**
When the banner is exited via the provided "close" icons, they should close

\

**Comment by davidluhr** [comment]
@rdoyle99 We do not include interactions for custom patterns, because we cannot predict how these components will be used.

If we provide functionality for closing the banner, then we would also need to move keyboard focus. But, there are many different ways in which banners can be opened (a button somewhere in the page, on page load, triggered by a custom action, etc.). So, even if we provided example functionality, almost all users would need to remove it or heavily customize it anyway.

I hope this helps explain why Banners don't include functionality.
