### ISSUE TITLE
File input form component does not handle drag & drop

### ISSUE THREAD

**Issue by MatthiasRMS** [tailwindlabs/tailwindui-issues#684]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: File Upload

**Describe the bug**
The file upload area is pretty large and indicates that files can be added through drag & drop but the only way to add a file is by clicking on "Upload a file".

**To Reproduce**
1. Go to 'https://tailwindui.com/components/application-ui/forms/form-layouts'
2. Drag & drop a file on the upload area
3. File will be in the browser instead of being uploaded

**Expected behavior**
The whole file upload area should be clickable and allow files to be drag & dropped.

**Comment by davidluhr** [comment]
@MatthiasRMS Thank you for the feedback.

Until the release of [Headless UI](https://headlessui.dev/) earlier this year, Tailwind UI has not included any custom functionality/interaction, which is why this component uses `<input type="upload">` under the hood, but does not have custom drag and drop features.

I'll make note of this request with the team, but please note that the component example is working as intended, since users bring their own custom functionality. Thanks!
