### ISSUE TITLE
Tailwind UI Components Details File Gallery HTML/CSS Broken

### ISSUE THREAD

**Issue by fjur** [tailwindlabs/tailwindui-issues#689]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-0218c9079330128b7d916325b9ad3f38
- Component name: File gallery

**Describe the bug**
When you scroll down in the component it doesn't contain the entire page and there is a massive whitespace gap at the bottom.

Sometimes the page properly displays and sometimes the page will have this large gap, and when it adds the gap it breaks the page

I have a dynamic list that grows, and the more the list grows the larger the gap will become, sometimes spanning 1-3 pages long of whitespace.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-0218c9079330128b7d916325b9ad3f38
2. Download File Gallery React code and create a page in next.js
3. Open the page in next.js and scroll down to bottom

**Expected behavior**
I expect there not to be a large white space at the bottom of the page.

**Screenshots**

**Browser/Device (if applicable)**
 - OS:  Mac
 - Browser Chrome 
 - Version 92.0.4515.107 (Seen on 90 & 91 as well)

**Additional context**

<img width="1602" alt="Screen Shot 2021-07-24 at 11 33 04 AM" src="https://user-images.githubusercontent.com/15708887/126878107-eb37fc7d-c352-4182-9bf7-a85344dd4d52.png">

**Comment by davidluhr** [comment]
@fjur Thank you for reporting this!

Turns out, this only happens in Chromium-based browsers. The fix is to add `relative` to outer wrapper elements that have `min-h-screen` or `h-screen` on them. I've corrected this for the example code in Home Screens, Detail Screens, and Setting Screens that have multiple scrolling regions.

Thanks again for letting us know and helping to improve things!
