### ISSUE TITLE
Make modal dismiss button not focusable

### ISSUE THREAD

**Issue by thechrisoshow** [tailwindlabs/tailwindui-issues#693]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals#component-6a0b582f00c5ec38bf748d9a75559f04
- Component name: Simple with dismiss button

**Describe the bug**
This is just a small suggestion. By adding `tabindex="-1"` to the dismiss button means it's not focusable meaning that the next focusable element will instead be autofocused.

This is handy if you have a modal that contains a form, because otherwise I was finding that the input box was not being focused initially, instead the dismiss button was (which doesn't feel intuitive to me).

i.e. change:
```
<button type="button" class="bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" @click="open = false">
  <span class="sr-only">Close</span>
  <XIcon class="h-6 w-6" aria-hidden="true" />
</button>
```

to

```
<button type="button" class="bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" @click="open = false" tabindex="-1">
  <span class="sr-only">Close</span>
  <XIcon class="h-6 w-6" aria-hidden="true" />
</button>
```

**Comment by davidluhr** [comment]
@thechrisoshow The dismiss button must be focusable for accessibility. Otherwise, keyboard users cannot close the modal. Modals use focus trapping and focus cycling, meaning focus starts on the first focusable element, and "wraps" as needed to prevent focus from leaving the modal.

Since the dismiss button is the first focusable element in the modal markup, it should receive focus. This is common practice with accessible modals.

You are free to modify the markup/functionality as you see fit, but we provide our recommended approach. Thanks!
