### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by jand000** [tailwindlabs/tailwindui-issues#721]
It would be great if the components could support [responsive images](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images?hl=en). Right now every image is a single img only. But in terms of web page speed optimisation having responsive images is essential.

**Comment by davidluhr** [comment]
@jand000 Thank you for the feedback. Any instance of an `<img>` tag can make use of `srcset` for non-art direction optimization with multiple image files.

If you need art direction, you should be able to wrap `<img>` with `<picture>`and add any `<source>` elements as needed. 

Since this is implementation-specific, it's not likely that we will provide this pattern directly in Tailwind UI, but you change the markup freely and at most you may need to move a couple classes around. Hope that helps!
