### ISSUE TITLE
E-Commerce Products accessible without Purchase

### ISSUE THREAD

**Issue by cbzehner** [tailwindlabs/tailwindui-issues#727]
**What component (if applicable)**
- URL for category: https://tailwindui.com/#product-ecommerce
- Component name: N/A

**Describe the bug**
I haven't purchased the E-Commerce Kit but I am still able to access the components. I've only purchased the "Marketing + Application UI Bundle"

**To Reproduce**
1. Go to https://tailwindui.com/#product-ecommerce
2. Click on any E-Commerce component
3. View the source code

**Expected behavior**
I expected to be redirected to an upsell upon trying to view the source code

**Screenshots**
<img width="1424" alt="Screen Shot 2021-09-05 at 8 51 06 PM" src="https://user-images.githubusercontent.com/3886290/132136640-2a14298e-a53a-4869-b706-8b8638097e61.png">
<img width="1414" alt="Screen Shot 2021-09-05 at 8 51 23 PM" src="https://user-images.githubusercontent.com/3886290/132136641-7530f6a1-7712-47fd-8525-17baf3fb610f.png">
<img width="1409" alt="Screen Shot 2021-09-05 at 8 51 34 PM" src="https://user-images.githubusercontent.com/3886290/132136642-959f50aa-2710-486d-8605-ac4b92f951bf.png">

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser Firefox
 - Version 91.0.2

**Additional context**
Let me know if you want any additional information or context. Tailwind UI has been hugely helpful to me over the past year, thanks so much for all your work on this!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

For each product we have a few components that are publicly accessible so that you can take a look and try them out before purchasing. You will notice that if you scroll down, that there will be examples that are locked (a png image is shown).

If you are not logged in and visit https://tailwindui.com then you will see a white `Try it out` button, this redirects you to a page, https://tailwindui.com/preview, with all the previewable components.

So while it is not a bug or an issue, I still appreciate it that you notified us. It just happens to be that the first 6 categories have _some_ previewable components and therefore seem to be public.
