### ISSUE TITLE
Modal Dialogs can be nested

### ISSUE THREAD

**Issue by swapnilnandgave** [tailwindlabs/tailwindui-issues#735]
**Screenshots**
![Screenshot 2021-09-09 at 2 57 09 PM](https://user-images.githubusercontent.com/1922846/132660652-7c7fb54a-524d-4b39-81b5-8efa7f2a56ca.png)

**Additional context**
In most of application, you can see nested modal dialog. Structure can be so nested in advanced application and we come to requirement where nested modal dialog will be useful. I can see single modal dialog in tailwindUI where we can capture user input but it would be great if you share your thoughts for nested modal dialogs. I have attached screenshot of vuetify where they are providing nested modal dialogs.

I am big fan of tailwindUI and excited to make any UI in tailwind. Thanks for your time

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

If you are using `Headless UI` for the `Dialog` components, then those can already be nested. Make sure that the `<Dialog/>` component is nested in another `<Dialog/>` component.
Here is an example: https://headlessui-react-qkekv2bba-tailwindlabs.vercel.app/dialog/dialog

If you mean that you want nested dialog examples in Tailwind UI, then I'm not 100% sure what you want exactly, since we already have Dialog components: https://tailwindui.com/components/application-ui/overlays/modals

**Comment by reinink** [comment]
Sounds like this is solved. Feel free to open a new issue if you run into anything further. 👍

**Comment by c316** [comment]
For my future self or other who might do a Google search, if you don't nest inside a Dialog you might see strange errors about, "Uncaught RangeError: Maximum call stack size exceeded." or some messages about <FocusTrap />

**Comment by pfcodes** [comment]
> Hey! Thank you for your suggestion! Much appreciated! 🙏
> 
> If you are using `Headless UI` for the `Dialog` components, then those can already be nested. Make sure that the `<Dialog/>` component is nested in another `<Dialog/>` component. Here is an example: https://headlessui-react-qkekv2bba-tailwindlabs.vercel.app/dialog/dialog
> 
> If you mean that you want nested dialog examples in Tailwind UI, then I'm not 100% sure what you want exactly, since we already have Dialog components: https://tailwindui.com/components/application-ui/overlays/modals

Side note: Is there a reason why the examples page is undocumented? It helped clear up a question I had about nested modals.
